### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by webtrend** [spacecatninja/craft-imager-x#1]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Description
I bought a pro license and when I tried to enter the license code on settings>plugins page, it shows me the "Lite/Trial" badge next to it.

At first I thought it was due to domain since my staging server and production server has a different domain (although no other paid licenses have caused this issue). So I changed the domain to my staging server on id.craft site. I also tried disable and re-enabling the plugin but the purchase  is not recognized.

As a result i am getting following error on my template
 

### Displayed errors, stack trace, relevant logs  

```
Could not find a registered storage with handle "aws". External storages are only available when using the Pro edition of Imager, you need to upgrade to use this feature
```

### Additional info

- Imager version and edition:
- Craft version: 3.4.5
- PHP version: 7.2
- Database driver & version:
- Plugins & versions: 3.0

**Comment by aelvan** [comment]
Hi, and thanks for checking out Imager X! :)

I think this is mostly an UI/UX "feature" in Craft. Even if you buy a Pro license and add it to the plugin, Craft doesn't automatically change the edition for you. If you only had Lite enabled before adding the license, you will still have Lite enabled after adding a Pro serial number.

But if you click on the badge, or just navigate to the Imager X page in the plugin store, and scroll down to the bottom of the edition-boxes, there should be a big "Reactivate" button underneath the Pro version. Clicking that should change to the Pro edition, and you're good to go.

Let me know if that solves it for you.

**Comment by webtrend** [comment]
Thanks for your prompt response. The error is now gone after implementing your suggestion but I am still unable to see any transformed images in my AWS buckets (or even in local cache for that matter). I am just using a very basic transform using your example
`{% set transforms = craft.imagerx.transformImage(image, 'heroImage') %}`

The `heroImage` named transform is of course defined in the config file. 

Is there anything else I need to do to generate the transformation?
