### ISSUE TITLE
Error on upgrade from Imager to Imager X

### ISSUE THREAD

**Issue by romainpoirier** [spacecatninja/craft-imager-x#10]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Description
 
I tried to upgrade from Imager following [the documentation](https://imager-x.spacecat.ninja/installation.html#upgrading-from-imager-2-0). But after pushing in prod, I got an error after syncing the project-config (using `/craft project-config/sync`). As the Craft CP and front end were stuck with this error, I had to uninstaller Imager X and then go back to Imager.

### Displayed errors, stack trace, relevant logs  

```
Installing plugin "imager-x" ... error: No plugin exists with the handle "imager-x
```

### Additional info

- Imager version & edition: v3.0.3 Pro
- Imager transformer: Craft + Imgix
- Craft version: Craft Pro 3.4.8
- PHP version: 7.1.30
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.9.6-2)
- Database driver & version: MySQL 5.7.26

**Comment by aelvan** [comment]
Think something must have gone wrong with the deploy. Did you check if the plugin actually were in the vendor folder? And that the composer autoloader had been updated? Sounds like this is more of a deploy/project config issue.

**Comment by romainpoirier** [comment]
Yep, you were probably right. I launched a couple of new deployments, and now it's correctly setup. Maybe I forgot something, like the clean uninstall of Imager plugin (from the CP settings page) before to install Imager X using Composer. Anyway, problem solved, thank you!

**Comment by aelvan** [comment]
Good to hear! :)
