### ISSUE TITLE
Cannot transform remote images with Imgix

### ISSUE THREAD

**Issue by ccchapman** [spacecatninja/craft-imager-x#102]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Transform a remote image with Imgix as your transformer
2. Transformed image URL from Imgix returns a 404

### Description

The remote URL ends up encoded within the Imgix transformed URL. The `hashRemoteUrl` configuration option appears to make no difference.

**Example**

Given a URL of `https://avatars.githubusercontent.com/u/1`, the  transformed URL will be `https://redacted.imgix.net/https%3A%2F%2Favatars.githubusercontent.com%2Fu%2F1?fit=clip&q=80&w=200&s=redacted`. This URL will 404.

Would this be supported functionality? If it is not, it would be nice to have an escape hatch to use the Craft transformer for exceptions like this.

```twig
{{ craft.imager.transformImage('https://avatars.githubusercontent.com/u/1', {
  width: 200,
}) }}
```

```php
<?php

use craft\helpers\App;

return [
    "filenamePattern" => "{fullname|hash}.{extension}",
    "imagerSystemPath" => App::env("CRAFT_STORAGE_PATH") . "/imager",
    "transformer" => "imgix",
    "imgixApiKey" => App::env("IMGIX_API_KEY"),
    "imgixConfig" => [
        "default" => [
            "domain" => App::env("IMGIX_DOMAIN"),
            "useHttps" => true,
            "signKey" => App::env("IMGIX_SIGN_KEY"),
        ],
    ],
];
```

### Additional info

- Imager version & edition: v3.4.0 Pro
- Imager transformer: Imgix
- Craft version: 3.6.11.2
- PHP version: 7.4

**Comment by aelvan** [comment]
Hi,

> If it is not, it would be nice to have an escape hatch to use the Craft transformer for exceptions like this.

To address this first, there is, you can always override the transformer at the template level by overriding the `transformer` config setting:

```
{% set transform = craft.imager.transformImage(image,  { width: 200 }, {}, { transformer: 'craft' }) %}
```

I wrote about [combining transformers in a recent blog post](http://spacecatninja.test/blog/combining-transformers-for-even-more-awesome).

But, you can of course also transform external images with Imgix. You just need to create a separate web proxy Imgix source and a profile for it in Imager's config. Both [the docs](https://imager-x.spacecat.ninja/configuration.html#imgixconfig-array) and the article I linked to above have examples for that.

**Comment by ccchapman** [comment]
Thanks for the reply! This is wonderful so I will close my issue. Sorry, I missed the Imgix external source example in the documentation.

Maybe there can be a tip in the [transforming external images](https://imager-x.spacecat.ninja/usage/#transforming-external-images) section. Otherwise it's not easily searchable.

**Comment by ccchapman** [comment]
@aelvan Would you expect that the `hashRemoteUrl` option has no affect for Imgix transforms? Their web proxy sources will have the encoded URL in the path. Is this unavoidable from Imager X's perspective?

**Comment by aelvan** [comment]
Ah, I forgot to mention that. `hashRemoteUrl` and all the other filename config settings are only applicable when using the default/local transformer. Imgix has a defined format for their URL API, there's no way to change that.

Thanks for the suggestion about adding this to the docs, will try and fill in the gaps. :)
