### ISSUE TITLE
Exception 'craft\errors\AssetException' with message 'Could not open create the stream for “VAF_4815.jpg”'

### ISSUE THREAD

**Issue by mufi-siebird** [spacecatninja/craft-imager-x#103]
I am using this Azure blob storage plugin from Pixel & Tonic
https://github.com/craftcms/azure-blob/blob/main/README.md

Issue is, When I try to generate transformations of images from this storage volume, I am getting this error. I tried via command line as well as queue. Note that, I get no such error if I pass FULL remote URL, but get the error again if I pass image objext in imager-x. 

So this code throw error:
```
{% set jpegImages = craft.imagerx.transformImage(image, 'jpg') %}
```
but this code not throw error:
```
{% set jpegImages = craft.imagerx.transformImage(image.getUrl(), 'jpg') %}
```

![image](https://user-images.githubusercontent.com/47181126/120630775-c254da00-c484-11eb-9b0e-fd086569cc8d.png)
![image](https://user-images.githubusercontent.com/47181126/120630814-ce409c00-c484-11eb-916e-e9d60a779869.png)

**Comment by aelvan** [comment]
The error seems to be related to the volume not being able to save the file to the local file system. Imager calls `saveFileLocally`, which is a native method on the Volume, to get a local copy of the asset that it can transform. Either this is a bug in the Azure Volume, or it has something to do with your environment (not write access to Craft's default temp file location or something). What kinda of environment (webserver/filesystem/etc) are you running on?

The fact that it works when passing in the URL, just underscores this. In that case, the asset will be treated as an external file, and Imager will download the file and put it in its own external images cache. So, not using the native functionality for volumes, and not storing it in the same location.
