### ISSUE TITLE
Hi, could you please confirm if imager X processes personal data? If so, what are they and is any personal data processed outside of the EU / EEA? 

### ISSUE THREAD

**Issue by companjon** [spacecatninja/craft-imager-x#104]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. ...
2. ...
3. ...

### Displayed errors, stack trace, relevant logs  

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version & edition:
- Imager transformer:
- Craft version:
- PHP version:
- Image driver & version:
- Database driver & version:
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
No, Imager does not process any personal data, and images are only stored wherever you choose to store them. Ie, if you configure an external storage to store data in a region outside of the EU, it will. But that's entirely up to you.
