### ISSUE TITLE
WebP issues

### ISSUE THREAD

**Issue by palomamtnez** [spacecatninja/craft-imager-x#108]
### I'm submitting a... 

- [x ] bug report
- [ ] general question

- [ ] feature request

### Steps to reproduce

```
                                    {# Create transforms #}
                                    {% set imageSizes = [{  width: 850, height: 480 },{  width: 720, height: 440 },{  width: 340, height: 200 }] %}
                                    {% set image = entry.imageBlock.one() %}

                                    {% set transformedImages = craft.imager.transformImage(image, imageSizes) %}
                                        <picture>
                                            {% if craft.imager.serverSupportsWebp() %}
                                                {% set transformedImagesWebp = craft.imager.transformImage(image, imageSizes, { format: 'webp' }) %}

                                                {% if transformedImagesWebp | length %}
                                                <source sizes="100vw"
                                                        srcset="{{ craft.imager.srcset(transformedImagesWebp) }}"
                                                        type="image/webp">
                                                {% endif %}
                                            {% endif %}
                                            <img sizes="100vw"
                                                 srcset="{{ craft.imager.srcset(transformedImages) }}"
                                                 alt="{{ image.title }}" loading="lazy"
                                                 src="{{ craft.imager.base64Pixel() }}">
                                        </picture>
```

### Description
 

Expected:
Render the webp images only if the server supports webp format _and_ if the files are found 

Actual: 
The <source> markup is shown but the images are not transformed to webp, then it shows a 404 (not found in the server) and the broken image. Doesn't fallback to <img>. 

As soon as I remove the <source> markup is transforming the images are expected. 

This odd behaviour is not present all the time though, it sometimes shows the webp images broken (404) and sometimes it displays them alright, even though we don't change the entry's images. 

### Displayed errors, stack trace, relevant logs  

404 img not found in the server

<img width="179" alt="Screen Shot 2021-07-08 at 3 03 54 PM" src="https://user-images.githubusercontent.com/13962572/124855874-b7e6ac80-dffd-11eb-893a-d4dad9b50a9a.png">

### Additional info

- Imager version & edition:  Lite 

![Screen Shot 2021-07-08 at 3 05 42 PM](https://user-images.githubusercontent.com/13962572/124856035-f8462a80-dffd-11eb-93d6-66868b3d8269.png)

**Comment by aelvan** [comment]
> This odd behaviour is not present all the time though..

Inconsistent behavior is the worst. But let's try to narrow it down.

1) Do you see this behaviour in local dev, or is it in production? Or both/all?

2) Are you using the built-in webp-support in imagick, or have you configured cwebp to do the conversion to webp? Is `imageDriver` explicitly set til `imagick` in `general.php`, or are you using the default (ie `auto`)?

3) Are you using external storages or optimizers?

4) When you get those broken images, can you check if the actual webp file exists in your `imagerSystemPath`? You should be able to figure out the path to the image by inspecting the src for the broken image.

**Comment by palomamtnez** [comment]
Hi @aelvan, yeah inconsistent behaviour is not easy to trace, thank you for your reply

1. Actually this markup was tested on my local env but I didn't notice this issue. It was when I deployed it to the staging site when some users started to notice it. I haven't been able to replicate it by my own which is not helpful.. they sent me those screenshots and reported it. They mentioned that in most of the cases the pictures are rendered as expected (webp), but in some odd situations, the users have those experiences
2. I'm using the built-in webp-support, this is my imager-x file:
```
return [
    'transformer' => "craft",
    'allowUpscale' => false,
    'imagerSystemPath' => '@assetBasePath/_resized/',
    'imagerUrl' => '@assetBaseUrl/_resized/',
    'smartResizeEnabled' => true,
    'instanceReuseEnabled' => true
];
```
3. No
4. I will ask for more details when this issue happens again

I know this is not really helpful. But any ideas of why this might happen?

**Comment by aelvan** [comment]
So, the error went away before you had a chance to see it live? Did you/the user do anything to fix it?

Based on what I know so far, the most likely culprit is that the server timed out during the creation of the transform, and left an invalid image on disk. When the webserver or PHP times out, it's impossible to catch this and take measures to clean up after it. So it's best to avoid this by either [generate transforms in advance](https://imager-x.spacecat.ninja/usage/generate.html), or just increase the necessary settings enough that you avoid this (max_execution_time in PHP, and various settings in nginx if that's what you're using). 

But, it might be something entirely different. The most important thing to figure out would be if the transform that the browser is trying to load, is actually generated in your `imagerSystemPath`. And if it is, try to figure out what's wrong with it. And if not, try to figure out why it didn't get generated/was removed from the file system, and how you still ended up with markup that tries to reference it.
