### ISSUE TITLE
Getting unknown property error after deleting/recreating section

### ISSUE THREAD

**Issue by jwrudzin** [spacecatninja/craft-imager-x#109]
### Description

Deleting a section (and subsequently deleting all of the fields that were attached to that section), then recreating the section using the same name and handle results in a `Getting unknown property` error when trying to save an entry in the newly created section.

This seems to be related specifically to assets fields. When I delete the section then delete a text field that was attached to that section, I can still properly save an entry after recreating the section. However, once I delete an assets field that was attached to the deleted section, I can no longer save a new entry and I get the aforementioned error.

Changing the handle of the newly created section makes the error go away.

### Steps to reproduce

Create a section.
Create an assets field and add it to the newly created section's default entry type.
Delete the section.
Delete the assets field.
Create another new section using the same section name and handle used in step 1.
Attempt to create and save an entry to the new section.
This results in an error `Getting unknown property: craft\elements\Entry::assetFieldHandle`

### Additional info

Craft version: 3.7.4
PHP version: 7.4.4
Database driver & version: MariaDB 10.4.12

[full error text](https://github.com/spacecatninja/craft-imager-x/files/6863274/fullError.txt)
![error screenshot](https://user-images.githubusercontent.com/18213990/126662492-7ee23df7-691a-4705-8b5d-d6c82272096e.jpg)

**Comment by aelvan** [comment]
Thanks for reporting. Just to be clear, you've created an auto generate config for that field?

**Comment by aelvan** [comment]
Tested now, and not able to reproduce. The only time I get this error, is if I'm targeting a non-existing field in my generate config. Are you sure the handle on the field and the configuration is correct?

**Comment by jwrudzin** [comment]
@aelvan Ah yep, that's it! I forgot that my generate config is referencing the field that I removed. Once I removed it from my generate config I'm no longer seeing the issue.

**Comment by aelvan** [comment]
Cool. I've added a fix for the next release that avoid throwing errors for this.
