### ISSUE TITLE
Element API error after updating from Imager

### ISSUE THREAD

**Issue by tinchalamo** [spacecatninja/craft-imager-x#11]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Have an element-api endpoint using `aelvan\imager\Imager`
2. Verify that the endpoint is working
3. Uninstall Imager and install Imager X
4. Rename `imager.php` to `imager-x.php`
5. Replace `use aelvan\imager\Imager` in Element API with `use spacecatninja\imagerx\ImagerX`
6. Verify endpoint again and see error message: _"Domain must be passed in as fully-qualified domain name and should not include a protocol or any path element, i.e. "example.imgix.net"."_

### Description
 
Element API endpoint should continue to work properly, but instead seeing error message.

### Displayed errors, stack trace, relevant logs  

```
{
error: {
code: 0,
message: "Domain must be passed in as fully-qualified domain name and should not include a protocol or any path element, i.e. "example.imgix.net"."
}
}
```
Also, seeing this deprecation error even though I have removed `shardStrategy` from the Element API endpoint:

```
Message: The `shardStrategy` config setting for Imgix has been deprecated and should be removed.

Origin: /Users/roger.tinch/Repos/crafthouse-3.4x/vendor/spacecatninja/imager-x/src/transformers/ImgixTransformer.php:97
```

### Additional info

- Imager version & edition: Imager X Pro 3.0.3
- Imager transformer: Imgix
- Craft version: Craft Pro 3.4.8
- PHP version: 7.2.25
- Image driver & version: GD 7.2.25
- Database driver & version: MySQL 5.6.46
- Plugins & versions (if relevant):

**Comment by jamesmacwhite** [comment]
Do you happen to have something like:

```
'deprecator' => [
     'throwExceptions' => true
]
```

In your `config/app.php` deprecation errors shouldn't cause an exception unless that's enabled, but maybe the Element API handles them differently.

If you have the `domains` key in your imager-x config, it needs to be renamed to `domain` and changed to a string as `example.imgix.net`, if you have `shardStrategy` in your config, you need to remove it completely.

**Comment by aelvan** [comment]
@tinchalamo That first error regarding the domain is coming from the Imgix library. It got updated to v3.0 in Imager X, and it might be that it's more strict regarding how the domain is set up. Can you post your `imgixConfig` here (replace credentials), so I can see what you've set it to?

**Comment by tinchalamo** [comment]
@aelvan sure thing:

```
// Global settings
'*' => [
    'transformer' => 'imgix',
    'useForNativeTransforms' => true,
    'useForCpThumbs' => true,
    'cacheDuration' => 31536000,
    'cacheDurationRemoteFiles' => 31536000,
    'imgixProfile' => 'default',
    'imgixApiKey' => '$IMGIX_API_KEY',
  ],

  // Dev environment settings
  'dev' => [
    'imgixConfig' => [
      'default' => [
        'domain' => ['img-assets-dev.*****.com'],
        'useHttps' => true,
        'signKey' => '',
        'sourceIsWebProxy' => false,
        'useCloudSourcePath' => true,
        'getExternalImageDimensions' => true,
        'defaultParams' => [
          'auto'=> 'compress',
          'q'=>80,
        ],
      ],
    ],
  ],
```

**Comment by aelvan** [comment]
@tinchalamo Yeah, `domain` is suppose to be a string, so change it to:

```
'domain' => 'img-assets-dev.*****.com',
```

**Comment by tinchalamo** [comment]
@tinchalamo updated to this:

```
  // Dev environment settings
  'dev' => [
    'imgixConfig' => [
      'default' => [
        'domain' => 'img-assets-dev.drafthouse.com',
        'useHttps' => true,
        'signKey' => '',
        'sourceIsWebProxy' => false,
        'useCloudSourcePath' => true,
        'getExternalImageDimensions' => true,
        'defaultParams' => [
          'auto'=> 'compress',
          'q'=>80,
        ],
      ],
    ],
  ],
```
I'm still getting the same error message when trying to access the endpoint:
```
{
  error: {
    code: 0,
    message: "Domain must be passed in as fully-qualified domain name and should not include a protocol or any path element, i.e. "example.imgix.net"."
  }
}
```

**Comment by tinchalamo** [comment]
@aelvan if it helps, here's a snippet of how I'm using Imager X in the Element API endpoint:

```
<?php

use craft\elements\Entry;
use craft\helpers\UrlHelper;
use spacecatninja\imagerx\ImagerX;
use League\Fractal\TransformerAbstract;

class ShowsTransformer extends TransformerAbstract {

  public function transform(Entry $entry) {

    //Hero Image
    $landscapeHeroImage = null;
    if ($entry->heroImage) {
      $image = $entry->heroImage[0];
      $transformedImage = ImagerX::$plugin->imager->transformImage($image, [
        'width' => 1920,
        'height' => 1080,
        'mode' => 'crop',
        'position' => $image->getFocalPoint(),
      ]);
      $landscapeHeroImage = array(
        'url' => $image->url,
        'transformed' => $transformedImage->url,
        'title' => $image->title,
        'altText' => $image->altText,
      );
    }

```

**Comment by aelvan** [comment]
Yeah, everything looks fine. It's the [validateDomain method in the Imgix library](https://github.com/imgix/imgix-php/blob/ff013094feb4855c561999f2248f3fafe0a25ec1/src/Imgix/UrlBuilder.php#L33) that fail for some reason. It shouldn't if the value that is passed actually is `img-assets-dev.drafthouse.com`. 

Are you sure that the environment that the element API is running in is `dev`? What happens if you (temporarily) add the `imgixConfig` to `*` instead, and delete any other `imgixConfig` you have in other envs?

**Comment by tinchalamo** [comment]
@aelvan Ah! That's exactly what it was. Local .env has a different env set. The .env file is updated and it's working now.
