### ISSUE TITLE
How to use Blurha.sh with Imager-X?

### ISSUE THREAD

**Issue by D3strukt0r** [spacecatninja/craft-imager-x#110]
### I'm submitting a... 
- [ ] bug report
- [ ] feature request
- [x] general question

### Description

I'm currently trying to figure out how I can implement using [Blurha.sh](https://github.com/woltapp/blurhash) using Imager-X, simply because it says [here](https://imager-x.spacecat.ninja/overview.html#features) "Lots of placeholder options, even the brand new blurhash thingy."

So I read, and read, and found no explanation. The only thing I can find is a small explanation about "placeholders", which didn't get me any further though.

---

#### craft.imager.placeholder([config = null])

Outputs an image placeholder. The config object takes the following parameters:

- type: Type of placeholder. Defaults to 'svg'. Available types are 'svg', 'gif' and 'silhouette'.
- width: Width of the placeholder. Defaults to '1'.
- height: Height of the placeholder. Defaults to '1'.
- color: Color of the placeholder. Defaults to 'transparent'.
- source: Source image that should be used to create silhouette style svgs. Only relevant for silhouette placeholders.
- fgColor: Foreground color for silhouette style svgs. Color is used as background. Only relevant for silhouette placeholders.
- size: Size multiplicator for silhouette style svgs. Only relevant for silhouette placeholders.
- silhouetteType: Type of silhouette, available values are '' and 'curve'. Only relevant for silhouette placeholders.

---

### Additional info

- Imager version & edition: Pro
- Imager transformer: 3.5.1
- Craft version: 3.6.17
- PHP version: 7.4
- Image driver & version:
- Database driver & version:
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Hi,

You can get the blurhash via the [transformed image model](https://imager-x.spacecat.ninja/models.html#crafttransformedimagemodel) itself:

```
{% set transformedImage = craft.imagerx.transformImage(image, { width: 1200, ratio: 16/9 }) %}
{% set blurhash = transformedImage.getBlurhash() %}
```

**Comment by kevinmu17** [comment]
Seems that this doens't work anymore, using craft 4 getting internal server error: getBlurhash does not exists. Can't find it in the repository codebase either so seems it's gone?

**Comment by aelvan** [comment]
@kevinmu17 Tested now, and `getBlurhash` still works both for the craft and imgix transformers. Can you open a new issue and supply more information about your environment, your template code, and the full error message (enable devMode).
