### ISSUE TITLE
Letterbox/fit issue

### ISSUE THREAD

**Issue by mikemeadeuk** [spacecatninja/craft-imager-x#114]
### I'm submitting a... 

- [ x] bug report

### Steps to reproduce

1. Applying these transforms in imager-x-transforms.php
```
return [
	'logo' => [
		'transforms' => [
				['width' => 150],
				['height' => 150],
				['mode' => 'letterbox'],
				'letterbox' => [
				'color' => '#ffffff',
				'opacity' => 1
			]
		]
	]
];
```

### Description
when using an image of say 1000/40px, the output is 150/40px. Expected result is 150/150px.

### Additional info

- Imager version & edition: 3.5.1 PRO
- Imager transformer: craft
- Craft version: 3.7.8 PRO
- PHP version: 8.0.9
- Image driver & version: GD 8.0.9
- Database driver & version: MySQL 5.5.5

**Comment by aelvan** [comment]
You have the syntax a bit wrong there. `transforms` can either be an array of transform objects, or a single transform. Right now you're passing in four transforms, one that's `'width' => 150`, one that's `'height' => 150`, and so on.

If the goal is to make a single transformed image that's letterboxed 150x150, try this instead:

```
return [
    'logo' => [
        'transforms' => [
            'width' => 150,
            'height' => 150,
            'mode' => 'letterbox',
            'letterbox' => [
                'color' => '#ffffff',
                'opacity' => 1
            ]
        ]
    ]
];
```

**Comment by aelvan** [comment]
Did you figure it out?

**Comment by mikemeadeuk** [comment]
Hi,

I havent tested it yet, but I will let you know. thanks for your help.

cheers

mike
