### ISSUE TITLE
Transparent Background? 

### ISSUE THREAD

**Issue by ambidustrious** [spacecatninja/craft-imager-x#115]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
 
Is there a way to make a color transparent... specifically looking to remove background color/white in logos..

I know I can do this in imageMagick... but can't quote figure out how/if it's possible to do this with the plugin.

I.e. -transparent #FFFFFF -fuzz 90%

**Comment by aelvan** [comment]
Not currently possible no, [this FR](https://github.com/spacecatninja/craft-imager-x/issues/100) I made for myself some time back aims to add that functionality.

**Comment by aelvan** [comment]
3.5.2 adds support for Imagick's `transparentPaintImage` and `floodFillPaintImage`, which can both be used to achieve transparent backgrounds, see https://imager-x.spacecat.ninja/effects.html.

The results are ok, but some images can get quite jagged edges, which may be a no-go for some. I'll explore further and see if it's possible to get a better result by maybe compositing the alpha channel on top of the original image. If so, this will be a separate effect.

**Comment by ambidustrious** [comment]
This is great - and will likely work for my needs.  Thank you!
