### ISSUE TITLE
Auto generated field error with Freeform submission

### ISSUE THREAD

**Issue by Moucky** [spacecatninja/craft-imager-x#12]
I discovered an issue with my auto generated transform field, I get the error below when the Freeform plugin generates an entry which stops the rest of submission process. Here is my field setting:

```
	'fields' => [
	   'installationView:item.image' => ['installationView']
	] 
```

Below is part of the error from web.log:

`Error: Call to a member function getFieldByHandle() on null in /var/www/#####/src/vendor/spacecatninja/imager-x/src/helpers/FieldHelpers.php:33`

Do you think it's something I've done wrong or perhaps another problem?

Thanks!

**Comment by aelvan** [comment]
That was me not taking into account that an element might not have a field layout. v3.0.4 should fix that.

Not sure why Freeform would result in that error though. Let me know if things work  out as expected for you!

**Comment by Moucky** [comment]
I'd say that's done it. Can't see the error in the log anymore and the form submissions are completing. Thanks!
