### ISSUE TITLE
Unable to auto generate transformations within a matrix on entry save

### ISSUE THREAD

**Issue by iuscare** [spacecatninja/craft-imager-x#121]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce
As discussed before on discord, I am unable to auto generate transformations for hero images. The hero images do not have a container/full width beside all other images, so I thought these images would be good candidates to use the `elements` object within the `imager-x-generate.php`. You can find the steps I did below:

1. Created a section called `subpages` with two entry types (`home` & `subpage`)
2. Created one Matrix called `headerBuilder` with a Matrix Block `heroBackgroundImage` 
3. Added an `heroImage` field to the block and attached the `headerBuilder` matrix to the `home` entry type.

Current **imager-x-transforms.php**:
```
<?php

$defaultTransforms = [
  ['width' => 200],
  ['width' => 400],
];

return [
  'auto' => [
    'transforms' => $defaultTransforms,
  ],
  'autoWebp' => [
    'transforms' => $defaultTransforms,
    'defaults' => [
      'format' => 'webp'
    ],
  ],
  'heroWide' => [
    'transforms' => [
      ['width' => 2560],
      ['width' => 3600]
    ],
    'defaults' => [
      'ratio' => 16 / 5
    ],
  ],
  'heroWideWebp' => [
    'transforms' => 'heroWide',
    'defaults' => [
      'format' => 'webp'
    ],
  ],
];
```

Current **imager-x-generate.php**
```
<?php

return [
  'volumes' => [
    'images' => ['auto', 'autoWebp'],
  ],

  'elements' => [
    [
      'elementType' => \craft\elements\Entry::class,
      'criteria' => [
        'section' => ['subpages'],
      ],
      'fields' => ['headerBuilder:heroBackgroundImage.image'],
      'transforms' => ['heroWide', 'heroWideWebp']
    ],
  ],
];
````
When using the `fields array`alone outside of the `elements` array (`'fields' => ['heroImage' => ['heroWide', 'heroWideWebp']]`) it does work, so my guess is that I have some misconfiguration in place, but can't see any culprit. As discussed on discord I also tried to specify the matrix block (`headerBuilder:heroBackgroundImage.heroImage`) and also to change the `elementType` to ` \craft\elements\MatrixBlock::class` with its `id` and `type`, both without success.

### Description
The expected behavior would be that imager-x creates the volume based transformations on file upload (this already works) and the transformations within the `elements` array on entry save (does not work). I have to visit the particular site on the frontend for the transformations within the `elements` array to be generated. This is, because on the template side I am fetching the `heroWide` and `heroWideWebp` transformations via twig to output them. But I'd need them to be generated on entry save.

### Displayed errors, stack trace, relevant logs  
No errors are being displayed within the log.

### Additional info

- Imager version & edition: Pro v3.5.2 
- Imager transformer: Default
- Craft version: Craft Pro 3.7.13 Multi Site
- PHP version: 8.0.9
- Image driver & version: Imagick @PACKAGE_VERSION@ (ImageMagick 7.0.11-13)
- Database driver & version: MySQL 5.5.5

**Comment by iuscare** [comment]
Hi @aelvan 

so I looked a little bit further into my issue. The auto generation on entry save does work, when I delete the `criteria` statement within the `imager-x-generate.php`:

**Does work:** 
```
<?php

return [
  'volumes' => [
    'images' => ['auto', 'autoWebp'],
  ],

  'elements' => [
    [
      'elementType' => \craft\elements\Entry::class,
      'fields' => ['headerBuilder:heroBackgroundImage.image'],
      'transforms' => ['heroWide', 'heroWideWebp']
    ],
  ],
];
```

When I put in the `criteria` statement to target the particular section, it does not work anymore. The site is a craft multi site, and the related section is activated on all sites (same template, just different content with different author teams) with Propagation Method set to `Only save entries to the site they were created in`.  The particular entry type template in that section includes a header builder, with the headerBuilder matrix, if that is important. Any ideas why it could stop working when I try to target the section? 

All the best
Pascal

**Comment by aelvan** [comment]
Very sorry for letting this slip from my mind. Turns out there were a silly bug that would prevent the criteria from working for non-primary sites, for certain propagation settings.

**Comment by iuscare** [comment]
@aelvan no worries, very happy to see that it came to your radar again. Will update imager-x and test it over the days and close the issue eventually. Great work! 👏
