### ISSUE TITLE
Feature Request: PDF Thumbnail Generation

### ISSUE THREAD

**Issue by adrienne** [spacecatninja/craft-imager-x#123]
This is definitely possible using ImageMagick and GhostScript, and I'm wondering if it could be bundled into ImagerX as kind of a one-stop-shop thing? This plugin (old, not really maintained) does it as a standalone: https://github.com/jmoont/pdfthumb but it doesn't seem to cache or do any of the other cool things ImagerX does.

**Comment by chadcrowell** [comment]
PLEASE PLEASE PLEASE that old plugin doesn't work anymore I don't think. Hi Adrienne!!

**Comment by aelvan** [comment]
Unfortunately this never made it into Imager X for Craft 3. But with the introduction of [file adapters](https://imager-x.spacecat.ninja/extending.html#file-adapters) and the first party [PDF adapter](https://plugins.craftcms.com/imager-x-pdf-adapter), this can now be done for Craft 4.
