### ISSUE TITLE
override Imgix defaults now results in an error - strpos() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by terryupton** [spacecatninja/craft-imager-x#127]
### I'm submitting a... 

- [x ] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
Since updating to the latest version, I am now having issues as follows:
<img width="1342" alt="Screenshot 2021-11-29 at 19 22 41" src="https://user-images.githubusercontent.com/5698596/143929595-ea4a8e33-d06e-4a0f-a8a4-2707b366f150.png">

`strpos() expects parameter 1 to be string, array given`

I believe this is down to this code and perhaps relates to our previous conversation and the update in https://github.com/spacecatninja/craft-imager-x/blob/master/CHANGELOG.md#353---2021-10-20

```
'auto'  => static function ($image) {
        if ($image instanceof \craft\elements\Asset) {
          if ($image->extension === 'png') {
            return ['compress,format', 'q' => 80];
          }
        }
        return ['compress,format,enhance', 'q' => 80];
      }
```

Full Code:
```
  '8x5Image' => [
    'displayName'     => 'Article Image',
    'transforms'      => [
      ['width' => 400],
      ['width' => 2000],
    ],
    'defaults'        => [
      'ratio' => 8 / 5,
      'auto'  => static function ($image) {
        if ($image instanceof \craft\elements\Asset) {
          if ($image->extension === 'png') {
            return ['compress,format', 'q' => 80];
          }
        }
        return ['compress,format,enhance', 'q' => 80];
      }
    ],
    'configOverrides' => [
      'fillTransforms' => true,
      'fillInterval'   => 200,
    ],
  ],
```

Could you offer an insight into how I need to resolve this or if there is a better way to achieve this now?

**Comment by terryupton** [comment]
It might be as simple as this:
```
    'defaults'        => [
      'ratio' => 8 / 5,
      'auto'  => static function ($image) {
        if ($image instanceof \craft\elements\Asset) {
          if ($image->extension === 'png') {
            return 'compress,format';
          }
        }
        return 'compress,format,enhance';
      }
    ],
  ```
  
  Removing the array and the q => param but I wanted to check this was in fact correct?

**Comment by aelvan** [comment]
Not quite, the top level setting you should override is `imgixParams`, which is an array of params, where `auto` could be one of them. So, something like:

```
'defaults'        => [
      'ratio' => 8 / 5,
      'imgixParams'  => static function ($image) {
        if ($image instanceof \craft\elements\Asset) {
          if ($image->extension === 'png') {
            return ['auto' => 'compress,format', 'q' => 80];
          }
        }
        return ['auto' => 'compress,format,enhance', 'q' => 80];
      }
```
