### ISSUE TITLE
CP Images with Imgix when we have more than one source

### ISSUE THREAD

**Issue by jhubb-io** [spacecatninja/craft-imager-x#129]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [X] general question

### Steps to reproduce

1. Have more than one volume in Craft each from a different source
2. Set imagerUrl to one source
3. Set useForCpThumbs true

### Description
 

We have two Craft volumes set up using different S3 buckets each with it's own Imgix source. When we set imagerUrl to one of the sources and useForCpThumbs true we of course only see thumbnails for one volume and not the other. Is there a way to set imagerUrl separately for each volume. If not, is it safe to set up a third Imgix source at www.domain.com → cp.domain.com and set the imagerUrl to this source. Since we're using Imgix for all transforms I assume that in this case the only place imagerUrl is being used in on the CP?

**Comment by aelvan** [comment]
Hi,

The `imagerUrl` isn't really used when using Imgix, the Imgix profile determines what the resulting URL will be. And the CP transforms will only use the default Imgix profile.

Unfortunately, with your current setup, I don't think there's currently a solution for this. There is functionality that solves a very similar case though. If you had multiple volumes _on the same bucket_, and used paths to separate them, you could simply set up one Imgix source that pointed to the root of the bucket, and set `useCloudSourcePath` in your [`imgixConfig`](https://imager-x.spacecat.ninja/configuration.html#imgixconfig-array) to `true`. The resulting URl would then be <domain from imgixConfig/<path from volume>/<path to image inside volume>, which would work for all sources on that bucket.

Any chance you could restructure the assets? :)
