### ISSUE TITLE
craft.imager.clientSupports('webp') returns false in Safari 14+ (Big Sur or newer)

### ISSUE THREAD

**Issue by vonscriptor** [spacecatninja/craft-imager-x#131]
### I'm submitting a... 
- [x] bug report

### Steps to reproduce
1. Output `{{ craft.imager.clientSupports('webp') }}`
2. Check in Safari 14+ (Big Sur or newer)
3. Returns false ''

### Description
WebP is supported in Safari 14+ (Big Sur or newer), but `{{ craft.imager.clientSupports('webp') }}` returns false when I test specifically in Safari 15.1—I don't have access to Safari 14 to confirm there as well.

https://developer.apple.com/documentation/safari-release-notes/safari-14-release-notes

### Additional info

- Imager version & edition: v3.5.5
- Imager transformer: craft
- Craft version: Craft Solo 3.7.28
- PHP version: 7.4.27
- Image driver & version: Imagick 3.6.0 (ImageMagick 6.9.7-4)
- Database driver & version: MySQL 5.5.5

**Comment by aelvan** [comment]
Can confirm. It looks like Safari doesn't send accept headers indicating what formats it accepts, unless the request is to an image-sounding URL (ie, it has an extension that indicates that it's an image). This makes it impossible to reliably detect server side if the client supports it or not. 

Still looks like Safari work with `<picture>` and `type`, so I guess that's the way they expect modern image formats to be served.
 
```
<picture>
    <source src="..." type="image/webp">
    <img src="...">
</picture>    
```

It would also be possible to parse the browser UA string, and _assume_ WebP support based on that, but it's a fragile and not very future proof solution, so I won't build that into Imager. But it could easily be in a seperate plugin or module.

**Comment by aelvan** [comment]
If you want to go down the latter route, there is already [a plugin in the plugin store](https://plugins.craftcms.com/agent) that you can leverage.

**Comment by vonscriptor** [comment]
Thanks for looking into this @aelvan. That makes sense. Using the browser UA string to determine support is an interesting idea!

I'm currently using JavaScript to create a WebP image and see if it loads to verify support.

```
testWebP() {
    return new Promise(res => {
        const webP = new Image();
        webP.src = 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA';
        webP.onload = webP.onerror = () => {
            res(webP.height === 2);
        };        
        });
}

testWebP().then(hasWebP => {
    if (hasWebP) {
        // Supported
    } else {
        // Not supported
    }
});
```

_A sample of code from: https://stackoverflow.com/questions/5573096/detecting-webp-support_

The reason I need this is that I want to lazy load with [HTMLImageElement.decode()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode) for performance reasons. So I need to manually test for WebP support and grab that specific `<picture>` `<source>` as the browser can't provide that for me in this case. i'm also able to use this to add a class to the body to manage WebP support in CSS styles.

For most use cases this is a non-issue for people and native `<picture>` and `type` is all you'd need, or using something like [lazysizes](https://github.com/aFarkas/lazysizes). Eventually, with more browser support / version releases we can ignore older browsers and use WebP freely.

Thanks for your quick reply and all of your work on Imager X—it is very useful in my projects!
