### ISSUE TITLE
Feature: Limit the number of images transformed in the auto generate config

### ISSUE THREAD

**Issue by alexroper** [spacecatninja/craft-imager-x#134]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description

I have an assets field that holds multiple images. On the front-end of the site, we only generate thumbnail images for the first 6. It would be great if we could limit the images targeted by auto generated transforms to the first 6. Something like this:

**imager-x-generate.php**

```
<?php

return [
    'elements' => [
        [
            'elementType' =>  \craft\elements\Entry::class,
            'criteria' => [
                'section' => ['rentals'],
            ],
            'fields' => ['images'],
            'limit' => 6,
            'transforms' => ['thumb'],
        ],
    ],
];
```

**Comment by aelvan** [comment]
Nice one, will add.

**Comment by aelvan** [comment]
Added in 3.5.6.

**Comment by alexroper** [comment]
Thanks! Just tried this out and it works great.

I am running into a weird problem though. If I have a 'fields' transform that won't run if the the same field is used in the 'elements' transform config:

 ```
<?php

return [
    'fields' => [
        'images' => [
            'galleryImage',
        ],
    ],
    'elements' => [
        [
            'elementType' =>  \craft\elements\Entry::class,
            'criteria' => [
                'section' => ['rentals'],
            ],
            'fields' => ['images'],
            'limit' => 6,
            'transforms' => ['thumb'],
        ],
    ],
];
```

In that example above, the `thumb` transform runs but `galleryImage` won't. If I comment out the 'elements' part of the config the `galleryImage` transform runs again.

I assume it's because there's an overlap with the 'images' field. Is this a known limitation or bug?

**Comment by aelvan** [comment]
That should work, let me test and get back to you.

**Comment by aelvan** [comment]
Can you try again with the patch release I just pushed. That limit setting introduced a bug which messed with other transforms on the same field (and potentially other plugins interacting with it).

Apart from that bug, which maybe isn't 100% what you describes here, I've tested and have no issues setting up different transforms for the same field.

**Comment by alexroper** [comment]
Great! I just tried it out and it looks like everything is working now. 

Thanks so much. 👏
