### ISSUE TITLE
custom encoder path is missing or invalid

### ISSUE THREAD

**Issue by webtrend** [spacecatninja/craft-imager-x#135]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x ] general question

### Steps to reproduce

1. ...
2. ...
3. ...

### Description
I upgraded craft from 3.4 to 3.7 and also downloaded the latest imager-x version. 

### Displayed errors, stack trace, relevant logs  
After the upgrade, I see following errors when **devMode is true** in general.php

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```
spacecatninja\imagerx\exceptions\ImagerException: Custom encoder path is missing or invalid. in /<craftfolder>/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php:479

Stack trace:
### Additional info

- Imager version & edition:3.5.6.1
- Imager transformer:
- Craft version:3.7
- PHP version:7.4
- Image driver & version:
- Database driver & version:
- Plugins & versions (if relevant):

Can you tell me what encoder am I missing here. The error dump has a lot of details but not sure what the root cause is and where should I look for it?

**Comment by aelvan** [comment]
Sounds like you have set up a custom encoder, or maybe configured webp support using cwebp, and the path given doesn't exist? Could you share your config (redact any sensitive data)?

**Comment by aelvan** [comment]
@webtrend Did you figure this one out?
