### ISSUE TITLE
Add PHP examples to documentation

### ISSUE THREAD

**Issue by clarknelson** [spacecatninja/craft-imager-x#14]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
 

Currently the documentation is amazing! But I would like to see some examples of how to use the plugin in PHP. It's common to generate the images in an element API configuration for example.

**Comment by aelvan** [comment]
Great feedback, I'll make sure to add some documentation on that.

**Comment by aelvan** [comment]
I've added a page in the docs: https://imager-x.spacecat.ninja/usage/php.html

Let me know if there's something you think I should elaborate on.

**Comment by clarknelson** [comment]
Oh wow, very informative thank you so much. This will save my ass down the road.
