### ISSUE TITLE
Imager-X not overriding "quality" options at runtime if set as default

### ISSUE THREAD

**Issue by naboo** [spacecatninja/craft-imager-x#144]
### I'm submitting a... 
- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
Add default option to Imager-X config and try to change one of the quality options at runtime.

### Description
When defining the default quality option in the config file...
```
'defaultParams' => [
       'auto' => 'compress,format', 
       'q' => 80
],
```
... it doesn't seem like you are able to change this at runtime.

### Additional info

- Imager version & edition: v3.5.5
- Imager transformer: Imgix
- Craft version: Craft CMS 3.7.30.1

**Comment by aelvan** [comment]
If you use `q` in your `defaultParams`, you need to overwrite it using `q` in your transforms as well. This is the intended behaviour, there're to many different options to resolve, so something had to give.

So preferably do: 

```
{% set transform = craft.imagerx.transformImage(s3Image, { width: 600, transformerParams: { q: 50 } }) %}
```

At the moment you can actually also do:

```
{% set transform = craft.imagerx.transformImage(s3Image, { width: 600, q: 50 }) %}
```

But I've been thinking of making the transform parameters thingy a bit stricter, so the first one is safer long term.
