### ISSUE TITLE
Skip already transformed Images

### ISSUE THREAD

**Issue by bmilagre** [spacecatninja/craft-imager-x#146]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [X] general question

### Description
 
I am currently trying to program a queued job, which will save all images in the desired transformers as a URL in a JSON file. Now I would like to skip the already created ones. Is there any way I can check if they already exist? Unfortunately I didn't find anything in the docs and the source code that could help me.

**Comment by aelvan** [comment]
Not sure if I follow in regards to `...save all images in the desired transformers as a URL in a JSON file`. But if you're just using Imager's `transformImage` method directly, the normal caching will still come into play. So if a transform already exists, it will not be recreated as long as `cacheEnabled` is `true`. Other than that, no there's not a way to figure out if a transform already exists for a given asset and transform. 

Did that clear things up?

**Comment by bmilagre** [comment]
Hi

Thanks for the clarification. It looks much better with the cacheEnabled parameter now.
