### ISSUE TITLE
Thoughts on .webp and .svg

### ISSUE THREAD

**Issue by clarknelson** [spacecatninja/craft-imager-x#15]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Attempt to transform a SVG or WEBP file.

### Description
 

It says defensive coding, but I frequently have SVG files with my jpgs and pngs. Maybe we should skip files that can't be transformed? What are your thoughts on this? Thanks

### Displayed errors, stack trace, relevant logs  

```
Exception 'Imagine\Exception\RuntimeException' with message 'Unable to open image /Users/clark/Documents/portfolio/dev/web/assets/skill-logos/metafizzy.svg'

Stack trace:
#0 /Users/clark/Documents/portfolio/dev/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(206): Imagine\Gd\Imagine->open('/Users/clark/Do...')
#1 /Users/clark/Documents/portfolio/dev/vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php(96): spacecatninja\imagerx\transformers\CraftTransformer->getTransformedImage(Object(spacecatninja\imagerx\models\LocalSourceImageModel), Array)
#2 /Users/clark/Documents/portfolio/dev/vendor/spacecatninja/imager-x/src/services/ImagerService.php(418): spacecatninja\imagerx\transformers\CraftTransformer->transform(Object(craft\elements\Asset), Array)
#3 /Users/clark/Documents/portfolio/dev/vendor/spacecatninja/imager-x/src/services/GenerateService.php(247): spacecatninja\imagerx\services\ImagerService->transformImage(Object(craft\elements\Asset), Array, Array, Array)
#4 /Users/clark/Documents/portfolio/dev/vendor/spacecatninja/imager-x/src/console/controllers/GenerateController.php(193): spacecatninja\imagerx\services\GenerateService->generateTransformsForAsset(Object(craft\elements\Asset), Array)
#5 [internal function]: spacecatninja\imagerx\console\controllers\GenerateController->actionIndex()
#6 /Users/clark/Documents/portfolio/dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /Users/clark/Documents/portfolio/dev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /Users/clark/Documents/portfolio/dev/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('', Array)
#9 /Users/clark/Documents/portfolio/dev/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#10 /Users/clark/Documents/portfolio/dev/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('imager-x/genera...', Array)
#11 /Users/clark/Documents/portfolio/dev/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('imager-x/genera...', Array)
#12 /Users/clark/Documents/portfolio/dev/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('imager-x/genera...', Array)
#13 /Users/clark/Documents/portfolio/dev/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 /Users/clark/Documents/portfolio/dev/craft(22): yii\base\Application->run()
#15 {main}
```

### Additional info

- Imager version & edition: v3.0.5
- Imager transformer: ?
- Craft version: 3.4.10
- PHP version: 7.4.3
- Image driver & version: GD 7.4.3 
- Database driver & version: MySQL 5.7.29
- Plugins & versions (if relevant): Don't think so

**Comment by aelvan** [comment]
Can you fill out the details about your environment. 

Does this heppen during auto generation?

**Comment by clarknelson** [comment]
Okay i've updated with the ENV details. Maybe it is a problem with the drivers?

It happens when I run `./craft imager-x/generate -v=general -t=default`

Here is my named transform:

``` php
<?php
use spacecatninja\imagerx\services\ImagerService;

return [
  'default' => [
    'transforms' => [
      ['width' => 3000],
      ['width' => 500],
    ],
    'defaults' => [
      'position' => static function ($image) {
        return $image->getFocalPoint();
      },
      'format' => static function ($image) {
        if (ImagerService::hasSupportForWebP()) {
          return 'webp';
        } else {
          return 'jpeg';
        }
      },
      'jpegQuality' => 80
    ],
    'configOverrides' => [
      'fillTransforms' => true,
      'fillInterval' => 250,
    ],
  ],
];
```

**Comment by clarknelson** [comment]
As far as I know, the old plugin also had an error with SVG. Should we prevent this from happening somehow? Better yet, should we integrate svgo or other svg optimization?

**Comment by aelvan** [comment]
Thanks for the details. Yes, I need to implement some kind of restrictions on which file types are being processed. In some cases SVG and WEBP could be possible to transform with Imagick, but GD does not support it. 

I'll try to have a go at it asap, but I'm a bit short on time these days due to the whole corona-thingy (kindergardens being closed, etc).

**Comment by clarknelson** [comment]
Understood, it's the opposite for me I get an extra hour or so I day I would have spent commuting. This isn't a rush thing but would be a great improvement. There is a Twig svg() function that will inline the svg code, maybe this is an option?

**Comment by aelvan** [comment]
I've just release v3.0.6 which adresses this issue by adding a `safeFileFormats` config setting which will be used to determine which types of image formats to process. By default, it's set to `['jpg', 'jpeg', 'gif', 'png']`. If your image driver/transformer supports other file formats, they can be added.

Transforming SVGs (as SVGs) is not something it's likely I'll build into Imager. Transforming and optimizing vector graphics is totally different from transforming bitmap images, so it should rather just be a separate plugin. 

I've been toying with the idea of adding support for rasterising SVG's automatically in Imager though (outputting them as png/gif), might have a look at that at some point.

**Comment by clarknelson** [comment]
thank you so much!

**Comment by MatthiasGrandl** [comment]
@aelvan I still get this error when querying with GraphQL. I have set the saveFileFormats to exclude svg, but apparently this option is ignored with GraphQL?

**Comment by aelvan** [comment]
@MatthiasGrandl Can you post the error message you're seeing, and a (reduced) example of the GQL that produces it.

**Comment by MatthiasGrandl** [comment]
Error: ```
{
      debugMessage: 'Unable to open image /redacted/xxx.svg',
      message: 'Internal server error',
      category: 'internal',
      locations: [Array],
      path: [Array]
    },
```

GQL: ```
image {
        url
        title
        extension
        width
        height
        dataUri: url @imagerTransform (width: 10, format: "gif", return: "dataUri")
        srcset: url @imagerSrcset (handle:"content")
        ... on uploads_Asset {
          alt
        }
      }
```

**Comment by MatthiasGrandl** [comment]
Interestingly on my dev environment, I get a different error with SVGs:
```
{
      debugMessage: 'Save operation failed',
      message: 'Internal server error',
      category: 'internal',
      locations: [Array],
      path: [Array]
    },
```

**Comment by aelvan** [comment]
Ok, Let me have a look. 

Regarding differences between prod and dev, that could be due to different image drivers and/or versions. Are you using GD or Imagick?

**Comment by MatthiasGrandl** [comment]
Imagick on both prod and dev.On Jun 2, 2020 09:55, André Elvan <notifications@github.com> wrote:
Ok, Let me have a look.
Regarding differences between prod and dev, that could be due to different image drivers and/or versions. Are you using GD or Imagick?

**Comment by aelvan** [comment]
I've made the GQL directives and query also use the `safeFileFormats` config setting in v3.0.10 which is out now. 

To be clear, the setting was never intended to be an universal "skip these types of files"-thingy, it'll only be used in scenarios where it's not easy to check the file type before trying to do a transform. But GQL appears to be one of those scenarios.
