### ISSUE TITLE
Is there a way to return an image URL for specific transformation via custom PHP API.? 

### ISSUE THREAD

**Issue by amici-infotech** [spacecatninja/craft-imager-x#152]
Hey,

Basically, We are creating an custom core PHP api that interects with craft cms database. What we can do is to query entry and get assets id, filenames etc. But I am not able to get imager transformations like that. My images that saves in entries might be very big some times so it would be helpful if there is some way to get imager transform via image url or image file name or ID.

**Comment by aelvan** [comment]
Hi, sorry for the late reply. 

I'm not 100% sure if I understand what you're trying to achieve. There is a page in the documentation on how to access Imager from PHP, see https://imager-x.spacecat.ninja/usage/php.html. You can pass in either a URL or an Asset directly. If you have the ID of an asset, you need to do an element query to get the Asset model, but that should be simple enough.

If that page doesn't help, let me know where things stop, and I'll try to help!
