### ISSUE TITLE
Bug with Formie

### ISSUE THREAD

**Issue by Mathias-Syversen** [spacecatninja/craft-imager-x#153]
Imager listens for when elements are saved, formie forms are elements, but does not have the same field layout as categories / entries.

This causes an error when saving formie forms:
`Unable to save form “TestForm”: spacecatninja\imagerx\helpers\FieldHelpers::getFieldInFieldLayoutByHandle(): Argument #2 ($layout) must be of type craft\models\FieldLayout, null given, called in spacecatninja/imager-x/src/services/GenerateService.php on line 204`

From what I can see, $element in this function is of type object(verbb\formie\elements\Form) instead of object(craft\elements\Entry or Category). Checking if the element is an entry or category before proceeding might fix this issue.

Craft cms: 4.0.4
Formie: 2.0.0-beta.13
Imager x: 4.0.1

**Comment by aelvan** [comment]
Thanks for reporting, should be fixed in 4.0.2 / 3.6.1.
