### ISSUE TITLE
Enable/Disable custom encoders per environment?

### ISSUE THREAD

**Issue by benjaminkohl** [spacecatninja/craft-imager-x#154]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
Is there a way to enable/disable particular custom encoders on an individual basis? I remember the config file options changed at some point and we occasionally want to disable cwebp locally. I think there used to be a boolean toggle to do this but can't find something similar now.

### Additional info

- Imager version & edition: 4.0.0 LITE
- Imager transformer: 
- Craft version: 4.0.3
- PHP version: 8.0.8
- Image driver & version: Imagick @PACKAGE_VERSION@ (ImageMagick 6.9.6-2) (not sure why it looks like that in Craft)

**Comment by aelvan** [comment]
Well, with the new `customEncoders` setting, you'll have to define the whole setting for the different environments. Admittedly, that was maybe a bit simpler with the old system where you could toggle only `useCwebp`, and keep the rest of the settings. But it didn't scale well for different formats, hence the new system.

So, depending on whether or not you use the new Craft best-practice config setup which relies heavily on env-variables, or the old one which had top level keys for environment, you'd do something like:

```
return [
    'customEncoders' => App::env('ENVIRONMENT') === 'production' ? [
        'webp' => [
            'path' => '/usr/local/bin/cwebp',
            'options' => [
                'quality' => 80,
                'effort' => 4,
            ],
            'paramsString' => '-q {quality} -m {effort} {src} -o {dest}'
        ],
    ] : []
];
```

Or:

```
return [
    '*' => [
        'customEncoders' => [
            'webp' => [
                'path' => '/usr/local/bin/cwebp',
                'options' => [
                    'quality' => 80,
                    'effort' => 4,
                ],
                'paramsString' => '-q {quality} -m {effort} {src} -o {dest}'
            ],
        ]
    ],
    'local' => [
        'customEncoders' => []
    ],
];
```

Whether or not it's easier to enable only for some environments, or disable for some, is of course dependant on your actual use-case (the two examples use different logic, that's just for readability).

Was that helpful? :)

**Comment by benjaminkohl** [comment]
Yes, thank you. Option 1 was what we were considering doing but we just figured we'd double-check with you.
