### ISSUE TITLE
FR: Trigger event before image transform

### ISSUE THREAD

**Issue by yoannisj** [spacecatninja/craft-imager-x#155]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
 
Craft's built-in image transforming exposes the `EVENT_BEFORE_GENERATE_TRANSFORM`, `EVENT_DEFINE_URL` and `EVENT_DEFINE_THUMB_URL` events which all allow developers to a) override the resulting asset URL before it is sent to the front-end, or b) cancel the image transform.

I am working on a Craft plugin which relies on these events and we would like to support Imager-X as well –seen that it is used by so many , including us. I believe support for Imager-X does makes sense for most use-cases that call for the built-in events above, and therefore would like to suggest triggering an event inside `ImagerService::transformImage()` which also allows overriding the resulting TransformedImage(s) or cancel the image transform(s) before invoking the imager-x transformer.

**Comment by yoannisj** [comment]
@aelvan sure! It's a plugin to set expiry dates on craft assets assets. It was requested by one of your clients which has to deal with licensing issues. The plugin supports multiple *expiry methods*, so it has to tackle into transforms:

1. delete the asset element from craft after expiry date
2. show fallback image (achieved by deleting transformed images and return transformed fallback image after expiry date)
3. show fallback image for social media only (achieved by transforming fallback image for some transforms only)
4. don't show image (keep in the CP)

the 1st method does not require the before transform event.

Technically the 2nd method could also be achieved by allowing modules/plugins to override Imager-X's `mockImage` config setting for specific transforms instead of overriding the returned TransformedImage(s). Looking at the Imager-X source-code tells me this is currently not possible however, and it would also require adding an event.

Making it possible to provide an alternative set of TransformedImage(s) via the event is how we implemented it for Craft's built-int transforms, and it allows us to add support for the 2nd, 3rd and 4th method with Imager-X.

**Comment by aelvan** [comment]
This has been merged into 4.1.1, thanks for contributing!
