### ISSUE TITLE
Failed parsing 'srcset' attribute value since its 'w' descriptor is invalid

### ISSUE THREAD

**Issue by kevinmu17** [spacecatninja/craft-imager-x#157]
### I'm submitting a... 
- [x] bug report

### Steps to reproduce
1. Add transform with AVIF
```html
{% set image = 'https://source.unsplash.com/random/1200x1200?hiking' %}
{% set imageSizes = [ { width: 600, height: 600 } ] %}
{% set transformedJpeg = craft.imagerx.transformImage(image, imageSizes, { jpegQuality: 85 }) %}
{% set transformedWebp = craft.imagerx.transformImage(image, imageSizes, { format: 'webp', webpQuality: 85 }) %}
{% set transformedAvif = craft.imagerx.transformImage(image, imageSizes, { format: 'avif', avifQuality: 40 }) %}
    <picture>
        <source srcset="{{ transformedAvif|srcset }}" type="image/avif">
        <source srcset="{{ transformedWebp|srcset }}" type="image/webp">
        <img srcset="{{ transformedJpeg|srcset }}" src="{{ transformedJpeg[0].url }}">
    </picture>
```

### Description
the value has to be the width of the imageSizes. so image.avif 600w. The actual value is 0w which is not valid.
<img width="843" alt="Screenshot 2022-07-08 at 16 14 50" src="https://user-images.githubusercontent.com/8747373/178009874-e6d7ff9d-c648-4fb5-a2b6-3b129d7b9ac4.png">

### Displayed errors, stack trace, relevant logs  
```
Failed parsing 'srcset' attribute value since its 'w' descriptor is invalid.
Dropped srcset candidate "/imager/source_unsplash_com/random/1200x1200_4c00d9e9e7b809fb059e6473a4e5043a.avif"
```

### Additional info
- Imager version & edition: Imager X lite 4.1.1
- Imager transformer: ?
- Craft version: Craft Pro 4.1.3
- PHP version: 8.1.6
- Image driver & version: Imagick 3.6.0 (ImageMagick 6.9.11-60)

**Comment by aelvan** [comment]
Thanks for reporting, it seems like `getimagesize()` doesn't (always?) support avif-files. I've implementet a fix (in 4.1.2/3.6.2) that uses the source image and the transform to calculate width and height of the resulting transform, if this happens.
