### ISSUE TITLE
Can Imager X be used to generate custom (hashed) output paths?

### ISSUE THREAD

**Issue by cballenar** [spacecatninja/craft-imager-x#159]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
Is it possible to use ImagerX (I'm thinking its [File Adapters](https://imager-x.spacecat.ninja/extending.html#file-adapters)) to transform an image so that its transformed path is different from its source path?

I'm interested in generating obfuscated/hashed URLs of images stored in GCS in order to prevent any crawling to mass download a series of images in their original state (which is fairly easy to guess). If the original image is located in `/2000/01/01/001.jpg` maybe the new location can be `/b23bd9873y7/nx731/001.jpg`. The obscured path would be automatically generated by the File Adapter.

Let me know if you think this is possible (or any additional feedback).

Thank you! Have a great day!

**Comment by aelvan** [comment]
Hi,

File adapters doesn't really help here, it has more to do with the input than the output. But there're a couple of config settings you can use to achieve this, if I understand what you're after. [`filenamePattern`](https://imager-x.spacecat.ninja/configuration.html#filenamepattern-string) can be used to hash both the basename and the transform string, which will obfuscate the filename. If that's not enough, you can also use [`hashPath`](https://imager-x.spacecat.ninja/configuration.html#hashpath-bool), which I guess is exactly what you're looking for? 

Let me know if that was helpful.

**Comment by cballenar** [comment]
This is huge! Yeah, I think that's exactly what we're looking for.

We'll review to confirm. Thank you very much!

(We can close this issue for now.)
