### ISSUE TITLE
Error when trying to replace Imager with Imager X

### ISSUE THREAD

**Issue by helleholmsen** [spacecatninja/craft-imager-x#16]
Hi! I've deleted Imager and I'm now trying to install Imager X with `composer require spacecatninja/imager-x`. It gives me the following errors: 

```
  Problem 1
    - Conclusion: don't install spacecatninja/imager-x v3.0.5
    - Conclusion: don't install spacecatninja/imager-x v3.0.4
    - Conclusion: don't install spacecatninja/imager-x v3.0.3
    - Conclusion: don't install spacecatninja/imager-x v3.0.2
    - Conclusion: don't install spacecatninja/imager-x v3.0.1
    - Conclusion: remove imgix/imgix-php 2.3.0
    - Installation request for spacecatninja/imager-x ^3.0 -> satisfiable by spacecatninja/imager-x[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5].
    - Conclusion: don't install imgix/imgix-php 2.3.0
    - spacecatninja/imager-x v3.0.0 requires imgix/imgix-php ^3.0 -> satisfiable by imgix/imgix-php[3.0.0, 3.1.0].
    - Can only install one of: imgix/imgix-php[3.0.0, 2.3.0].
    - Can only install one of: imgix/imgix-php[3.1.0, 2.3.0].
    - Installation request for imgix/imgix-php (locked at 2.3.0) -> satisfiable by imgix/imgix-php[2.3.0].
```

Help? :grimacing:

**Comment by aelvan** [comment]
Hi,

How did you remove the old Imager plugin? Make sure that it is removed from your composer.json file, and that there's no reference to `aelvan/imager` or `imgix/imgix-php` in there.

**Comment by helleholmsen** [comment]
That was it! Thank you:)

**Comment by KatieMFritz** [comment]
In case anyone else is running into this even with no references to imager or imgix in `composer.json`, here's what I did:

- delete `composer.lock`
- delete `vendor/`
- run `composer update --lock`

Then I could do `composer require spacecatninja/imager-x` and `./craft install/plugin imager-x`.
