### ISSUE TITLE
Fs transformSubpath causes url generation issues

### ISSUE THREAD

**Issue by mizziness** [spacecatninja/craft-imager-x#161]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
1. Create a FileSystem with handle siteImages that points to volume siteImages which is an S3 bucket
2. Set Fs transformSubpath to relative path 'imager/site-images'
3. Attempt to load any asset with transforms

### Description
I expect the URL to look like: `<bucket url>/imager/site-images/<id>`
Instead, it tries to load: `<bucket url>/imager//siteimages/813701`

### Displayed errors, stack trace, relevant logs  
```
[web.ERROR] [spacecatninja\imagerx\transformers\CraftTransformer::getTransformedImage] Target folder “https://bucketeer-5bc3db0c-7cba-4693-96f4-f201c5865122.s3.amazonaws.com/public/imager//siteimages/813701” does not exist and could not be created
```

This issue also persists if I try to force the transformation url to absolute with `https://bucketeer-5bc3db0c-7cba-4693-96f4-f201c5865122.s3.amazonaws.com/public/imager/site-images` but the error still shows it's looking for `public/imager//siteimages/813701`

### Additional info

- Imager version & edition: 4.1.2
- Imager transformer: craft
- Craft version: Craft CMS 4.1.4.1 Pro
- PHP version: 8.1.8
- Image driver & version: Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by aelvan** [comment]
Hi,

Imager does not use transform filesystems in Craft. Where to store transforms are defined in the imager-x.php config file. Have you set up a storage as shown in https://imager-x.spacecat.ninja/configuration.html#storageconfig-array ? If so, can you please attach it (with anything sensitive redacted) and I'll have a look.

**Comment by mizziness** [comment]
Yup!

```
'storages' => ['aws'],
  
  'storageConfig' => [
    'aws'  => [
        'accessKey' => getenv('BUCKETEER_AWS_ACCESS_KEY_ID'),
        'secretAccessKey' => getenv('BUCKETEER_AWS_SECRET_ACCESS_KEY'),
        'region' => getenv('BUCKETEER_AWS_REGION'),
        'bucket' => getenv('BUCKETEER_BUCKET_NAME'),
        'folder' => "public/imager",
        'storageType' => 'standard',
        'public' => true
    ],
  ],
```

**Comment by aelvan** [comment]
Thanks. Not immediately able to reproduce the bug. And the error message doesn't really make sense..

What's you `imagerSystemPath` and `imagerUrl` set to?

Can you provide a minimal example of the template code that produces this? What are you passing in to the `transformImage` method?

**Comment by mizziness** [comment]
Yup x 2! 

```
  'imagerSystemPath' => 'https://bucketeer-5bc3db0c-7cba-4693-96f4-f201c5865122.s3.amazonaws.com/public/imager',
  'imagerUrl' => 'https://bucketeer-5bc3db0c-7cba-4693-96f4-f201c5865122.s3.amazonaws.com/public/imager',
```
  
And then in the template code after fetching a single image as `image`:

```
{% set transformedImage = craft.imager.transformImage(image, 
      [{ width: 500 }, { width: 1800 }], 
      { ratio: 3/2, format: 'png' }, 
      { fillTransforms: true }) 
%}

  <img 
    src="{{- craft.imager.base64Pixel(image.width, image.height) -}}"
    srcset="{{- craft.imager.placeholder({ width: image.width, height: image.height }) -}}"
    data-srcset="{{- transformedImage | srcset -}}"
    type="{{- transformedImage[0].mimeType | default('image/' ~ format) -}}"
    alt="{{- alt -}}"
    title="{{- alt -}}"
    class="lazyload {{ css|length ? css : '' -}}"
    height="{{transformedImage[0].height}}"
    width="{{transformedImage[0].width}}"
  >
 ```

**Comment by aelvan** [comment]
Ok, there we have it. :) Even if you're using S3 to store and serve your transformed imaged, your `imagerSystemPath` has to be a path on your local file system. So, by default `@webroot/imager`, but you can put it anywhere you want on your local server.

This path acts as the cache for Imager, and needs to be persistent to avoid performance issues.

Hope that solves it for you, the rest of the settings and your code looks correct.

**Comment by mizziness** [comment]
So, I tried that but that this is on Heroku, so trying to tell it to use say `/tmp/imager` which exists on each ethereal server causes errors and none of the transforms run.  The settings this way actually do create all the transforms, just in the wrong location ( they are being made in `/public/images/site-images/imager/site-images/xxxxxxx` and I would like them to be in `/public/imager/site-images/xxxxxxx`).  The only piece that doesn't pan out is the url it tries to find the transform at.

**Comment by mizziness** [comment]
Hokay, after a couple hours of stepping through code, I have found a configuration that (theoretically) works but have not tested it with a full HA setup. So if someone else hits this, this worked for me:

```
  'transformer' => "craft",
  'imagerSystemPath' => '/tmp/imager',
  'imagerUrl' => 'https://bucketeer-5bc3db0c-7cba-4693-96f4-f201c5865122.s3.amazonaws.com/public/imager',
  'cacheEnabled' => true,
  ...
  'storages' => ['aws'],
  'storageConfig' => [
    'aws'  => [
        'accessKey' => getenv('AWS_ACCESS_KEY_ID'),
        'secretAccessKey' => getenv('AWS_SECRET_ACCESS_KEY'),
        'region' => getenv('AWS_REGION'),
        'bucket' => getenv('BUCKET_NAME'),
        'folder' => "public/imager",
        'storageType' => 'standard',
        'public' => true
    ],
  ],
```

Then in my app config:

```
    'transformSvgs' => false,
    'aliases' => [
      '@assets' => "https://bucketeer-5bc3db0c-7cba-4693-96f4-f201c5865122.s3.amazonaws.com/public/"
    ],
   ...
   'resourceBasePath' => '@root/web/cpresources/',
    'resourceBaseUrl' => '@root/web/cpresources',
    'aliases' => [
      '@storage' => '@root/../tmp/storage',
    ]
```

**Comment by aelvan** [comment]
Great that you got it working. In general, the default, local transformer in Imager (ie `'transformer' => 'craft'`), isn't really a good fit for architectures with ephemeral disks/servers unless you can set up a persistent storage that you can store the imager cache on. I'm not familiar with Heroku, so can't say if that's what you're using now though. 

For such systems it's generally better to offload the image transforms to a third-party service. Imgix support is built in, and first-party plugins for [AWS Serverless Image Handler](https://plugins.craftcms.com/imager-x-aws-serverless-transformer?craft4) and [ImageBoss](https://plugins.craftcms.com/imager-x-imageboss-transformer?craft4) exist. 

Anyways, hope you find a solution that works for your setup!
