### ISSUE TITLE
{{ craft.imager.transformer }} returns a bool rather than a handle string

### ISSUE THREAD

**Issue by terryupton** [spacecatninja/craft-imager-x#167]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
When I try to use `{{ craft.imager.transformer }}` I am getting back the value 1 rather than the handle/string of the transformer.

I am expecting this to return either 'craft' or 'imgix' as per the settings inside imager-x.php settings file.

The purpose of this is so I can use this setting to check inside my image component to pass specific params into the transform and do a few different things.

### Additional info

- Imager version & edition: 4.1.2 pro
- Craft version: Craft Pro 4.2.0.2
- PHP version: 8.0.20
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.0-39)

**Comment by aelvan** [comment]
4.1.3 is out with this fix.
