### ISSUE TITLE
Positional difference between focal-point cropping in Imgix and Craft

### ISSUE THREAD

**Issue by terryupton** [spacecatninja/craft-imager-x#168]
- [x] bug report
- [ ] feature request
- [ ] general question

### Description
I have noticed on a couple of production sites (Craft 3) a difference in crop position when setting a focal-point.
I believe the same issue exists in Craft 4. 
When using imgix, the cropped image is not quite correct based on the focal point.
If using the native 'craft' transform the cropped image is correct based on the focal point.

This is hard to explain writing so I have done several tests. Here is one to illustrate the problem.

**Focal Point Setting:**
<img width="1332" alt="Screenshot 2022-09-10 at 16 59 05" src="https://user-images.githubusercontent.com/5698596/189491664-626fe887-a7a4-470f-bfde-5e829ed9c3d1.png">

**Craft Transform:**
_(I believe this is correct as the crop uses the focal-point as the centre point)_ 
![Heald_2019-85-1ca803d09a](https://user-images.githubusercontent.com/5698596/189491774-c7e338b0-5bf8-48f1-8127-478a9028e7dc.jpg)

**Imgix Transform:**
_(Imgix seems to start the crop from the bottom of the focal-point)_
![Heald_2019-85](https://user-images.githubusercontent.com/5698596/189491819-c65ab1c7-dd1f-489a-98dd-9899a570425e.jpeg)
Url:
`https://healdlaw.imgix.net/images/heald/Heald_2019-85.jpg?auto=compress%2Cformat%2Cenhance&crop=focalpoint&fit=min&fp-x=0.8852&fp-y=0.9442&h=500&q=80&w=800&s=1f23508e91f2ac18b49cc97cbb5dcee8`
_Please note this was an AVIF image that I have converted to a jpeg._

Now this is perhaps not an ImagerX issue, but instead a imgix issue or how they are using the crop values or how these are being passed in? However, it causes a few issues, in particular when using teaser images and people/heads as the crops are sometimes incorrect. I would like to understand what is causing this and how to get around this issue?

Thanks.

**Comment by terryupton** [comment]
From the url `https://healdlaw.imgix.net/images/heald/Heald_2019-85.jpg?auto=compress%2Cformat%2Cenhance&crop=focalpoint&fit=min&fp-x=0.8852&fp-y=0.9442&h=500&q=80&w=800&s=1f23508e91f2ac18b49cc97cbb5dcee8`

Perhaps what might be happening is that imager is passing in the `crop=focalpoint` and `fit=min` when it should be passing in the fit as crop. ie. `crop=focalpoint&fit=crop`.

https://sandbox.imgix.com/view?url=https%3A%2F%2Fassets.imgix.net%2Funsplash%2Fwalrus.jpg%3Ffp-z%3D1%26fp-y%3D.35%26fp-x%3D.825%26crop%3Dfocalpoint%26fit%3Dcrop%26w%3D320%26h%3D320

**Comment by terryupton** [comment]
Hey @aelvan 

Been doing some further digger and I believe the culprit lines that cause this are https://github.com/spacecatninja/craft-imager-x/blob/v3/src/transformers/ImgixTransformer.php#L258 

<img width="872" alt="Screenshot 2022-09-10 at 19 50 17" src="https://user-images.githubusercontent.com/5698596/189497593-d8bc77b2-eb1e-4f91-8940-9e5261da633b.png">


My global settings have `'allowUpscale'   => false`,

However, in this instance there should be no upscaling regardless as the source image is larger than any of the transforms created via imgix. I have tested this further by making the transform widths much smaller to double check. 

So I think this might be down to some logic or some additional checks required on this. So that fit is set to 'crop' and not 'min' or 'max'.

**Comment by aelvan** [comment]
Thanks for reporting, it appears to be some faulty logic there in terms of `allowUpscale`. Not sure if there's a feasible, or if taking `allowUpscale` into account would have to go. But I'll look into it.

**Comment by aelvan** [comment]
Should be fixed now for both 3.x and 4.x.
