### ISSUE TITLE
getDataUri doesn't work after upgrading to imager x

### ISSUE THREAD

**Issue by helleholmsen** [spacecatninja/craft-imager-x#17]
Just gives an empty string.

**Comment by aelvan** [comment]
Still works as intended for me. Can you fill in this info, it makes it easier to debug:

- Imager version & edition:
- Imager transformer:
- Craft version:
- PHP version:
- Image driver & version:
- Database driver & version:

**Comment by aelvan** [comment]
Did you figure this out? My guess is that you're maybe using Imgix? In that case `getDataUri` has always returned an empty string.

**Comment by helleholmsen** [comment]
@aelvan sorry! Yes, I'm using Imgix. So in the image transform for the base64 placeholder I used the craft transformer when generating the image. And I think this used to work?

**Comment by aelvan** [comment]
Yes, you should still be able to override the transformer on a transform-by-transform basis, and use the Craft transformer to make it. Can you post your template code, in my tests, this still works as expected:

```
{% set transform = craft.imager.transformImage(image, { width: 5, height: 5, format: 'gif' }, {}, { transformer: 'craft' }) %}
{{ transform.getDataUri() }}
```

**Comment by helleholmsen** [comment]
@aelvan got it working with your example there! thanks:)
