### ISSUE TITLE
RAM requirements

### ISSUE THREAD

**Issue by yingban** [spacecatninja/craft-imager-x#171]
Hi,

I tried to regenerate 74 images in 1 transform on a server with 1.5GB RAM, it failed at 75%.
I am aware that images regeneration is resourceful, so I am just wondering what would be the minimum requirements?
We have the resizeFilter set to "gaussian"
We extended it to 3GB, and it's working.

### I'm submitting a... 
- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce
1. ./craft imager-x/generate -r -v="{folder name}" -t="{size}"

### Displayed errors, stack trace, relevant logs  
```
PHP Warning ‘yii\base\ErrorException’ with message ‘exec(): Unable to fork [stty -a 2>&1]’
in /var/www/webroot/ROOT/vendor/yiisoft/yii2/helpers/BaseConsole.php:704
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/webroot/ROOT/vendor/yiisoft/yii2/helpers/BaseConsole.php(704): exec()
#2 /var/www/webroot/ROOT/vendor/yiisoft/yii2/helpers/BaseConsole.php(1085): yii\helpers\BaseConsole::getScreenSize()
#3 /var/www/webroot/ROOT/vendor/yiisoft/yii2/helpers/BaseConsole.php(1040): yii\helpers\BaseConsole::getProgressbarWidth()
#4 /var/www/webroot/ROOT/vendor/spacecatninja/imager-x/src/console/controllers/GenerateController.php(192): yii\helpers\BaseConsole::updateProgress()
#5 [internal function]: spacecatninja\imagerx\console\controllers\GenerateController->actionIndex()
#6 /var/www/webroot/ROOT/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/webroot/ROOT/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#8 /var/www/webroot/ROOT/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction()
#9 /var/www/webroot/ROOT/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#10 /var/www/webroot/ROOT/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#11 /var/www/webroot/ROOT/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction()
#12 /var/www/webroot/ROOT/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#13 /var/www/webroot/ROOT/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest()
#14 /var/www/webroot/ROOT/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#15 /var/www/webroot/ROOT/craft(23): yii\base\Application->run()
```

### Additional info

- Imager version & edition: 4.1.3 
- Craft version: 4.2.4
- PHP version: 8.0.17
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.0-32)

**Comment by aelvan** [comment]
Hi,

If you rerun that command, did it stop at the same point every time?

Most likely it's not due to the fact that it was 75% done, more likely that there's a big image that it doesn't have enough memory to transform. Calculating exactly how much memory is needed is not trivial, but it loosely matches the amount of RAM needed to hold the source image, and the largest transform, open in memory at the same time. 

Did you check how much memory was available when you started the image generation? If 1GB already was used by other things, 500MB is not that much to play with. That can easily be gobbled up if the source images are large. What's the biggest image (in pixels) that you were trying to transform?

**Comment by yingban** [comment]
Hi,

Thank you for you reply.
We already upgrade to 1.5GB RAM, there were only 500MB, which is indeed a bit low.
i also saw that there were huge images uploaded like 9000x5000 1MB png.
I added  'smartResizeEnabled' attribute which might help with performance issue.

**Comment by aelvan** [comment]
4.2.0 is out which addresses a memory leak issue that was affecting generate commands. Also, the output of the generate command has been improved, it will now show processed files, making it easier to detect problematic files that halt the generate process.
