### ISSUE TITLE
unable to purge from imgix

### ISSUE THREAD

**Issue by WHITE-developer** [spacecatninja/craft-imager-x#174]
### I'm submitting a... 

- [ x] bug report
- [ ] feature request
- [ ] general question

### Description
 
Since the update for Craft 4 the $canPurge variable (https://github.com/spacecatninja/craft-imager-x/blob/master/src/services/ImgixService.php#L42) is always set so the getCanPurge() method will always return false and no images can get purged from imgix

### Additional info

- Imager version & edition: ^4.0.0
- Craft version: 4.2.5.1
- PHP version: 8.1

**Comment by aelvan** [comment]
Thanks for reporting, will fix shortly.

**Comment by aelvan** [comment]
Fixed in 4.1.6

**Comment by WHITE-developer** [comment]
Thanks for the quick fix!
