### ISSUE TITLE
Trouble with Amazon S3 and CloudFront

### ISSUE THREAD

**Issue by angieherrera** [spacecatninja/craft-imager-x#176]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to Reproduce
1. Setup AWS storage option in `imager-x.php` config
2. Set up and load a page using `craft.imager.transformImage`

### Description
I've set up a single volume (so far) that uses S3 & CloudFront based off [this article by nystudio107](https://nystudio107.com/blog/using-aws-s3-buckets-cloudfront-distribution-with-craft-cms). Adding assets through the Craft CP > Assets works just fine and the assets' URLs are CloudFront (i.e. https://xxxx.cloudfront.net/folder/image.png). It seems that the transforms Imager creates don't get uploaded to S3 and the URL to the image seems to be incorrect (`https://xxxx.cloudfront.net/volumefolder/####/image.png` as opposed to what I'm guessing should be `https://xxxx.cloudfront.net/transforms/####/image.png`).

Here's what my `imager-x.php` file contains:
```php
<?php
  return array(
    '*' => array(
      'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/assets/imager/',
      'imagerUrl' => 'https://d2raej5j80g9a3.cloudfront.net/',
      'jpegQuality' => 90,
      'interlace' => true,
      'allowUpscale' => false,
      'useFilenamePattern' => true,
      'filenamePattern' => '{basename}_{transformString|shorthash}.{extension}',
      'storages' => ['aws'], // uploads to AWS
      'storageConfig' => [
        'aws' => [
          'accessKey' => getenv('S3_KEY_ID'),
          'secretAccessKey' => getenv('S3_SECRET'),
          'region' => getenv('S3_REGION'),
          'bucket' => getenv('S3_BUCKET'),
          'folder' => 'transforms',
          'requestHeaders' => array(),
          'storageType' => 'standard',
          'public' => false,
          'cloudfrontInvalidateEnabled' => true,
          'cloudfrontDistributionId' => getenv('CLOUDFRONT_DISTRIBUTION_ID'),
        ],
      ],
    )
  );
```

Not sure what I'm doing wrong. So far I've only tested in my local environment.

### Additional info

- Imager version & edition: 3.6.4 Pro
- Imager transformer: craft
- Craft version: 3.7.54
- PHP version: 8.1
- Image driver & version: Imagick 3.7.0 (ImageMagick 7.1.0-49)

**Comment by aelvan** [comment]
Hi,

Have you checked manually in the AWS console if the transforms are in the bucket?

The `imagerUrl` and the storage config is completely independent of each other, so (at a glance) I think the `imagerUrl` should be `https://d2raej5j80g9a3.cloudfront.net/transforms/`. 

If the transforms are not uploaded at all, try enabling your debug bar and check for errors.

**Comment by angieherrera** [comment]
Nope, no transforms in the bucket. In the debug bar, where should I look specifically and am I checking in the CP or front-end? (Apologies; I've hardly used the debug bar so I'm not super familiar with it.)

**Comment by aelvan** [comment]
You'd enable the toolbar for the front-end, and load a front-ent template that do the transform. There's a page for troubleshooting in the docs which explains several other steps you can go through: https://imager-x.spacecat.ninja/troubleshooting.html

The first point is important. If you're retro-fitting an external storage to an existing install, be aware that any transforms that have already been generate (ie, they exist in the `imagerSystemPath`), won't be uploaded to the storage. So you need to essentially clear the cache, or manually transfer any existing transforms to S3.

**Comment by angieherrera** [comment]
Okay, I'm not seeing anything in the debug bar.

I've emptied all transform caches and disabled caching for Imager X. Transformed images still don't upload, but they are getting put in the local folder per the `imagerSystemPath`.

**Comment by angieherrera** [comment]
Unfortunately we ended up taking Imager out of the equation. I'm going to do more testing separately so I don't run into the issue again. Thanks for the help!
