### ISSUE TITLE
Position not working quite as expected

### ISSUE THREAD

**Issue by kevinmu17** [spacecatninja/craft-imager-x#179]
- [x] bug report
- [ ] feature request
- [x] general question

### Description
I have a very wide image, 5120 x 1440. I want to cut it down into 10 equal pieces. So every piece is gonna be 512px wide.
I want to glue them back together, but somehow the position option doesn't work as i expect it to.

I'm calculating the percentage in a forloop from every image, so the first has 0%, the second 10% etc. Here is where the results are getting outputted unexpected. The first 4 images are showing almost duplicates. where the 50% seems to be indeed in the middle. the rest of the percentages are totally off. There isn't a way to use px as unit instead of percentages?

```html
{% set total = 5120 %}
{% for imageSlice in 1..10 %}
    {% set sliceOffset = 512 * loop.index0 %}
    {% set percentage = ( sliceOffset * 100 )/total %}
    {% set transformedJpeg = craft.imager.transformImage(image, [{ width: 512, height: 466 }], { position: percentage~'% 0%'} ) %}
    <img src="{{ transformedJpeg[0].url }}">
{% endfor %}
```

### Steps to reproduce
1. very wide image
2. Cut into 10 pieces with a forloop
3. bad results

### Additional info
- Imager version & edition: 4.1.6 Lite
- Imager transformer: were do i find this one?
- Craft version: Craft Pro 4.2.5.1
- PHP version: 8.1.11
- Image driver & version: Imagick 3.6.0 (ImageMagick 6.9.11-60)

The resource i use for testing:
![20536905](https://user-images.githubusercontent.com/8747373/197079222-306a175a-693b-49d9-92fc-69150539738d.jpg)

Results i'm getting
<img width="2549" alt="Screenshot 2022-10-21 at 01 41 31" src="https://user-images.githubusercontent.com/8747373/197079278-5e17e077-ab94-4412-bd46-211115a046ba.png">

**Comment by aelvan** [comment]
I'll have to test this a bit more, but you can't start with position set to `0%` as it looks like in the above code. The crop will be centered around the focal point, so if the focal point is closer to the edge than 50% of the cropped size, the focal point will no longer be in the center of the transformed image. Also, if you don't need to actually resize the image, you can have a look at the `croponly` mode, which is for doing that.

But, I'll have a closer look at it when I have the time.

**Comment by aelvan** [comment]
Not sure exactly how you got the result that you showed above, I'm not able to reproduce exactly with the code you supplied. But I think it's just a logical error in terms of how focal point cropping works. I'm able to create the desired result as I understand it with the following code:

```
{% for c in 1..10 %}
    {% set percentage = (loop.index0 * 10) + 5 %}
    {% set transform = craft.imagerx.transformImage(image, { width: 512, height: 1440 }, { position: percentage~'% 0%'} ) %}
    <img src="{{ transform.url }}">
{% endfor %}
```

So if each slice is suppose to ba 0-10%, 10-20%, 20-30%, and so on, the focal points have to be at 5%, 15%, 25%, etc. 

A slightly more optimized version of the code above would be:

```
{% set transforms = [] %}

{% for c in 1..10 %}
    {% set percentage = (loop.index0 * 10) + 5 %}
    {% set transforms = transforms|merge([{ width: 512, height: 1440, position: "#{percentage}% 0%" }]) %}
{% endfor %}

{% set transformedImages = craft.imagerx.transformImage(image, transforms) %}

{% for transform in transformedImages %}
    <img src="{{ transform.url }}">
{% endfor %}
```

A bit more verbose, but passing in all the transforms in one go will require a bit less overhead.

**Comment by aelvan** [comment]
Ah, hang on, I understand what's going on in the example you gave. I kinda assumed that you wanted to split the image into 10 slices without any resizing, and that the `height: 466` just was an error (I changed it to the height of the image in my examples).

But, if you want to resize and slice it like this, you'll have to calculate the new total width, based on the new height, and then use that width for the slices. Because of the way `crop` works the image will first be resized so that it fits within the dimensions given, and then it will be cropped based on that new size. Example:

```
{% set height = 466 %}
{% set newTotalWidth = image.width * (height/image.height) %}

{% for c in 1..10 %}
    {% set percentage = (loop.index0 * 10) + 5 %}
    {% set transform = craft.imagerx.transformImage(image, { width: newTotalWidth/10, height: height }, { position: percentage~'% 0%'} ) %}
    <img src="{{ transform.url }}">
{% endfor %}
```

If you actually want to extract 512px wide slices, with a height of 466px, so that you get an image that has a total size of 5120x466px, you'll have to either do the transform in two steps, or use `croponly`. 

Let me know if this helped!
