### ISSUE TITLE
ImgIX not serving transforms even though it is configured as transformer

### ISSUE THREAD

**Issue by brianrivet-tilt** [spacecatninja/craft-imager-x#180]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [ X] general question

### Description
normally when I use ImagerX with ImgIX, the image fields are served up from ImgIX, but on this site they are being server from the local imager folder.

Correct/Expected URL Example: 
https://qci.imgix.net/images/Broken-Barrel-16x9.jpg?auto=compress%2Cformat&fit=clip&q=70&w=320&s=d3359ba29269883eb562cb2045bae847

Current Output: 
https://qualitycourt.com/imager/images/2816/Pic-of-completed-court-aerial_418a03802bb78fe1077227ed13e6bbf6.jpg

### Displayed errors, stack trace, relevant logs  
There are no errors and I don't see anything in the log.

### Additional info

- Imager version & edition: Pro 4.1.6
- Imager transformer: ImgIX
- Craft version: 4.3.0
- PHP version: 8.1.2
- Image driver & version: ?

**Comment by brianrivet-tilt** [comment]
Some additional info. The source I set up on ImgIX is not showing any image requests. I have a stage version of the site on the same server and it is connecting up just fine and serving images from its source. That being the case, API Key is not the issue. I've tried redeploying the source a few times, but nothing happens.

**Comment by aelvan** [comment]
Hi,

If Imgix url's are not being returned, it means Imager is not using the Imgix transformer. Can you share your config (make sure to redact any sensitive information)? Also are you sure that Imager _Pro_ is enabled?

**Comment by brianrivet-tilt** [comment]
When I look in the ImagerX window under Utilities, it shows the version as 4.1.6 Pro. However, I am having an issue where the control panel says I need to pay for trials even though I've already paid for them. I have a ticket open on that. It doesn't show the plugin as being a trial in the settings screen though.

Here's my config:

```
<?php

  use craft\helpers\App;

  return [
	'*' => [	
		'jpegQuality' => 70,
		'webpQuality' => 70,
	],
	'production' => [
		'transformer' => 'imgix',
		'imgixConfig' => [
			'default' => [
				'domain' => App::env('IMGIX_SRC_DOMAIN'),
				'useHttps' => true,
				'signKey' => App::env('IMGIX_TOKEN'),
				'sourceIsWebProxy' => false,
				'useCloudSourcePath' => true,
				'addPath' => [
					'images' => 'images',			            
				],
				'getExternalImageDimensions' => true,
				'defaultParams' => ['auto'=>'compress,format', 'q'=>70],
			],		
		]
	],
	'staging' => [
		'transformer' => 'imgix',
		'imgixConfig' => [
			'default' => [
				'domain' => App::env('IMGIX_SRC_DOMAIN'),
				'useHttps' => true,
				'signKey' => App::env('IMGIX_TOKEN'),
				'sourceIsWebProxy' => false,
				'useCloudSourcePath' => true,
				'addPath' => [
					'images' => 'images',			            
				],
				'getExternalImageDimensions' => true,
				'defaultParams' => ['auto'=>'compress,format', 'q'=>70],
			],		
		]
	],
  ];


```

**Comment by aelvan** [comment]
What does the utility say under "Imager transformer"?

You sure the env handle for production is "production" and not something else?

**Comment by brianrivet-tilt** [comment]
it says craft under imager transformer, but the env file has the environment as production.

**Comment by brianrivet-tilt** [comment]
I found the problem. This site was an upgrade from a Craft 3 site and a lot of the env variables didn't have the CRAFT_ prefix on them. I added it and that fixed it.
