### ISSUE TITLE
ImageKit support [FR]

### ISSUE THREAD

**Issue by shoored** [spacecatninja/craft-imager-x#182]
### I'm submitting a... 
- [ ] bug report
- [x] feature request
- [ ] general question

Hello, do you have any plans to support ImageKit? Might be interesting since imgix has changed their pricing and ImageKit seems to have a lot of the same features.

https://imagekit.io/

**Comment by aelvan** [comment]
Looks like I started making a transformer for it two years ago, had completely forgotten. :) Maybe time to pick it up again, I'll have a look.

**Comment by aelvan** [comment]
Took a while, but wrapped this up finally: https://github.com/spacecatninja/craft-imager-x-imagekit-transformer
