### ISSUE TITLE
Cloudfront invalidations generating errors in the log

### ISSUE THREAD

**Issue by webtrend** [spacecatninja/craft-imager-x#19]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [] general question

### Steps to reproduce

1. ...in the config file cloudfrontInvalidateEnabled => true
2. ...cloudfrontDistributionId => As provided by AWS
3. ...IAM account has following permissions for the above cloudfrontdistributionid 
               "cloudfront:ListInvalidations",
                "cloudfront:GetInvalidation",
                "cloudfront:CreateInvalidation"

### Displayed errors, stack trace, relevant logs  

```
2020-04-03 06:23:35 [-][-][-][error][spacecatninja\imagerx\externalstorage\AwsStorage::upload] An error occured while sending an Cloudfront invalidation request: Error executing "CreateInvalidation" on "https://cloudfront.amazonaws.com/2019-03-26/distribution/EXXXXXXXX/invalidation"; AWS HTTP error: Client error: `POST https://cloudfront.amazonaws.com/2019-03-26/distribution/E8XXXXXXXX/invalidation` resulted in a `400 Bad Request` response:
<?xml version="1.0"?>
<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2019-03-26/"><Error><Type>Sender</Type>< (truncated...)
 Throttling (client): Rate exceeded - <?xml version="1.0"?>
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version & edition: Pro v3.0.0
- Imager transformer:
- Craft version:3.4.5
- PHP version:7.2
- Image driver & version:
- Database driver & version:
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Looks like the error is that the rate limit for invalidation requests was exceeded. Did this happen during some kind of batch processing?

**Comment by webtrend** [comment]
yes, I was updating the asset index on craft. But it continued well after, I think. In any case, is there a way to limit the rate?

**Comment by aelvan** [comment]
I can't think of a way to practically rate limit this at the Craft/Imager side of things, this is a limitation at the CloudFront end.

It was kind of unintentional that reindexing asset volumes triggered auto-generation of transforms (and in turn, upload to S3 and cloudfront invalidation), I've disabled this in v3.0.7. The rate limiting might still occur when running batch transforms from the console commands, or when mass uploading assets, so you should probably do a manual invalidation directly from CloudFront in these cases.
