### ISSUE TITLE
Catch exception while transforming external image with twig

### ISSUE THREAD

**Issue by Megafry** [spacecatninja/craft-imager-x#190]
### I'm submitting a feature request 

- [ ] bug report
- [X] feature request
- [ ] general question

### Description
 
I would like to use this code: [Transforming and optimizing external images in Craft CMS](https://www.spacecat.ninja/blog/transforming-and-optimizing-external-images-in-craft-cms)
unfortunately, it can happen that an image is not available and the resulting Exception makes my page therefore no longer accessible (Error 500)

It would be nice if the function does not return an exception but just return `false`.
Or provide a twig filter to check if the external media exist before calling `craft.imagerx.transformImage()`

### Displayed errors, stack trace, relevant logs  

src/models/LocalSourceImageModel.php:411
```
HTTP status “404” encountered while attempting to download https://xyz.com/old.jpg
```

### Additional info

- Imager version & edition: 4.1.7
- Imager transformer: -
- Craft version: 4.3.1
- PHP version: 8.0
 - Image driver & version: -
 
Or should i solve the problem differently, thanks for feedback

**Comment by aelvan** [comment]
Hi,

You can configure Craft to suppress exceptions using the (suppressExceptions)[https://imager-x.spacecat.ninja/configuration.html#suppressexceptions-bool] configuration setting. If not set, it will depend on the devMode setting what happens (devMode set to true, means errors are not suppressed). 

Hope that helps!
