### ISSUE TITLE
Incorrect url output causing 403 and 404 errors with ImgIX

### ISSUE THREAD

**Issue by brianrivet-tilt** [spacecatninja/craft-imager-x#191]
Hi,

I'm working on a site upgrade from Craft 2 to Craft 4. As part of that I'm incorporating Imager -X for image processing. 

I'm using Img IX to handle the transforms, but I have a few images that are not working like they should (at least as fas as I can tell). The image urls are not outputting as expected and it is causing ImgIX to return 403 errors on some of the images and 404s on others.  Here are the examples:

403:

https://mannersstage.imgix.net/images/1-School-106.jpg?auto=compress%2Cformat&amp;fit=clip&amp;q=70&amp;w=300&amp;s=ed21e023953e74a320de4068bfaf2a0e

I spoke to ImgIX about this and the 403 is happening because the ampersand characters in the url are being written out as html entities ( &amp; instead of just & ). 

404:

For these, I have the images in a subfolder of my uploads folder. For some reason, the url that is being output isn't correctly reflecting the path like it should.

Here's the url to the source image:
https://staging.mannersoftheheart.org/uploads/graphicresources/wilbur.png

And here's what is being output to the template:
https://mannersstage.imgix.net/WiseOlWilbur.png?auto=compress%2Cformat&fit=clip&h=200&q=70&s=c1a81ead382b24e380cc67750bf21a15

I have my ImgIX source set to use the staging.mannersoftheheart.org/uploads folder as the source, and then I have a number of subfolders under that. The images subfolder seems to be working fine, but the graphicresources folder doesn't seem to be outputting any images correctly.

### I'm submitting a... 

- [X ] bug report
- [ ] feature request
- [ ] general question

- Imager version & edition: Pro Trial 4.1.7
- Imager transformer: ImgIX
- Craft version: Pro Trial  4.3.4
- PHP version: 8.1.2
- Image driver & version: not sure.

**Comment by aelvan** [comment]
Hi,

Regarding the encoding issue, where and how is this output in your templates? Twig will sometimes encode output differently depending on where it's used. For instance, in css in style attributes, where you'd need to use the `raw` filter to  get the correct output (ie `{{ myTransformedImage|raw }}`).

In terms of the 404's, I'm not sure why one of your volumes would work and not the others. By default, Imager will assume that the root of a volume, corresponds to the root of the Imgix source (for webfolder sources). If you have a setup where the source points to `/uploads`, and the volumes point to subfolders within this folder (ie images = `/uploads/images`, graphicresources = `/uploads/graphicresources`, and so on), you need to configure this using `addPath` in your source's config. Something like:

```
'imgixConfig' => [
            'myconfig' => [
                'domain' => 'mydomain.imgix.net', // this point to /upload
                'addPath' => [
                    'images' => 'images', // this will add /images to the file path for images in volume "images"      
                    'graphicresources' => 'graphicresources',            
                    'otherstuff' => 'other/stuff',            
                ]
            ]
        ]
```

See https://imager-x.spacecat.ninja/configuration.html#imgixconfig-array 

Let me know if this helps. If not, please supply your imager config (sensitive things redacted) and I'll look further into it.

**Comment by brianrivet-tilt** [comment]
this took care of both issues. Thanks so much!
