### ISSUE TITLE
What's the command to generate element transforms?

### ISSUE THREAD

**Issue by webrgp** [spacecatninja/craft-imager-x#192]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
 
In the [docs](https://imager-x.spacecat.ninja/usage/generate.html#console-commands-for-generating-transforms) we have commands to generate transforms for volumes and fields, but it isn't clear to me how to trigger the generation for element configurations.

Thanks for this plugin and for your help!

### Additional info

- Imager version & edition: 4.1.8 PRO
- Imager transformer: craft
- Craft version: 4.3.4 PRO
- PHP version: 8.1.12
- Image driver & version: Imagick 3.7.0 (ImageMagick 6.9.10-23)

**Comment by aelvan** [comment]
Hi,

The transforms you've configured for elements, can be triggered [using Craft's built-in resave commands](https://craftcms.com/docs/4.x/console-commands.html#resave), with all the granularity that they provide. 

Thanks for reminding me, I need to add that to the docs!

Hope that helps!
