### ISSUE TITLE
Failed to open stream: File name too long

### ISSUE THREAD

**Issue by samlising** [spacecatninja/craft-imager-x#196]
I'm testing out using AWS Serverless Transformer to replace Imagix. 

I ran into an issue when trying to use a imager-x transform of an image with getDominantColor. 

```
{% set productImg = craft.imagerx.transformImage(background, 'productImage') %}
{% set color = craft.imagerx.getDominantColor(productImg[2], 1, 'hex') %}
```

I get an error that the file name is too long. 

PHP Warning – yii\base\ErrorException

fopen(/home/forge/XXXX/storage/runtime/imager/d2z8w197buip6x_cloudfront_net/~eyJidWNrZXQiOiJzYW50aS1hc3NldH... : Failed to open stream: File name too long

The system is running on an Ubuntu server and I believe 256 characters is a limitation of the OS. 

I'm wondering if there is a workaround for this?

**Comment by aelvan** [comment]
This is only tangentially related to using the AWS serverless transformer, in that it generates URL's that are very long and obscure. Since this is a file that's not available locally, Imager downloads the file to be able to analyse it, and the error happens when Imager takes that long URL and tries to create a file out of it.

This is actually the same issue as #194, see my comment there.

**Comment by samlising** [comment]
Got it. 

Wondering if hashing filenames over a certain limit when saving could be backward compatible. 

I guess this is a larger to solve situation than I initially thought. 

Is there a way to generate transforms with the imager-x transformer only in specific situations, but use the awsserverless as the default transformer?

**Comment by aelvan** [comment]
> Wondering if hashing filenames over a certain limit when saving could be backward compatible.

Yes, I'm thinking something along these lines. 

> Is there a way to generate transforms with the imager-x transformer only in specific situations, but use the awsserverless as the default transformer?

Yes, you can override the `transformer` config setting on a per transform basis:

```
{% set productImg = craft.imagerx.transformImage(background, 'productImage', {}, { transformer: 'craft' }) %}
```

**Comment by samlising** [comment]
The override works and is a good work around until there is a solution for the file name character limit. 
Thanks

**Comment by aelvan** [comment]
This was amended in 4.1.10
