### ISSUE TITLE
Is it possible to append a unique hash to transformed image filenames to prevent browsers caching outdated images?

### ISSUE THREAD

**Issue by iainb-cogapp** [spacecatninja/craft-imager-x#200]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Create a template which uses `craft.imager.transformImage`
2. Add an image to an assets field on an entry which uses that template
3. Visit that entry on the frontend
4. In the Craft image editor, make a change to the image asset. e.g. crop
5. Click 'Save'
6. Refresh the page on the frontend
7. The image does not change
8. Clear browser cache or visit the page in a new incognito window
9. The image changes to use the edited version

### Description
 

While this is somewhat expected behaviour — if the filename doesn't change, most browsers will display the cached version for a certain amount of time (depending on cache control headers) — is it possible to include a hash based on the file modified date or file contents in the output filename from imager? This would mean browsers would then recognise it as a different file when the original asset is modified.

I've looked at the [documentation for filenamePattern](https://imager-x.spacecat.ninja/configuration.html#filenamepattern-string) and it seems that neither `basename` or `transformString` would change in the case that an existing image asset is edited.

### Additional info

- Imager version & edition: 4.1.8 PRO
- Imager transformer: craft
- Craft version: 4.3.6.1 PRO
- PHP version: 8.0.24
- Image driver & version: Imagick 3.6.0 (ImageMagick 6.9.11-60)

**Comment by aelvan** [comment]
Sorry for the late reply. Seems useful, so I've added `{timestamp}` as a possible variable for the `filenamePattern` in 4.1.11, you can use it like this:

```
'filenamePattern' => '{basename}_{transformString|hash}_{timestamp}.{extension}'
```

I word of caution though; this will make any change to the file, even if the image itself wasn't really changed, invalidate the transform. The implications of this really depends on your use-case, but there could be instances where the timestamp of the file could change even if you didn't edit it.

**Comment by iainb-cogapp** [comment]
I can confirm the new variable is working as expected, thanks!
