### ISSUE TITLE
Can't find the requested image when revAssetUrls is set true

### ISSUE THREAD

**Issue by belkin** [spacecatninja/craft-imager-x#202]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Enable `revAssetUrls` on general.php file (https://craftcms.com/docs/4.x/config/general.html#revasseturls).
2. Set `transformer` to `craft`
3. Surf to page

### Description
 

Imager-x can't find the requested image while `revAssetUrls` is set `true` on general.php file. This is only happening when the transformer is set to 'craft'. We're mostly using 'imgix' and there we don't have this issue with revAssetUrls.

### Displayed errors, stack trace, relevant logs  

```
2023-03-14 14:11:42 [web.ERROR] [spacecatninja\imagerx\transformers\CraftTransformer::getTransformedImage] Requested image “image-copy.png?v=1678803027” does not exist in path “/WEBSITE_PATH/web/volumes/general” {"memory":5534048} 
```

### Additional info

- Imager version & edition:  4.1.11 | Pro
- Imager transformer: 'craft'
- Craft version: 4.4.1
- PHP version: 8.1.16
- Image driver & version: GD 8.1.16

**Comment by aelvan** [comment]
Thanks for reporting!

I'm not able to reproduce with information given. Can you provide the twig code that generates this error and the full stack trace (send me a DM on discord or email to hi@spacecat.ninja if you're worried about leaking sensitive information), and I'll investigate further.
