### ISSUE TITLE
Save dominant color to database

### ISSUE THREAD

**Issue by luke-nehemedia** [spacecatninja/craft-imager-x#205]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
I am currently trying out the imagerX plugin instead of using imageOptimize and consider switching a number of clients to it, since it lets me create transforms more purposefully by field- or entrytype and not on a per-folder basis. 

I really like the dominantColor feature. However, it makes the website unbearably slow. Sure: I could try to cache it by some means within a macro, but then I have also to make sure the cache is renewed whenever the image is changed etc. 
Wouldn't it be possible to save the dominant color to the database when it is first calculated and then retrieve it from there?

### Additional info
- Imager version & edition: v3.6.5 Pro
- Imager transformer: local
- Craft version: Craft Pro 3.8.5
- PHP version: 7.3.33
- Image driver & version: ImageOptimize

**Comment by aelvan** [comment]
Imager does not use the database, and I think introducing it just to store this information would be a bit heavy handed. But with the new tag based caching functionality, it might be a better solution to just tap into that, and store it in the data cache with the appropriate element tags. I'll have a look.  

Template caching is the easiest workaround for the time being.

**Comment by aelvan** [comment]
Caching have been added to `getDominantColor` and `getPalette`, and cache breaking for element changes has been added.

**Comment by aelvan** [comment]
Also, see #220 regarding the new `generateFlags` option for named transforms, which can be used to warm the cache for these.
