### ISSUE TITLE
Support for Default Focal Point in Named Transforms

### ISSUE THREAD

**Issue by cballenar** [spacecatninja/craft-imager-x#207]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
The default focal point of an image is used for cropping (i.e., `50% 50%`) but there are cases that require a default focal point for the respective transformation. Say if you have many images in the same format where the main content is located on a specific side of the image. Craft CMS addresses these in their transformation by having a `Default Focal Point` with basic options Top-Center, Bottom-Left, Center-Center, etc. This would work great for images that don't have a focal point explicitly defined but with a recurring pattern.

### Additional info

- Imager version & edition: 4 Pro Trial (pending launch)
- Craft version: 4
- PHP version: 8

**Comment by aelvan** [comment]
Hi,

Not sure I understand what you mean. 🤔 The `position` config setting/transform parameter can be used to set a focal point if you want to override the native one. It also takes the built-in keywords (`top-center`, `bottom-left`, etc) as values, and converts them to the correct percentage. Doesn't that do what you want?
