### ISSUE TITLE
imagerTransform is null in graphql 

### ISSUE THREAD

**Issue by vishakha-dev** [spacecatninja/craft-imager-x#208]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. ...
2. ...
3. ...

### Displayed errors, stack trace, relevant logs  

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version & edition:
- Imager transformer:
- Craft version:
- PHP version:
- Image driver & version:

**Comment by vishakha-dev** [comment]
> * ...

write graphql support
imagerTransform is empty

**Comment by aelvan** [comment]
This submission is incomplete, and GraphQL still works as expected. 

Please create a new issue with more details, at least about your environment, versions, and the GraphQL you're trying to execute.
