### ISSUE TITLE
Clear Caches Utility not showing for Lite

### ISSUE THREAD

**Issue by joelzerner** [spacecatninja/craft-imager-x#212]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description

In reading through the documentation my understanding is that the Utility > Imager X screen should be available for both Lite and Pro versions however I can't see it showing using the Lite version.

I've read through the below issue which has some helpful info. It seems to mention that the Utility screen might be disabled by default and setting the "registerCacheOptions" config setting to true will get it showing but I attempted that and it doesn't work - this setting is also not mentioned in the docs.
https://github.com/spacecatninja/craft-imager-x/issues/29#issuecomment-1228741214

Hoping you can clarify whether we need the Pro version to clear caches or should it be showing up for Lite but there's an issue? The docs may need to be clarified a little bit further to make this clearer?

Also, is it possible to clear the runtime cache via a CLI command?

( Docs reference: https://imager-x.spacecat.ninja/usage/caching.html )

### Additional info

- Imager version & edition: Lite 4.1.12
- Craft version: 4.4.9
- PHP version: 8.1

**Comment by aelvan** [comment]
Hi,

Currently, the utility is only available to the PRO version, but that's actually a silly bug. 😬 The utility started its life as a utility for generating transforms using the auto-generate setup that's only available to the PRO version. When I removed caching from Craft's built-in cache (which is what the thread you referenced is related to), I apparently forgot to make it available to LITE too. 

As for cli commands there's somewhat the same oversight; if you enable `registerCacheOptions`, clearing of caches will be added to Craft's native range of `clear-caches` commands. But when it's disabled, there isn't any.

I'll fix this shortly.

**Comment by joelzerner** [comment]
Thanks for explaining that @aelvan - makes sense!

With the `clear-caches` commands via the cli, what is the exact handle for the imager-x commands?

Thanks for your great work on this excellent plugin by the way - it's been a mainstay since the beginning of time for all our Craft projects.

**Comment by aelvan** [comment]
The two commands that are added is 

```
clear-caches/imager-remote-images-cache
clear-caches/imager-transform-cache
```

You can see them in the list of available command if you do `./craft`.
And beware, when enabling `registerCacheOptions`, and doing `clear-caches/all`, this will also wipe the Imager caches, which is usually not desirable, and the reason I removed them by default. :)

Thank you for the kind words, hope you'll continue enjoying Imager!

**Comment by aelvan** [comment]
But, and sorry for the confusion, I wasn't very clear on this... `registerCacheOptions` is only available in the Craft 3 version, it was removed in Craft 4.

**Comment by aelvan** [comment]
4.1.13 fixed the requirement for the utility, and added three new console commands that can be used to clear the cache:

```
imager-x/clear-caches/all
imager-x/clear-caches/runtime-cache
imager-x/clear-caches/transforms-cache
```

This should resolve the issues raised, let me know if there are still gaps that I need to have a look at.

**Comment by joelzerner** [comment]
Awesome - perfect! Thanks for this @aelvan
