### ISSUE TITLE
getBlurhash() is an unknown method

### ISSUE THREAD

**Issue by jayhlee** [spacecatninja/craft-imager-x#216]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Description
I'm trying to create a blurhash (`{% set blurhash = image.getBlurhash() %}`), but I get an error stating that  `getBlurhash()` is an unknown method. 

### Additional info

- Imager version & edition: 4.1.13 PRO
- Imager transformer: craft
- Craft version: 4.4.14 PRO
- PHP version: 8.0.13
- Image driver & version: Imagick (ImageMagick 7.0.11-14)

**Comment by aelvan** [comment]
Can you provide more of your template code, and the actual error. Are you sure that `image` is a transformed image model?

**Comment by jayhlee** [comment]
Hi Aelvan, Sorry. I didn't realize `image` needed to be a transformed image model. Thanks for the guidance!
