### ISSUE TITLE
Create an Image from Headline text

### ISSUE THREAD

**Issue by michalbulla** [spacecatninja/craft-imager-x#217]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
 
I would like to create a teaser image from the Headline text, setting a background color, text color and apply a watermark on it. Is this possible to achieve using the Craft Imager?

Thanks

**Comment by aelvan** [comment]
No, there's not any functionality in Imager to create images from elements like that.
