### ISSUE TITLE
Optimizing images during automatic generation

### ISSUE THREAD

**Issue by jessedobbelaere** [spacecatninja/craft-imager-x#219]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [x] general question

### Description
 
I have a e-commerce list of products, and a product detail page with an image gallery (srcset of different sizes of avif/webp and jpg images). Obviously this is quite painful on initial load if all the transforms run during the web request, sometimes it errors out. 

I've gone ahead and started defining [named transforms](https://imager-x.spacecat.ninja/usage/named-transforms.html) and [automatic generation of transforms](https://imager-x.spacecat.ninja/usage/generate.html) on the queue in a separate worker job, when the entry gets saved, so we don't block the web request anymore. That works great. 

However, when I load the product detail page, I still notice it takes roughly 30s on initial load. I noticed `spacecatninja/imagerx/jobs/OptimizeJob` jobs being dispatched. This is also visible in the request log:
<img width="2517" alt="Screenshot 2023-06-28 at 14 48 24@2x" src="https://github.com/spacecatninja/craft-imager-x/assets/1352979/0768901b-280f-4ef4-881e-1ed5c280b736">

I have the following optimizers in my `imager-x.php` config:

```php
        'optimizers' => ['jpegoptim', 'optipng'],
        'optimizerConfig' => [
            'jpegoptim' => [
                'extensions' => ['jpg'],
                'path' => '/usr/bin/jpegoptim',
                'optionString' => '-m90 --all-progressive -s',
            ],
            'optipng' => [
                'extensions' => ['png'],
                'path' => '/usr/bin/optipng',
                'optionString' => '-o2',
            ]
        ],
```

Even though the optimizer jobs get dispatched onto a queue, and a separate process (worker) picks them up, it still seems to take a lot of seconds of the web request to dispatch each job 🤔 as you see in the screenshot. 

**Is there a suggested solution to prevent optimizers to run on page load? Ideally, the optimizer job can run when the entry gets saved after Imager-X transformed the images automatically.** 

### Displayed errors, stack trace, relevant logs  

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version & edition: 4.1.13 PRO
- Imager transformer:
- Craft version: 4.4.14 PRO
- PHP version: 8.1
- Image driver & version:

**Comment by aelvan** [comment]
Hi, 

This sounds a bit strange, the only time an optimizer queue job can be created, is after a new transform has been created. So I suspect that there're transforms that are not covered by your auto generation that is causing this. Can you try disabling optimizers altogether and see what happens?

But it's worth noting that when using optimizers with auto generation, it could be better to set `optimizeType` config setting to `runtime`. That way, it will be optimized as part of the transform job, not as a separate job that's run afterwards.

And also.. if you're serving avif and webp, I'd consider saving the server som work by just delivering those jpegs/pngs a little bit bigger, since most requests will get the superior file formats anyway. ;)

**Comment by jessedobbelaere** [comment]
Yeah, I had optimizers disabled meanwhile as it doesn't have a lot of benefits with superior file formats 👍 The `optimizeType: runtime` setting will still run the optimizer command in the (web) request, from what I've seen. 

Indeed, I think I've found the issue that there are indeed some transforms not covered by auto generation 🤦 . There were some 75x75 transforms where I explicitly specified `format: 'jpeg'` in twig, but the named transformers did not define the `format` option, so by default it keeps the uploaded format (e.g. `jpg`). So I had an auto transform ending in `.jpg` while the twig template asked for a transform with format `jpeg`, which did not exist, so it created them and optimized them during the web request 🤦
