### ISSUE TITLE
Large Google packages included without being used

### ISSUE THREAD

**Issue by catdevman** [spacecatninja/craft-imager-x#22]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
 
I am only using AWS but when I install this plugin I get ALL of packages needed for Google (cloud, auth, etc...) in all the vendor/google/* directory is ~45MB. Which might not seem like much at first but I am putting this Docker images and even working on moving it into AWS Lambda using Bref which is where I hit the roadblock of 250MB limit per layer... of which my vendor directory was one.  Because of this limitation of the environment the packages that aren't being used are taking up +15% of my available space(of a single layer). AWS is much less noticeable, but still not great at ~7% w/ 19MB on disk.

My suggestion is that you break out the inclusion of aws and/or google into separate "helper" packages for imagerx.

Perhaps `craft-imager-x-aws` and `craft-imager-x-google`...

I know I might be in the minority here... totally understand that but thought I would throw it out there...

Also with the google packages (similar with what I believe the AWS sdk does) it seems like EVERYTHING for google is being included... I know that Google changed from individual packages for services to one big `google/cloud`.  Would it be possible to only include what is needed from each provider that might be enough to slim this down as well.

Thanks!

**Comment by aelvan** [comment]
Hi,

Splitting external storages (and also the Imgix transformer) out into separate packages is a good idea, and probably something I'll do at some point. It's a breaking change though, so it'd have to be in the next major version.

I don't remember atm why I went with the whole `google\cloud` package back when, but looking at it now, it might be that I could maybe only include the storage part of it. I thought I'd done it that way to stay in line with the packages being included by the Google Storage volume plugin from P&T, but I see now that the flysystem driver actually includes `google/cloud-storage`. I'll have a look and see if I can change the dependency to that one instead, maybe that'd help?

**Comment by catdevman** [comment]
Yeah part of this is the fault of Google... Technically speaking `google/cloud` (monolith) replaces the nice small individual packages like `google/cloud-storage`(https://packagist.org/packages/google/cloud replaces section). 

I don't know when `google/cloud-storage` is to be deprecated but it might work for a short term until your next major release for imagerx... I don't want to put a good package like this into technical debt...

**Comment by aelvan** [comment]
I just pushed v3.0.8 which changes the requirement to `google/cloud-storage`. I couldn't find any information about it being deprecated, and everything seemingly works the same with only that. And as long as the flysystem driver is using that, I'm cool with it. :)

It made my vendor folder about whooping 49MB smaller, so hopefully that'll help.
