### ISSUE TITLE
Where should I put optimizers config?

### ISSUE THREAD

**Issue by anvme** [spacecatninja/craft-imager-x#226]
[https://imager-x.spacecat.ninja/usage/optimizers.html](https://imager-x.spacecat.ninja/usage/optimizers.html)
In which file I should put this config?

**Comment by aelvan** [comment]
Hi,

Please refer to the ["Configuration" section of the documentation](https://imager-x.spacecat.ninja/configuration.html). As descried, all general configuration goes into the `imager-x.php` config file, same way as for all other plugins (`handle.php`).

Don't spam.
