### ISSUE TITLE
Where should I put External storages config?

### ISSUE THREAD

**Issue by anvme** [spacecatninja/craft-imager-x#227]
[https://imager-x.spacecat.ninja/usage/external-storages.html](https://imager-x.spacecat.ninja/usage/external-storages.html)
In which file I should put External storages config?

**Comment by aelvan** [comment]
Hi,

Please refer to the ["Configuration" section of the documentation](https://imager-x.spacecat.ninja/configuration.html). As descried, all general configuration goes into the `imager-x.php` config file, same way as for all other plugins (`handle.php`).

Don't spam.
