### ISSUE TITLE
In which file should I put WebP, AVIF, and JPEG XL support config?

### ISSUE THREAD

**Issue by anvme** [spacecatninja/craft-imager-x#228]
[https://imager-x.spacecat.ninja/usage/webp-avif-jpegxl.html](https://imager-x.spacecat.ninja/usage/webp-avif-jpegxl.html)
In which file should I put WebP, AVIF, and JPEG XL support config?

**Comment by aelvan** [comment]
Hi,

Please refer to the ["Configuration" section of the documentation](https://imager-x.spacecat.ninja/configuration.html). As descried, all general configuration goes into the `imager-x.php` config file, same way as for all other plugins (`handle.php`).

Don't spam.
