### ISSUE TITLE
Add a tinypng example in the documentation 

### ISSUE THREAD

**Issue by anvme** [spacecatninja/craft-imager-x#229]
https://imager-x.spacecat.ninja/usage/optimizers.html
Add a tinypng example in the documentation

**Comment by anvme** [comment]
+ how to use the tinypng convert images function? https://tinypng.com/developers/reference#converting-images

**Comment by aelvan** [comment]
Hi,

Please refer to the [documentation for `optimizerConfig` config setting](https://imager-x.spacecat.ninja/configuration.html#optimizerconfig-array) for details on available parameters for all optimizers.

The TinyPNG optimizer does not expose any functionality for converting file formats with TinyPNG, that's not what it's for. It'll optimize the file format you've created with Imager, and that's it.

Don't spam.
