### ISSUE TITLE
Generating LQIP using base64 data URL

### ISSUE THREAD

**Issue by samatcd** [spacecatninja/craft-imager-x#23]
### I'm submitting a... 
- [ ] bug report
- [x] feature request
- [ ] general question

### Description
Can Imager X allow you to return a base64 data url via Graphql API? E.g., in my case I want to generate a LQIP which returns inline with results.

This way I can display the low quality image placeholder which is returned inline with my data while the full image loads in the background.

```graphql
{
  entries (section: "news", orderBy: "dateCreated DESC") {
    title
    ... on news_news_Entry {
      image {
        src: url @imagerTransform (width: 2048, height: 1152, mode: "crop", format: "jpg"),
        preSrc: url @imagerTransform (width: 16, height: 9, mode: "crop", format: "base64"),
        width,
        height
      }
    }
  }
}
```

**Comment by aelvan** [comment]
Hi,

Not currently, but that's something I can add. It'll have to be either a seperate directive (like `imagerBase64` or something) or a separate param (like `...return: 'base64'...`) though, format is still relevant even if the returned data is base64.

**Comment by samatcd** [comment]
I think using a separate directive makes sense — and yes you're right format would still be relevant in many use-cases.

**Comment by aelvan** [comment]
I just pushed v3.0.8 which adds a return parameter (I went with that!) to the imagerTransform directive. so you can do:

```
preSrc: url @imagerTransform (width: 16, height: 9, mode: "crop", format: "gif", return: "base64"),
```

The parameter takes three possible values, `url`, `base64` and `dataUri`. If you're going to use the image data as a LQIP, you might as well go with the `dataUri` one, it'll add the needed prefixes, so all you need to do is insert it into the src attribute.

**Comment by samatcd** [comment]
Fantastic, that's perfect — will give it a try!
