### ISSUE TITLE
Add a imageoptim example in the documentation

### ISSUE THREAD

**Issue by anvme** [spacecatninja/craft-imager-x#230]
https://imager-x.spacecat.ninja/usage/optimizers.html
Add a imageoptim example in the documentation

**Comment by aelvan** [comment]
Hi,

Please refer to the [documentation for `optimizerConfig` config setting](https://imager-x.spacecat.ninja/configuration.html#optimizerconfig-array) for details on available parameters for all optimizers.

Don't spam.
