### ISSUE TITLE
Pure documentation for generate

### ISSUE THREAD

**Issue by anvme** [spacecatninja/craft-imager-x#234]
https://imager-x.spacecat.ninja/usage/generate.html#setting-it-up
Fix the documentation
Give the reference to
As a start, let's say we want all images uploaded to our volume with handle employeeImages, to have two [named transform](https://imager-x.spacecat.ninja/usage/named-transforms.html) called employeeThumbnail and employeePoster be auto-generated
`our volume with handle employeeImages`
Where we can find handle employeeImages in the control panel?

**Comment by aelvan** [comment]
I'm sorry, this is not something the documentation for Imager should need to provide. I suggest you familiarize yourself with the basic concepts of Craft before starting to add plugins. Terms like "volume" and "handle" should be familiar to anyone with a basic knowledge of Craft.
