### ISSUE TITLE
Pure documentation for generate with named transform

### ISSUE THREAD

**Issue by anvme** [spacecatninja/craft-imager-x#235]
https://imager-x.spacecat.ninja/usage/generate.html#setting-it-up
two [named transform](https://imager-x.spacecat.ninja/usage/named-transforms.html) called employeeThumbnail and employeePoster be auto-generated:
If we click on the link, I don't see any employeeThumbnail or employeePoster
Fix this side in documentation please. I don't understand what do you mean. On the link there is no any employeePoster or employeeThumbnail. Edit names please, remove unused names, add names which I can find please

**Comment by aelvan** [comment]
The linked page describes the concept of "named transforms". The examples provided will differ depending on your project. These are _examples_. You need to understand the concepts and then you can customize the examples to your use-case.
