### ISSUE TITLE
No transformed images

### ISSUE THREAD

**Issue by anvme** [spacecatninja/craft-imager-x#236]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Control panel->Settings->Assets  Create new asset
2. Create file config/imager-x-generate.php
```
<?php
return [
    'volumes' => [
        'testlocalasset' => ['ImgTransform']
    ]
];
```
3. Create file config/imager-x-transforms.php
```
<?php
return [
    'ImgTransform' => [
        'displayName' => 'List Thumbnail',
        'transforms' => [
            ['width' => 200],
            ['width' => 400]
        ],
        'defaults' => [
            'format' => 'jpg'
        ]
    ]
];
```
4. Upload new image in assets in the control panel
5. Then, I see the image uploaded successfully. 
6. Run command /app $ ./craft imager-x/generate --volume=testlocalasset
The result is 
```
> Volume `testlocalasset`
> Not recursive

> Generating 2 named transform(s) for 2 image(s).
    - [2/4] (50) IMG_4148.PNG ... done
    - [4/4] (48) bridge.jpg ... done
> Done.
```

### Description
 
In the folder I have uploaded images, I don't see any transforms with 200px and 400px size

### Displayed errors, stack trace, relevant logs  

```
No Errors
```

### Additional info

Imager version & edition	4.2.1 PRO
Imager transformer	craft
Craft version & edition	4.4.16.1 PRO
PHP version	8.0.29
Image driver & version	Imagick 3.7.0 (ImageMagick 7.1.0-50)
Image driver supported formats	jpg, jpeg, gif, png, webp, avif, heic
Custom encoders	No [custom encoders](https://imager-x.spacecat.ninja/usage/webp-avif-jpegxl.html) configured.
Enabled [external storage](https://imager-x.spacecat.ninja/configuration.html#storages-array)s	No external storage configured.
Enabled optimizers

**Comment by anvme** [comment]
+ Assets + file system preview
![Screenshot 2023-07-22 at 16 47 37](https://github.com/spacecatninja/craft-imager-x/assets/56738034/81759d0b-1433-476c-b0ed-961e79e4db9b)
![Screenshot 2023-07-22 at 16 48 40](https://github.com/spacecatninja/craft-imager-x/assets/56738034/c2e84396-51a6-422a-800e-f679d3551409)
![Screenshot 2023-07-22 at 16 47 50](https://github.com/spacecatninja/craft-imager-x/assets/56738034/10eae728-d402-47e8-a21f-eabc956160d3)

**Comment by aelvan** [comment]
Imager transforms are stored in their own folder, not alongside Craft's transforms. By default /web/imager, I suggest you check there.
