### ISSUE TITLE
Issue with CraftTransformer#saveWithCustomEncoder and filenames with spaces

### ISSUE THREAD

**Issue by neildcuk** [spacecatninja/craft-imager-x#239]
### I'm submitting a... 

- [X] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Add volume with spaces in its name (or within a site hosted in a directory with spaces in its name)
2. Add an image to Craft
3. Use custom encoders to output avif, webp etc. (this may not be necessary but it is likely related to the use of `shell_exec`)

### Description
From what we can see, the following lines do not escape the arguments themselves:

https://github.com/spacecatninja/craft-imager-x/blob/v3/src/transformers/CraftTransformer.php#L425-L428

i.e.:
```
            $opts = array_merge([
                '{src}' => $tempFile,
                '{dest}' => $path
            ], $encoder['options'], $customEncoderOptions);
```

This has resulted in the a "Custom encoder failed" error, however there was no output from the encoder cavif as I believe `shell_exec` does not capture output to stderr.

We altered the command on line 442 of `vendor/spacecatninja/imager-x/src/transformers/CraftTransformer.php` to include ` . ' 2>&1'` at the end of the `$command` var which ensured errors were piped to stdout and shown in the error log.

This revealed issues with the filenames for src and dest, confusing the command into splitting a single filename into multiple invalid filenames.

We then changed the above code to the following:

```
            $opts = array_merge([
                '{src}' => escapeshellarg($tempFile),
                '{dest}' => escapeshellarg($path)
            ], $encoder['options'], $customEncoderOptions);
```

Which, on the face of it, appears to have solved the problem. The avif and webp images are generated successfully, produced on the front end (with the `srcset` filter) and seem to work without issues.

Can you please advise as to whether this
   a) would be an appropriate course of action, and,
   b) if possible, could be written into the package for a new release?

### Additional info

- Imager version & edition: 3.6.3.1 (although the same code appears to exist in what I assume is head at present, 3.6.6[1])
- Imager transformer: cavif (custom) and cwebp (custom)
- Craft version: 3.7.54
- PHP version: 8.1
- Image driver & version: Imagick 3.7.0 (ImageMagick 6.9.6-2), GD bundled (2.1.0 compatible)

[1] https://github.com/spacecatninja/craft-imager-x/blob/v3/src/transformers/CraftTransformer.php#L426

**Comment by aelvan** [comment]
Thanks for your thorough testing and report! This has been fixed in 3.6.7 and 4.2.2.
