### ISSUE TITLE
Height and Width values of a transformed image are wrong when mode is `fit` and transformer is Imgix

### ISSUE THREAD

**Issue by johndwells** [spacecatninja/craft-imager-x#24]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Grab an asset
2. Pass it to `craft.imager.transformImage()` with
    1. Imgix as the transformer
    2. Mode to `fit`
    3. Width and height of the transform do **not** match the asset's aspect ratio

e.g. given an `asset` that is 600px square, then:

```
{% set transformed = craft.imager.transformImage(asset, { width : 300, height : 400, mode : 'fit' }, {}, { transformer : 'imgix'}) %}
```

The resulting `transformed` image will be 300px square; yet `transformed.height` will be `400`. Essentially, the `transformed.width` and `transformed.height` values are always equal to their corresponding values of the transform rule, and not the actual dimensions of the transformed image.

If you re-run the above but use `craft` as the transformer, you will see the correct values returned.

### Additional info

- Imager version & edition: 3.0.8
- Imager transformer: Imgix
- Craft version: 3.4.18
- PHP version: 7.4

**Comment by aelvan** [comment]
Thanks for reporting! This was fixed in v3.0.9.
