### ISSUE TITLE
"Generating image transform" - Over 6,000 in queue

### ISSUE THREAD

**Issue by Coysh** [spacecatninja/craft-imager-x#245]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [X] general question

### Steps to reproduce

1. Put Imager X live
2. Looked at queue after a few hours
3. ...

### Description
My queue is growing slowly and has over 5k "Generating image transform" jobs in it.
The queue is running and the transforms are being created.
Cache is on:
![CleanShot 2023-12-19 at 13 25 10@2x](https://github.com/spacecatninja/craft-imager-x/assets/5764356/3f662035-60c2-43ac-8e83-8a9f1e845c44)

Is this a coding error or something else?

### Displayed errors, stack trace, relevant logs  

![CleanShot 2023-12-19 at 13 25 10@2x](https://github.com/spacecatninja/craft-imager-x/assets/5764356/5b6ab1a0-9223-43ca-998e-6744602a0e76)

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

Imager version & edition | 4.2.3 PRO
-- | --
craft
4.5.13 PRO
8.2.13
GD 8.2.13
jpg, jpeg, gif, png, webp, avif
No custom encoders configured.
No external storage configured.
No optimizers configured.

Imager version & edition	4.2.3 PRO
Imager transformer	craft
Craft version & edition	4.5.13 PRO
PHP version	8.2.13
Image driver & version	GD 8.2.13
Image driver supported formats	jpg, jpeg, gif, png, webp, avif
Custom encoders	No [custom encoders](https://imager-x.spacecat.ninja/usage/webp-avif-jpegxl.html) configured.
Enabled external storages	No [external storage](https://imager-x.spacecat.ninja/configuration.html#storages-array) configured.
Enabled optimizers	No [optimizers](https://imager-x.spacecat.ninja/usage/optimizers.html) configured.

**Comment by aelvan** [comment]
Hi,

The "Generating image transform" job is a native Craft job, so it has nothing to do with Imager. If you're not using native transforms on the front end, it's probably transform triggered by the control panel.
