### ISSUE TITLE
How can I generate a Blurhash for a named transform?

### ISSUE THREAD

**Issue by benfeather** [spacecatninja/craft-imager-x#246]
### I'm submitting a... 
- [ ] bug report
- [ ] feature request
- [X] general question

### Description
I am using this GraphQL query to retrieve a named transform:

```
query Test() {
  entry(section: "test") {
    ... on test_test_Entry {
      id
      image {
        title
        alt
        srcset: imagerTransform(transform: "productThumb") {
          url
          width
          height
          mimeType
        }
      }
    }
  }
}
```

The named transform is set up like so:

```
return [
	'productThumb' => [
		'displayName' => 'Product thumbnail',
		'defaults' => [
			'bgColor' => '#ffffff',
			'format' => 'webp',
			'mode' => 'letterbox',
			'ratio' => 1 / 1,
		],
		'transforms' => [
			['width' => 400],
			['width' => 800],
		],
	],
];
```

This produces the expected output:

```
{
  "data": {
    "entry": {
      "id": "3321",
      "image": [
        {
          "title": "Adobe Stock 520806851",
          "alt": null,
          "srcset": [
            {
              "url": "https://cms.ddev.site/transforms/Placeholder/3057/AdobeStock_520806851_a25aaeb4117d8b87b3b46d449ab929be.webp",
              "width": 400,
              "height": 400,
              "mimeType": "image/webp"
            },
            {
              "url": "https://cms.ddev.site/transforms/Placeholder/3057/AdobeStock_520806851_7addaa6068e3de5137602c2bc5a3ff03.webp",
              "width": 800,
              "height": 800,
              "mimeType": "image/webp"
            }
          ]
        }
      ]
    }
  }
}
```

However, I can't seem to figure out how I can generate a blurhash of the transformed image. 
The docs show a blurhash being generated like so:

`blurhash: url @imagerTransform (width: 100, height: 100, mode: "crop", format: "jpg", return: "blurhash")`

But this doesn't work with a named transform. Any help would be appreciated.

### Additional info
- Imager version & edition: 4.2.3 PRO
- Imager transformer: craft
- Craft version: 4.5.13 PRO
- PHP version: 8.2.13
- Image driver & version:  Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by aelvan** [comment]
Hi,

You can use a named transform in the `imagerTransform` directive too, using only the `handle` attribute:

```
blurhash: url @imagerTransform (handle: "myTransform", return: "blurhash")
```

The cave-at being that it needs to be a named transform that returns a single transformed image, and not an array. Something like this:

``` 
return [
	'productThumbBlurhash' => [
		'displayName' => 'Product thumbnail blurhash',
		'transforms' => [
			'width' => 400,
			'bgColor' => '#ffffff',
			'format' => 'webp',
			'mode' => 'letterbox',
			'ratio' => 1 / 1,
		],
	],
];
```

There is no blurhash property on the query unfortunately, as it's not a property on the transformed image model, it's generated when requested due to the large overhead of creating it.

Hope that helps!

**Comment by benfeather** [comment]
Ah, that makes sense, I was using:

`blurhash: url @imagerTransform (transform: "myTransform", return: "blurhash")`

After switching transform to handle, it worked.

Are there any plans to support a named transform with multiple sizes with blurhash?

For example, if my named transform was just a srcset of 1x and 2x sizes:

```
'productThumb' => [
		'displayName' => 'Product thumbnail',
		'defaults' => [
			'bgColor' => '#ffffff',
			'mode' => 'letterbox',
			'ratio' => 1 / 1,
		],
		'transforms' => [
			['width' => 400, 'format' => 'webp',],
			['width' => 800, 'format' => 'webp',],
		],
]
```
Could I use that transform to generate a blurhash? It could use the first transform in the array as a base, in the example above the blurhash would be generated with the 400px image. The output would look something like this:

```
{
  "data": {
    "entry": {
      "id": "3321",
      "image": [
        {
          "title": "Adobe Stock 520806851",
          "alt": null,
          "srcset": [
            {
              "url": "https://cms.ddev.site/transforms/Placeholder/3057/AdobeStock_520806851_a25aaeb4117d8b87b3b46d449ab929be.webp",
              "width": 400,
              "height": 400,
              "mimeType": "image/webp"
            },
            {
              "url": "https://cms.ddev.site/transforms/Placeholder/3057/AdobeStock_520806851_7addaa6068e3de5137602c2bc5a3ff03.webp",
              "width": 800,
              "height": 800,
              "mimeType": "image/webp"
            }
          ],
          "blurhash": "UZJ@~{?b0Lxu~qj[WBj[0Kj[WBj["
        }
      ]
    }
  }
}
```

**Comment by aelvan** [comment]
Changed the behaviour for this in 4.2.4. If the transform returns an array of transforms when doing `@imagerTransform (transform: "myTransform")`, the first transform will be used, and the following operations will be done on that transformed image.

This should let you get the blurhash from the same named transform that you return the srcset from, but you still have to do it in two operations, like:

```
query Test() {
  entry(section: "test") {
    ... on test_test_Entry {
      id
      image {
        title
        alt
        srcset: imagerTransform(transform: "productThumb") {
          url
          width
          height
          mimeType
        }
        blurhash: url @imagerTransform (handle: "productThumb", return: "blurhash")
      }
    }
  }
}
```
