### ISSUE TITLE
Add `placeholder` to the model returned by transformImage()

### ISSUE THREAD

**Issue by johndwells** [spacecatninja/craft-imager-x#25]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description

It would be great to have a `placeholder` method attached to `TransformedImageInterface` that, if called, returns a placeholder that is prepped with the width & height of the transformed image. It could accept the same config model of parameters but the key difference is that `width` and `height` would not default to 1, but instead the dimensions of the transformed image.

This is particularly handy in times when you're using a mode other than `crop`, where the transform rule you're applying to the asset will result in a height or width that isn't equal to the value of your transform.

It would allow for concise code like this:

```
{% set transformed = craft.imager.transformImage(asset, 'transform-handle') %}
{{ tag('img', {
    src : transformed.placeholder,
    'data-src' : transformed.url,
    class : 'lazyload'
}) }}
```

And be guaranteed that the placeholder image has the same dimensions as the image itself, avoiding reflow jitters when the real image is lazyloaded in.

**Comment by aelvan** [comment]
I don't see any real benefits of having this on the transformed image, instead of using the dedicated `craft.imager.placeholder` method. You could achieve what you're proposing above with:

```
{% set transformed = craft.imager.transformImage(asset, 'transform-handle') %}
{{ tag('img', {
    src : craft.imager.placeholder({ width: transformed.width, height: transformed.height }),
    'data-src' : transformed.url,
    class : 'lazyload'
}) }}
```

Which is marginally more code, but also gives you the option of passing various parameters to the placeholder method to control format, color, etc. 

Or, did I misunderstand something in terms of what you're trying to achieve?

**Comment by johndwells** [comment]
Yeah, you've got it right - it's all about convenience and less code.

Generally with our builds, 99% of the time if we're generating a placeholder, it's to assist in lazyloading a transformed image. So the placeholder is always going to be the width & height of the final transform.

You could, of course, still let `transformed.placeholder()` accept parameters to further control format etc.  Basically it can still act the same as `craft.imager.placeholder()`, accept the _default_ `width` and `height` aren't 1px.

Thanks for your time either way!

**Comment by aelvan** [comment]
A `getPlaceholder` method was added in 3.0.10. It takes the same parameters as the placeholder template variable, but will fill in width and height automatically.
