### ISSUE TITLE
Make AWS S3 Credentials Optional when running Craft on AWS EC2/ECS.

### ISSUE THREAD

**Issue by vanburenx** [spacecatninja/craft-imager-x#254]
### I'm submitting a... 
- [ ] bug report
- [x] feature request
- [ ] general question

### Description
Remove the need for **AWS `accessKey`/`secretAccessKey`** credentials if you're running on **AWS EC2/ECS** and instead use **Assumed Roles** (instance profile credentials). This removes the need to create/manage additional/unnecessary credentials.

#### Creating OpenID Connect (OIDC) identity providers
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html

#### Using IAM roles for Amazon EC2 instance variable credentials
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_assume_role.html

#### Task IAM role
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

#### Assuming Role with OpenID Connect (OIDC) (craftcms/aws-s3)
https://github.com/craftcms/aws-s3#assuming-role-with-oidc

#### Tasks running in ECS (craftcms/aws-s3)
https://github.com/craftcms/aws-s3?tab=readme-ov-file#tasks-running-in-ecs

#### Code used for craftcms/aws-s3
https://github.com/craftcms/aws-s3/blob/a04ee659490d53da879e302e660ba3807532a926/src/Fs.php#L423

#### Credential-less auth should be explicit opt-in (craftcms/aws-s3)
https://github.com/craftcms/aws-s3/issues/155

### Additional info

- Imager version & edition: 4.2.4 (PRO)
- Imager transformer: Craft
- Craft version: 4.7.2.1
- PHP version: 8.0.30
- Image driver & version: Imagick (ImageMagick 7.1.1-28)

**Comment by joelzerner** [comment]
We'd be very interested in this feature too.
@aelvan any idea if this feature will be in the pipeline?

**Comment by aelvan** [comment]
Hi,

The biggest show-stopper is that I don't use AWS and I'm not familiar with the concepts here. BUT, I'll try to replicate what Craft does and see where it gets me. Are you on Craft 4 or 5, @joelzerner?

**Comment by aelvan** [comment]
Cool, then I can implement it for 4 to begin with and then port it to 5 when you've tested. That code is essentially identical between 4 and 5 so it doesn't really matter what comes first.

**Comment by aelvan** [comment]
I've tried to replicate what the `craftcms/aws-s3` package does, and you can test it by installing the feature branch via:

```
composer require spacecatninja/imager-x:"dev-dev/craft4-optional-aws-s3-credentials as 4.4.1.1"
```

I made credential-less auth explicit opt in, as planned by P&T, so to enable it you need to set `useCredentialLessAuth` to `true` in your external storage config, ie:

```
        'storageConfig' => [
            'aws' => [ 
                'useCredentialLessAuth' => true,
                ...
            ],
    ]
```

Let me know if this works as expected.

**Comment by joelzerner** [comment]
Thanks @aelvan - we will test this out on Monday and let you know how we go.

**Comment by joelzerner** [comment]
Thanks @aelvan - we've tested and it works!

**Comment by aelvan** [comment]
Great, thanks for testing this. I'll merge it into a release shortly.

**Comment by aelvan** [comment]
This has been added for 4.5.0 and 5.1.0.
