### ISSUE TITLE
Allow transform name to be used in `filenamePattern`

### ISSUE THREAD

**Issue by dgsiegel** [spacecatninja/craft-imager-x#257]
### I'm submitting a... 

- [ ] bug report
- [X] feature request
- [ ] general question

### Description
It would be great to use the name of a named transform in a filename, for example:

```
  'filenamePattern' => '{fullname}{transform}.{extension}'
```

For example, if you have a transform named `1x1`, `{transform}` should be replaced with the name.

**Comment by aelvan** [comment]
Version 4.4.0 now supports the use of `{transformName}` in filename patterns.

**Comment by dgsiegel** [comment]
Thanks @aelvan :)
