### ISSUE TITLE
Transformed Images not uploading in the AWS S3 bucket 

### ISSUE THREAD

**Issue by Brijeshgrg1999** [spacecatninja/craft-imager-x#258]
### I'm submitting a... 
- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

    1.Setup AWS storage option in imager-x.php config
    2.Set up and load a page using craft.imager.transformImage

### Description

I have set up an AWS S3 bucket and CloudFront for asset storage in Craft CMS, and normal assets can be uploaded through the CMS without any issues. However, when I try to use Imager-X to transform images  and store them in the S3 bucket according to this article : [https://imager-x.spacecat.ninja/usage/external-storages.html](url) , but  I can't see any transformed images in the bucket. Is there anything i am missing ? 

Here's my `imager-x.php` configuration file:

```php
<?php
return [
  'imagerUrl' => 'https://d1ef7ke0x2i9g8.cloudfront.net/Singapore-Transformed-Assets/', 
  'storages' => ['aws'], 
  'storageConfig' => [
    'aws' => [
      'accessKey' => getenv('S3_KEY_ID'),
      'secretAccessKey' => getenv('S3_SECRET'),
      'region' => getenv('S3_REGION'),
      'bucket' => getenv('S3_BUCKET'),
      'folder' => 'Singapore-Transformed-Assets',
      'requestHeaders' => array(),
      'storageType' => 'standard',
      'public' => false,
      'cloudfrontInvalidateEnabled' => true,
      'cloudfrontDistributionId' => getenv('CLOUDFRONT_DISTRIBUTION_ID'),
    ],
  ]
];
?>

### Additional info

  - Imager version & edition: 4.3.1 free version 
  - Imager transformer: craft 
  - Craft version: 4.5.10
  - PHP version: 8.1

**Comment by Brijeshgrg1999** [comment]
thanks for the reply , I checked the logs , it seems I am on the free version of the imager-x , so that was the issue I think.

**Comment by aelvan** [comment]
Right, you need to upgrade to pro to use external storages. Can still trial it for free though. :)

**Comment by Brijeshgrg1999** [comment]
cheerss

**Comment by Brijeshgrg1999** [comment]
@aelvan  sorry I am actually facing some issue ,  I want to remove to remove the Transformed images after  it gets upload on the AWS S3 , so that  I added "  { removeTransformedFilesOnUpload' => true  }  in the imager-x.php . But I still see those transformed file on my  " imagerSystemPath " . Is there a way to actually solve this issue ? . FYI I can see the assets on my s3 bucket.

**Comment by aelvan** [comment]
This is the [expected behaviour](https://imager-x.spacecat.ninja/faq.html#i-ve-configured-an-external-storage-but-files-are-still-being-stored-in-my-imagersystempath-what-am-i-doing-wrong), Imager uses the transforms in the `imagerSystemPath` as the primary cache, the external storage is just an additional place the transforms are stored.

**Comment by Brijeshgrg1999** [comment]
so the primary cache will be there forever ?
