### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by mkrigsman** [spacecatninja/craft-imager-x#259]
I just purchased the lite version by mistake. I really need the Pro version. Can I somehow "return" the lite version in order to buy the Pro version?

**Comment by aelvan** [comment]
You should be able to upgrade the license from the plugin store. If you go to Imager's listing page, there should be a button below the pro version for upgrading.

**Comment by mkrigsman** [comment]
Under PRO there is a TRY button but no UPGRADE button. When I hit Try, it
just spins.

Michael Krigsman
Publisher, CXOTalk
M: 617-905-5950

*CXO Conversations on Leadership, Enterprise AI, and the Digital Economy*

**Comment by aelvan** [comment]
Sorry for the late reply, but if you still haven't figured it out you should shoot an email to support@craftcms.com, they'll be able to help you with any refunds or help with the plugin store.
