### ISSUE TITLE
Imager to Imager-x upgrade fails

### ISSUE THREAD

**Issue by E2design** [spacecatninja/craft-imager-x#260]
### I'm submitting a... 
- [X ] bug report

### Description
In the process of moving a site hosted on Arcustech from Craft 3.x to 4.x. Imager was used and needs to be upgraded to Imager-X lite before upgrading Craft. Uninstalled Imager and thereafter trying to install Imager-X from the plugin store within the Craft CP. While installing Craft generates the following error.

PASTE THE ERROR MESSAGE / STACK TRACE HERE
Error: The command "'/usr/bin/php' '/storage/av06134/www/public_html/storage/runtime/composer.phar' 'update' 'spacecatninja/imager-x' '--with-all-dependencies' '--working-dir' '/storage/av06134/www/public_html' '--no-scripts' '--no-ansi' '--no-interaction'" failed.

Exit Code: 2(Misuse of shell builtins)

Working directory: /storage/av06134/www/public_html/public

Error Output:
================
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- spacecatninja/imager-x v3.6.8 requires imgix/imgix-php ^3.0 -> found imgix/imgix-php[3.0.0, ..., 3.3.1] but these were not loaded, likely because it conflicts with another require.
- Root composer.json requires spacecatninja/imager-x v3.6.8 -> satisfiable by spacecatninja/imager-x[v3.6.8].

Composer output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- spacecatninja/imager-x v3.6.8 requires imgix/imgix-php ^3.0 -> found imgix/imgix-php[3.0.0, ..., 3.3.1] but these were not loaded, likely because it conflicts with another require.
- Root composer.json requires spacecatninja/imager-x v3.6.8 -> satisfiable by spacecatninja/imager-x[v3.6.8].

### Additional info

- Image version & edition: Image 2.4.0 
- Craft version: 3.9.13
- PHP version: 7.2.24

**Comment by aelvan** [comment]
Hi,

Not sure I follow, the first error you mention (`Exit Code: 2(Misuse of shell builtins)`) is when you try to upgrade Craft? Or when you uninstall Imager/install Imager X? 

Unless you have some other plugin installed that requires `imgix/imgix-php`, the second error sounds like you didn't completely remove the old version. Try running `composer depends imgix/imgix-php` to determine what plugins currently require the package.

**Comment by E2design** [comment]
The first error message happens when I try to install Imager X. 
I had removed the old imager already. No craft upgrades executed.

**Comment by E2design** [comment]
Solved. After deinstalling the old Imager AND removing the old Imager completely I was able to install Imager X.
