### ISSUE TITLE
Problems creating a custom External Storage

### ISSUE THREAD

**Issue by ax2000** [spacecatninja/craft-imager-x#261]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

I'm trying to create a custom external source via custom module following the instructions under the Extending section in the docs.

I'm sure I'm missing something but somehow it seems that the event `EVENT_REGISTER_EXTERNAL_STORAGES` never gets called from within the module as per below:

```
use spacecatninja\imagerx\ImagerX;
use spacecatninja\imagerx\events\RegisterExternalStoragesEvent;
...
Event::on(
            ImagerX::class,
            ImagerX::EVENT_REGISTER_EXTERNAL_STORAGES,
            function (RegisterExternalStoragesEvent $event) {
                dd($event);
                $event->storages['azure'] = ImagerBlobService::class;
            }
        );
```
The dump and die never gets printed in the screen.

Then I've got the following in the `imager-x.php` config file
```
<?php
use craft\helpers\App;
return [
    'imagerUrl' => App::env('AZURE_BASE_URL_IMAGES') . '/imager',
    'storages' => ['azure'],
    'storageConfig' => [
        'azure'  => [
            'endpoint' => App::env('AZURE_BASE_URL_IMAGES'),
            'connectionString' => App::env('AZURE_CONNECTION_STRING'),
            'container' => App::env('AZURE_CONTAINER_IMAGES'),
            'folder' => 'imager',
            'requestHeaders' => array(),
        ]
    ],
];
```

When parsing the image in the frontend I'm getting `Could not find a registered storage with handle "azure".`

![Screenshot 2024-04-30 at 11 42 04](https://github.com/paragonn/craft-imager-x-azure-blob/assets/2585959/e0a58ad8-f6c1-4e32-a611-a81ebb574766)

Any pointers would be greatly appreciated.

### Additional info

- Imager version & edition: Pro 4.4.0
- Imager transformer:
- Craft version: 4.8.9
- PHP version: 8.2.18
- Image driver & version: Imagick 3.7.0 (ImageMagick 6.9.11-60)

**Comment by aelvan** [comment]
Hi,
Your code looks correct. Are you sure that your module is initialized correctly? If you put a dd in front of the listener, does that trigger?

**Comment by ax2000** [comment]
Thanks for checking this @aelvan .

The module seems to initialise just fine. I've got a bunch of other listeners for some custom features and they all work as expected.

I put a `dd` in front of the listener as you requested and it worked as expected as well.

If you can't replicate on your end, do you think it might be another plugin getting on the way? 

I'll try and disable some plugins and also comment all the other module event listeners to see if its environment related and will let you know.

**Comment by aelvan** [comment]
I'll do some additional testing and get back to you.

**Comment by ax2000** [comment]
Thanks for that @aelvan .

I have commented all extra logic in my custom module and also disabled all plugins except for imager-x and the `dd($event);` from my first comment still doesn't parse when within the `EVENT_REGISTER_EXTERNAL_STORAGES` event listener.

I can't see any plugin interfering but maybe I'm still missing something. Have you managed to replicate from your end by any chance?

**Comment by aelvan** [comment]
Hi again,

I've tested thoroughly now, but I'm not able to replicate. I thought maybe there could be a race condition going on, but it seems like Yii handles that, which was what I originally thought. I can't replicate the `dd` not working either, at my end it always work inside the event handler. 

Are you running in devMode while testing this, or could there we some errors being swallowed by PHP?
Are you 100% sure that the pro version of Imager is activated? You should get some other error then, but.
What happens if you try to register the storage directly like this:

```
ImagerService::registerExternalStorage('azure', ImagerBlobService::class);
```

**Comment by aelvan** [comment]
Right, now I can reproduce. 🎉 

And the solution is simple, you must attach the event handler before `Craft::$app->onInit()`, this is not one of those `most setup tasks` that I see that the Craft documentation recommends now. 🙂

The reason for this is that Imager needs to init storages (and the other components that can be extended), during init. More specifically, it happens during `Plugins::EVENT_AFTER_LOAD_PLUGINS`, which ensures that all modules and plugins are loaded before triggering the event. The code that you put in `onInit` though happens afterwards, so it's too late and the event handler is never run. 

I'll make sure to update the documentation for this.

**Comment by ax2000** [comment]
Thanks @aelvan , it does make sense now!

I've added the listener before the `onInit()` and it works as expected.

Now I'll need to polish the logic for Azure. Hopefully I'll get it working following your built in storages but I might open a ticket if I get stuck. 🙂

Thanks heaps!

**Comment by ax2000** [comment]
Yep - that's exactly what I did.

It does seem to work just fine already 🎉
