### ISSUE TITLE
docs: transform parameters - line break missing before 'fit'

### ISSUE THREAD

**Issue by mandrasch** [spacecatninja/craft-imager-x#263]
hey, just wanted to let you know since we first wondered where option `fit` is described

- https://imager-x.spacecat.ninja/transform-parameters.html#mode-string
- https://imager-x-v4.spacecat.ninja/transform-parameters.html#mode-string

Line break is missing here:

![image](https://github.com/spacecatninja/craft-imager-x/assets/777278/b3e50283-8bb7-443d-afe4-30a7a2a57640)

**Comment by aelvan** [comment]
Thank you, should be fixed now! 🙂

**Comment by aelvan** [comment]
Btw, it seems like transparency works perfectly fine when using a command line encoder like [cavif](https://github.com/kornelski/cavif-rs), which can be configured to be used as a custom encoder in Imager, [see the docs](https://imager-x.spacecat.ninja/usage/webp-avif-jpegxl.html).

Not a perfect solution, but maybe helpful if you or someone else really want to deliver transparent avifs. :)
