### ISSUE TITLE
Maintaining transparency from PNGs

### ISSUE THREAD

**Issue by dhmax88** [spacecatninja/craft-imager-x#264]
Hi! Is it possible to maintain transparency on PNG images, they are being converted to avif and webp but have black backgrounds?

**Comment by aelvan** [comment]
Hi, 

In regards to AVIF, this appears to be a bug in certain compiled ImageMagick versions, see: 

https://askubuntu.com/questions/1411869/creating-avif-or-heic-images-with-transparency-does-not-work-with-imagemagick-in
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1980124
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040307

I've confirmed that this happens both when using Imager X, Craft's native transforms, and Imagick directly, on the latest version of ddev.

In regards to WebP, I don't see any such issues. Have you tested if it's really the case that WebP also has a black background, or might it be that you got served the AVIF file through a picture tag?

**Comment by dhmax88** [comment]
Thanks André

You’re correct - we ended up removing the avif transform and sticking to
just webp. All is transparent as expected!

**Comment by aelvan** [comment]
Btw, it seems like transparency works perfectly fine when using a command line encoder like [cavif](https://github.com/kornelski/cavif-rs), which can be configured to be used as a custom encoder in Imager, [see the docs](https://imager-x.spacecat.ninja/usage/webp-avif-jpegxl.html).

Not a perfect solution, but maybe helpful if you or someone else really want to deliver transparent avifs. :)
