### ISSUE TITLE
New demo page?

### ISSUE THREAD

**Issue by adrienne** [spacecatninja/craft-imager-x#27]
### I'm submitting a... 

- [ ] bug report
- [X] feature request
- [X] general question

### Issue Description

All the old demo pages at the `http://imager.vaersaagod.no/` domain are gone. They were really helpful to see things like the blend modes for watermarking; can they be replaced somewhere?

**Comment by aelvan** [comment]
Wow, I thought noone was using that demo page. ;) That demo site got a bit outdated over time, I'll add example images to the docs instead.

**Comment by aelvan** [comment]
Not exactly what you asked for, but the new Effects Playground covers the effects part of the old demo page: https://effects.spacecat.ninja/

I'll still need to get some examples for watermarks into the docs.

**Comment by aelvan** [comment]
Added an example image to [watermark docs](https://imager-x.spacecat.ninja/transform-parameters.html#watermark-object) that show the different blend modes.
