### ISSUE TITLE
hideClearCachesForUserGroups question

### ISSUE THREAD

**Issue by erikberger** [spacecatninja/craft-imager-x#278]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. ...
2. ...
3. ...

### Description
 
Does the `hideClearCachesForUserGroups` setting hide the **Clear Imager Transforms** and **Purge from Imgix** (if using Imgix) options in the assets table when you select images and click the cog icon?

<img width="565" alt="Screenshot 2024-11-27 at 3 15 24 PM" src="https://github.com/user-attachments/assets/a31e553c-cd85-4234-8436-eed55b3c059e">

If so, I can't seem to get it to work with
`'hideClearCachesForUserGroups' => ['clientAdmin']`

If not, can it in a future release, please?

### Displayed errors, stack trace, relevant logs  

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version & edition: 4.4.1
- Imager transformer:
- Craft version: 4.11.3
- PHP version:
- Image driver & version:

**Comment by aelvan** [comment]
That actually was a setting for disabling the clear cache thing that Imager used to add to the native Craft clear cache utility. But it was removed from it way back, so the setting actually doesn't do anything at the moment. :) Repurposing it for the element actions sounds like an fair idea, I'll give it a little thought and get back to you.

**Comment by aelvan** [comment]
This change has been added for 4.5.0 and 5.1.0.

**Comment by erikberger** [comment]
Tested it out today. Works beautifully. Thanks again.
