### ISSUE TITLE
Transforms in one go (myImage) variable explanation 

### ISSUE THREAD

**Issue by dva-MichaelW** [spacecatninja/craft-imager-x#28]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x ] general question

### Steps to reproduce
  

1. setup craft 3 as per documentation
2. follow the setup steps in the documentation for imager-x (leave the config files to default)
3. paste this code in the template: 
`<img src="{{ craft.imager.transformImage(myImages, [{ width: 200 }, { width: 600 }], { ratio: 16/9, fillTransforms: true }) | srcset }}" alt="Feature Image" class="feature-img">`

### Description
 
Hi there, while using the code mentioned above I get an error message that "the variable myImage does not exist". how do I set this variable or what do I need to place instead?
I've tried setting the variable to null then the code work, but image doesn't load (duhh..)
Also tried to put the url to the file, however then I get:
"Exception – spacecatninja\imagerx\exceptions\ImagerException
Failed to create directory "E:\xampp\htdocs\Projects\craft\project_1\storage\runtime\imager\localhost\Projects\craft\project_1\web\uploads ": mkdir(): Permission denied
↵
Caused by: Exception – yii\base\Exception
Failed to create directory "E:\xampp\htdocs\Projects\craft\project_1\storage\runtime\imager\localhost\Projects\craft\project_1\web\uploads ": mkdir(): Permission denied
in E:\xampp\htdocs\Projects\craft\project_1\vendor\yiisoft\yii2\helpers\BaseFileHelper.php at line 645

↵
Caused by: yii\base\ErrorException
mkdir(): Permission denied
in E:\xampp\htdocs\Projects\craft\project_1\vendor\yiisoft\yii2\helpers\BaseFileHelper.php at line 640"

### Displayed errors, stack trace, relevant logs  

```
Twig\Error\RuntimeError: Variable "myImages" does not exist. in E:\xampp\htdocs\Projects\craft\project_1\templates\home.twig:12
Stack trace:
#0 E:\xampp\htdocs\Projects\craft\project_1\storage\runtime\compiled_templates\34\34d1d1ec02eb87d282d6a9252303b9aacd6ac621f9b4f995a4a12f5652928805.php(75): __TwigTemplate_cbd22b1ff8badf8ea8bd9960afd24a2b349d661a7dc87a81bfacc646d9b8d65f->{closure}()
#1 E:\xampp\htdocs\Projects\craft\project_1\vendor\twig\twig\src\Template.php(184): __TwigTemplate_cbd22b1ff8badf8ea8bd9960afd24a2b349d661a7dc87a81bfacc646d9b8d65f->block_content(Array, Array)
#2 E:\xampp\htdocs\Projects\craft\project_1\storage\runtime\compiled_templates\95\9533580dbea9d02b1e5790bfb4bc8ab9e728d192b202ab5fc5a4bab9507f4832.php(112): Twig\Template->displayBlock('content', Array, Array)
#3 E:\xampp\htdocs\Projects\craft\project_1\vendor\twig\twig\src\Template.php(407): __TwigTemplate_9b132b8b5e7850db3bc50fcd50d69f808e387d61ab252bd74792b531774e9b5d->doDisplay(Array, Array)
#4 E:\xampp\htdocs\Projects\craft\project_1\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#5 E:\xampp\htdocs\Projects\craft\project_1\storage\runtime\compiled_templates\34\34d1d1ec02eb87d282d6a9252303b9aacd6ac621f9b4f995a4a12f5652928805.php(45): Twig\Template->display(Array, Array)
#6 E:\xampp\htdocs\Projects\craft\project_1\vendor\twig\twig\src\Template.php(407): __TwigTemplate_cbd22b1ff8badf8ea8bd9960afd24a2b349d661a7dc87a81bfacc646d9b8d65f->doDisplay(Array, Array)
#7 E:\xampp\htdocs\Projects\craft\project_1\vendor\twig\twig\src\Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#8 E:\xampp\htdocs\Projects\craft\project_1\vendor\twig\twig\src\Template.php(392): Twig\Template->display(Array)
#9 E:\xampp\htdocs\Projects\craft\project_1\vendor\twig\twig\src\TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#10 E:\xampp\htdocs\Projects\craft\project_1\vendor\twig\twig\src\Environment.php(318): Twig\TemplateWrapper->render(Array)
#11 E:\xampp\htdocs\Projects\craft\project_1\vendor\craftcms\cms\src\web\View.php(397): Twig\Environment->render('home', Array)
#12 E:\xampp\htdocs\Projects\craft\project_1\vendor\craftcms\cms\src\web\View.php(458): craft\web\View->renderTemplate('home', Array)
#13 E:\xampp\htdocs\Projects\craft\project_1\vendor\craftcms\cms\src\web\Controller.php(235): craft\web\View->renderPageTemplate('home', Array, 'site')
#14 E:\xampp\htdocs\Projects\craft\project_1\vendor\craftcms\cms\src\controllers\TemplatesController.php(98): craft\web\Controller->renderTemplate('home', Array)
#15 [internal function]: craft\controllers\TemplatesController->actionRender('home', Array)
#16 E:\xampp\htdocs\Projects\craft\project_1\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#17 E:\xampp\htdocs\Projects\craft\project_1\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#18 E:\xampp\htdocs\Projects\craft\project_1\vendor\craftcms\cms\src\web\Controller.php(178): yii\base\Controller->runAction('render', Array)
#19 E:\xampp\htdocs\Projects\craft\project_1\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('render', Array)
#20 E:\xampp\htdocs\Projects\craft\project_1\vendor\craftcms\cms\src\web\Application.php(291): yii\base\Module->runAction('templates/rende...', Array)
#21 E:\xampp\htdocs\Projects\craft\project_1\vendor\yiisoft\yii2\web\Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#22 E:\xampp\htdocs\Projects\craft\project_1\vendor\craftcms\cms\src\web\Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#23 E:\xampp\htdocs\Projects\craft\project_1\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 E:\xampp\htdocs\Projects\craft\project_1\web\index.php(21): yii\base\Application->run()
#25 {main}
```

### Additional info

- Imager version & edition: latest & lite
- Imager transformer: 
- Craft version: 3.4.13
- PHP version: 7.4.3.
- Image driver & version:
- Database driver & version: xampp v3.2.4 - phpmyadmin 
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Hi,

Well, there're several things to be said about this. 

At the most basic level, what Twig is telling you is that `myImages` is not a variable that exists in your template. Imager's `transformImage` method can take different types of input data as the first parameter, but usually you'll be passing in an Asset model, which is what Craft uses to represent an image. Also note that the method takes _one_ image at a time (not several, as your variable name suggests), and that you can't put a `srcset` (which is what the srcset filter outputs) inside a `src` attribute (as you're trying to do).

Knowing nothing about your project, it's hard to know what your content model is, and what you're trying to achieve. But, a common use-case would be that you're in an entry template and you have an Assets field on your entry and want to output the images as optimized srcset's. Here's an example of how you'd do that:

```
{# Let's say your field is named "myImages" #}
{% set myImages = entry.myImages %}

{# Let's loop over those images and output one image tag per image #}
{% for myImage in myImages %}
    
    {# Do the transdforms #}
    {% set transforms = craft.imager.transformImage(myImage, [{ width: 200 }, { width: 600 }], { ratio: 16/9, fillTransforms: true }) %}

    {# Output the image tag. We use the smallest image as the fallback, and assume that the image is full width (ie sizes="100vw"). #}
    <img src="{{ transforms[0].url }}" sizes="100vw" srcset="{{ transforms | srcset }}">
{% endfor %}
```

Hope this helps. If you're new to Craft, it's probably a good idea to familiarize yourself with the native concepts and functionality first, before throwing a plugin into the mix. :)

**Comment by dva-MichaelW** [comment]
Thanks sir! I'm able to load and transform images now, however  when I add the `ratio` parameter the image gets cropped. 

`          {% set featuredImage = entry.featuredImage.one() %}
          {% set transformedImages = craft.imager.transformImage(featuredImage, [{width: 1200}],{ ratio: 16/9, fillTransforms: false }) %}
          <figure class="image is-2by1">
              <img src="{{ transformedImages[0].url }}" sizes="10rem" srcset="{{ transformedImages | srcset }}">
          </figure>`

Removing the parameter will give me the full image, however not with the right ratio. I tried all of the `modes`, but with no results.

**Comment by aelvan** [comment]
Right, that is the intended behaviour. The default mode is `crop`, but if you only specify width, it will only resize, but if you specify width and height, or either and ratio, it'll crop to that format. 

What is it that you want to achieve? If you want a certain format, ie 16:9, and want to see the whole image, you probably need to use the `letterbox` mode (or use `fit` and use css to fill the container, that's actually a better solution).
