### ISSUE TITLE
Asset actions dropdown being replaced.

### ISSUE THREAD

**Issue by shornuk** [spacecatninja/craft-imager-x#30]
Not sure of this is Imager of Craft, but when Imager X is installed the Assets Actions dropdown is being replaced with a single 'Clear Imager Transforms' rather than being appended. 

<img width="264" alt="Screenshot 2020-06-12 at 10 39 49" src="https://user-images.githubusercontent.com/2061819/84489271-5688c880-ac99-11ea-8f61-5239f2d75201.png">

**Comment by aelvan** [comment]
Can you provide the following details:

- Imager version & edition:
- Craft version:
- PHP version:

**Comment by shornuk** [comment]
Imager v3.0.10,  Craft CMS 3.5.0-beta.3 (forgot we we're on beta 😆) and PHP 7.3.11

**Comment by aelvan** [comment]
I've tested with beta.3 now, and I can't reproduce. Can you try enabling the debug toolbar and see of you have any errors there? Also check the js console and make sure that there aren't any errors there. 

What other plugins do you have installed? Might be that there's some other offending plugin that clears out the list of element actions prior to Imager registrering its action, and that being the reason why it's there, but none of the others are.

**Comment by shornuk** [comment]
Just about to test some more. Interestingly, I get the full element actions menu on the 'Temporary Uploads' folder.

**Comment by aelvan** [comment]
@shornuk Did you figure out what was causing this?

**Comment by shornuk** [comment]
Still getting the issue but still cannot work out what's causing it. Nothing in the debug bar and no JS errors. The only thing I have noticed is that it only occurs on dynamically created folders. For example when the save location is set to something like `{postDate|date('Y')}/{id}` - standard folders show all the options. 🤷‍♂️

**Comment by aelvan** [comment]
That's... interesting. What happens if you (temporarily) disable/uninstall Imager? Do you then see the normal options in the dropdown?

**Comment by shornuk** [comment]
So, when I disable Imager, those folders have no multiple select options at all? Presumably that's what Craft is giving as default and then it's Imager that bringing that view in by providing an option?

**Comment by aelvan** [comment]
Yeah, I see the same behaviour. Actually, it's the same for _all subfolders_. I think it's safe to assume that this is a bug in the 3.5 beta, you should [report it to P&T](https://github.com/craftcms/cms/issues).

**Comment by shornuk** [comment]
Have raised with P&T 👍
