### ISSUE TITLE
Images not showing on Safari on Mac OS

### ISSUE THREAD

**Issue by paragonn** [spacecatninja/craft-imager-x#36]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x ] general question

### Steps to reproduce

1. Visit this website on Safari on Mac OS: https://www.alvdalskurlag.no
2. Images do not load

### Description
I expect that this is not a problem with ImagerX, but rather an implementation problem, but I can't figure out why images are not loading on Safari on Mac.

**Comment by aelvan** [comment]
Looks like you've got it fixed, the images load for me now in Safari?

**Comment by paragonn** [comment]
Yes, although the fix was to use an actual image rather than a placeholder as the default. I think it must have something to do with how Safari implements the picture/source elements. So technically image swapping isn't currently taking place on Safari on Mac, however, this is mitigated by lazy image loading.

**Comment by aelvan** [comment]
Weird. Closing since it doesn't sound like an issue with Imager.
