### ISSUE TITLE
Generate transforms layout/html encoding bug

### ISSUE THREAD

**Issue by Jan10** [spacecatninja/craft-imager-x#37]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

In admin/utilities/generate-transforms-utility

![Markup on 2020-07-22 at 09:19:53](https://user-images.githubusercontent.com/192557/88148410-d726d700-cbfe-11ea-93b0-ca2162f6e1b9.png)

Additional info
* Craft version: 3.5.0-RC1.1
* Imager-x version: v3.1.1

**Comment by aelvan** [comment]
This was due to a breaking change in 3.5, it has been fixed in 3.1.2. Thanks for reporting.
