### ISSUE TITLE
Use Imager X with Redactor

### ISSUE THREAD

**Issue by kenvunz** [spacecatninja/craft-imager-x#40]
Hi,

Is there a way to use Imager X with Redactor plugin? I'd like to be able overwrite the `img` HTMl output of Redactor to imager x one with proper `srcset` atrribute.

Sorry, if this is not a right channel for supporting. Happy to remove this and post it somewhere.

Cheers,
Ken

**Comment by aelvan** [comment]
Hi,

There isn't native functionality for this in Imager, but you can use the amazing [Retcon plugin](https://github.com/mmikkel/Retcon-Craft) to do this (and much more). [The docs has a page dedicated to responsive images](https://github.com/mmikkel/Retcon-Craft/wiki/srcset).
