### ISSUE TITLE
Support AV1 Image File Format (AVIF)

### ISSUE THREAD

**Issue by Jan10** [spacecatninja/craft-imager-x#42]
### I'm submitting a... 
- [ ] bug report
- [x] feature request
- [ ] general question

### Description
Please support AVIF 🙏 

Article: 
* https://aomediacodec.github.io/av1-avif/ 
* https://reachlightspeed.com/blog/using-the-new-high-performance-avif-image-format-on-the-web-today/
* https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4
* https://caniuse.com/#feat=avif

**Comment by aelvan** [comment]
Thanks for nudging me about AVIF! Added support in v3.2.0, see [this page in the docs](https://imager-x.spacecat.ninja/usage/avif.html) for details.

**Comment by Jan10** [comment]
Wow! thank you so much!
