### ISSUE TITLE
[FR] AWS Server­less Image Han­dler Transformer

### ISSUE THREAD

**Issue by Joobs** [spacecatninja/craft-imager-x#43]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description
I've been reading the nystudio107 blog post on "Setting Up Your Own Image Transform Service", are there any plans on offering this a default transformer for Imager?

**Comment by aelvan** [comment]
I've looked into it at various occasions, but there're shortcomings in the service that have dissuade me every time. But I'll leave this open and reconsider, I've been looking for a service to make a custom transformer for, just haven't decided which one.

**Comment by Joobs** [comment]
Thanks for leaving it open for consideration.

We looked into it because the free tier has high limits compared to other services (and the blog post about it sells it well).

**Comment by aelvan** [comment]
I just released an Imager X custom transformer for AWS Serverless Image Handler:

https://github.com/spacecatninja/craft-imager-x-aws-serverless-transformer

Hope this helps!
