### ISSUE TITLE
failed install on Craft CMS 3.5.5

### ISSUE THREAD

**Issue by ballmannweber** [spacecatninja/craft-imager-x#44]
we couldn't install imagerx on craft 3.5.5 because of that error:

`Composer konnte die Updates aufgrund eines Abhängigkeitskonflikts nicht installieren.

Composer-Ausgabe: Cannot create cache directory /home/www/p533910/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/www/p533910/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/www/p533910/.composer/cache/repo/https---composer.craftcms.com/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/www/p533910/.composer/cache/files/, or directory is not writable. Proceeding without cache
Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for spacecatninja/imager-x v3.1.4 -> satisfiable by spacecatninja/imager-x[v3.1.4].
- spacecatninja/imager-x v3.1.4 requires google/cloud-storage ~1.0 -> satisfiable by google/cloud-storage[v1.22.0, v1.21.1, v1.21.0, v1.20.1, v1.20.0, v1.19.0, v1.18.0, v1.17.0, v1.16.1, v1.16.0, v1.15.0, v1.14.0, v1.13.0, v1.12.3, v1.12.2, v1.12.1, v1.12.0, v1.10.1, v1.11.0, v1.10.0, v1.9.4, v1.9.3, v1.9.2, v1.9.1, v1.9.0, v1.8.0, v1.4.0, v1.5.0, v1.5.1, v1.5.2, v1.6.0, v1.7.0, v1.7.1, v1.7.2, v1.7.3, v1.0.0, v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.2.0, v1.2.1, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4].
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.22.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.21.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.21.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.20.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.20.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.19.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.18.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.17.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.16.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.16.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.15.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.14.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.13.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.12.3
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.12.2
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.12.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.12.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.10.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.11.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.10.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.9.4
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.9.3
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.9.2
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.9.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.9.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.8.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.4.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.5.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.5.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.5.2
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.6.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.7.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.7.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.7.2
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.7.3
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.0.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.1.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.1.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.1.2
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.1.3
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.1.4
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.1.5
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.2.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.2.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.3.0
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.3.1
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.3.2
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.3.3
- don't install google/cloud v0.131.0|don't install google/cloud-storage v1.3.4
- Installation request for google/cloud (locked at v0.131.0) -> satisfiable by google/cloud[v0.131.0].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.`

any ideas?

**Comment by aelvan** [comment]
Hi,

Can you post your `require` section of your composer.json, looks like there could be incompatible requirements in the plugins/packages you use.

**Comment by ballmannweber** [comment]
this is what I found. craft 3.5.5, updated from 3.4

```
  "require": {
    "aelvan/stamp": "2.1.0",
    "amici/craft-super-pdf": "1.0.2",
    "craftcms/cms": "3.5.5",
    "craftcms/redactor": "2.7.1",
    "nystudio107/craft-minify": "1.2.10",
    "vlucas/phpdotenv": "^3.4.0"
  },
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
```

**Comment by aelvan** [comment]
There's nothing in there that should cause a requirement conflict. How did you try to install it, via the CP? What platform and php version are you on?

**Comment by aelvan** [comment]
Hi @ballmannweber, did you figure this one out?

**Comment by ballmannweber** [comment]
entschuldige die späte antwort – ich war im urlaub. ich habe es nochmal übers terminal probiert und dann klappte es. system is Linux 5.3.0-16-generic and php is 7.3.15.

**Comment by aelvan** [comment]
Sorry, my german is not what is used to be... ;) You tried via the terminal, and then it worked (that's what Google Translate says)? Or it didn't?

**Comment by ballmannweber** [comment]
OH NO!!! sorry, why did I answer you in german???

sorry for the late reply - i was on vacation. i tried again over the terminal and it worked. system is Linux 5.3.0-16-generic and php is 7.3.15 :-)

**Comment by aelvan** [comment]
Haha, no problem! Glad you got it sorted out.
