### ISSUE TITLE
Fail to transform image from Assets "Generate transforms" menu

### ISSUE THREAD

**Issue by ken-gladeye** [spacecatninja/craft-imager-x#45]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Go to Assets
2. Tick on one image
3. Select <Gear Icon> / Generate transforms
4. Go to Queue Manager to observe

### Description
 
*Expected behaviour*
- Selected image is transformed as per configuration

*Current behaviour*
- Selected image is not transformed

### Displayed errors, stack trace, relevant logs  

![Screen Shot 2020-08-26 at 08 19 04](https://user-images.githubusercontent.com/65751307/91225177-41d7af00-e777-11ea-9bc8-f982d1fdf8d5.png)

### Additional info

- Imager version & edition: v3.1.2 PRO
- Imager transformer: craft
- Craft version: Craft Pro 3.4.30
- PHP version: 7.4.4
- Image driver & version: Imagick 3.4.4 
- Database driver & version: MySQL 5.7.19

**Comment by aelvan** [comment]
Looks like you might have set the transforms in your `imager-x-generate.php` incorrectly. `transforms` are always suppose to be an array, even if you just have one transform you want to generate. 

```
        'volumes' => [
            // This is correct
            'images' => ['maxWidth-1600'],

            // This is not
            'images' => 'maxWidth-1600',
        ],
```

**Comment by ken-gladeye** [comment]
yes that was the case, duh! thank you!
