### ISSUE TITLE
Watermarks

### ISSUE THREAD

**Issue by Qwen2020** [spacecatninja/craft-imager-x#46]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
 

I just want a laymans explanation on how to setup watermarks, I can't wrap my head around your documentation, I've pulled the following out of there; 

{% set logo = craft.assets({ id: 11 }).one() %}
{% set watermarkedImage = craft.imager.transformImage(image, { 
	width: 600, 
	watermark: { image: logo, width: 80, height: 80, position: { right: 30, bottom: 30 }, opacity: 0.75, blendMode: 'multiply' }
}) %}

and then in the same template file I'm trying to fun an image through the watermarking as so;

{{ entry.assetTitle.one().url('watermarkedImage') }} 

This just displays an error saying the transformation isn't found? 

### Additional info

- Imager version & edition: Current
- Imager transformer: Watermark?
- Craft version: Current
- PHP version: 7.0.33
- Image driver & version: 
- Database driver & version: mysql

**Comment by aelvan** [comment]
Yeah, that's a mix of the native Craft transform syntax and Imager's. :)

What you do here:

```
{% set watermarkedImage = craft.imager.transformImage(image, { width: 600, watermark: { image: logo, width: 80, height: 80, position: { right: 30, bottom: 30 }, opacity: 0.75, blendMode: 'multiply' } }) %}
```

Is apply the watermark to a transformed image. The resulting `watermarkedImage`, is an [CraftTransformedImageModel](https://imager-x.spacecat.ninja/models.html#crafttransformedimagemodel) which represents the transformed image. If you want to output the url to that image, you'd do:

```
{{ watermarkedImage.url }}
```

The [Usage page in the docs](https://imager-x.spacecat.ninja/usage/) shows the basic usage of Imager transforms, and how they differ from the native ones.

Did that help?

**Comment by Qwen2020** [comment]
Ah I see, sorry I assumed it would built upon the existing transformations. I’ve got it working now, thanks a lot!

**Comment by Qwen2020** [comment]
It’s not possible to tile the watermark is it?

**Comment by aelvan** [comment]
No, sorry, it's not. Maybe you could use an image that already have the watermark tiled, and just fill the whole image with it? :)
