### ISSUE TITLE
GraphQL queries always return null

### ISSUE THREAD

**Issue by jonnyasmar** [spacecatninja/craft-imager-x#48]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Run GraphiQL

2. Execute the following query on some asset that exists in your project:

```gql
query image {
  assets(title: "Pexels photo 1411392") {
    id
    plain: url
    stockTransform: url @transform(mode:"crop")
    imagerTransform: url @imagerTransform(width: 300, height: 300, format: "jpg")
  }
}
```

3. Observe the null response:

```json
{
  "data": {
    "assets": [
      {
        "id": "16491",
        "plain": "/storage/images/pexels-photo-1411392.jpeg",
        "stockTransform": "/storage/images/_AUTOxAUTO_crop_center-center_none/pexels-photo-1411392.jpeg",
        "imagerTransform": null
      }
    ]
  }
}
```

### Description
 
See step 3 above for the current behavior.

Expected behavior is that I would get a working url for an imager-x transformed image.

### Displayed errors, stack trace, relevant logs  

Turned on `devMode` and disabled `suppressExceptions` and haven't been able to find anything that looks relevant.

On Craft 3.4.9 I _was_ seeing a fatal error come back about `can't access getUrl() on null` or something similar, but after upgrading to Craft 3.5.8 to try and fix it, I stopped seeing any fatal errors and just get the null in the response.

### Additional info

- Imager version & edition: 3.2.0
- Imager transformer: stock
- Craft version: 3.5.8
- PHP version: 7.2.24
- Image driver & version: ?
- Database driver & version: MySQL 5.7.23
- Plugins & versions (if relevant): n/a

**Comment by aelvan** [comment]
Hi,

I can't reproduce, your code works as expected for me. Can you try to do a transform at the template level just to see if Imager is working at all. Something like:

```
{% set asset = craft.assets.id(16491).one() %}
{% set test = craft.imager.transformImage(asset, { width: 300, height: 300, format: "jpg" }) %}
```

**Comment by jonnyasmar** [comment]
> Hi,
> 
> I can't reproduce, your code works as expected for me. Can you try to do a transform at the template level just to see if Imager is working at all. Something like:
> 
> ```
> {% set asset = craft.assets.id(16491).one() %}
> {% set test = craft.imager.transformImage(asset, { width: 300, height: 300, format: "jpg" }) %}
> ```

Looks like I was able to correct this. It seems my initial queries contained a `position` property, which was formatted incorrectly and this was breaking the query. I assume the query above was failing because of cached results. Clearing config, cache, etc, and then ensuring that all properties were correct fixed the issue.
