### ISSUE TITLE
max-width for largest transform in srcset?

### ISSUE THREAD

**Issue by sonoflee** [spacecatninja/craft-imager-x#5]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

Quick question: is there a way to get the width (and/or height) of the largest transformed image in a srcset?  I have a case where I'd like to set the max-width on a returned srcset's container based on this value.

**Comment by aelvan** [comment]
Hi,

No, there's not a specific method to get that. But, Imager will return the transforms in the order that you passed in the transforms, so if you order them from biggest to smallest, the first transformed image will be the biggest:

```
{% set transformedImages = craft.imager.transformImage(image, [{width: 1200}, {width: 1000}, {width: 800} ]) %}
{% set largestTransform = transformedImages[0] %}
{% set maxWidth = largestTransform.getWidth() %}
```

And of course, if you order them smallest to largest, the last transformed image will be the largest.

If the sizes are mixed randomly, you'd have to loop over and get the largest one, it's a pretty simple twig loop, although it might look a bit excessive in a template. Something like this (completely untested):

```
{% set maxWidth = 0 %}

{% for transform in transforms %}
    {% set maxWidth = transform.getWidth() > maxWidth ? transform.getWidth() : maxWidth %}
{% endfor %} 
```

Hope this helps.

**Comment by sonoflee** [comment]
This answers my question - thanks for the assistance!
