### ISSUE TITLE
Images referenced in redactor body content are not getting transformed

### ISSUE THREAD

**Issue by JoshCoady** [spacecatninja/craft-imager-x#50]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Config imager x with `'useForNativeTransforms' => true`
2. Create a named transform in craft (not in imager x)
3. Create an entry type with a redactor field
4. Create an entry and insert an image into the redactor field using the transform from step 2
5. Output the redactor body somehow (like in a template or graphql response) 

### Description
 
When you do this, a craft transform url (e.g. /images/_xyz/IMG_4747.jpg -- xyz is the handle for the craft named transform) is used instead of imager x format url (/images/74/IMG_4747_abcdef1234.jpg -- abcdef1234 is the format string hash from the imager x filenamePattern config setting).

It is using the fallback url because there is an exception thrown while imager x is handling `EVENT_GET_ASSET_URL`: 
> Maximum function nesting level of '256' reached, aborting!

This exception is caught in vendor/craftcms/cms/src/services/Elements.php::_getRefTokenReplacement where it logs it and then returns the fallback URL to the asset transform (the craft version):
```
        } catch (\Throwable $e) {
            // Log it
            Craft::error("An exception was thrown when parsing the ref tag \"$fullMatch\":\n" . $e->getMessage(), __METHOD__);

            // Replace the token with the default value
            return $fallback;
        }
```

This is because the call in the imager x event handler for `EVENT_GET_ASSET_URL` to do this: 
```
$transformedImage = ImagerX::$plugin->imagerx->transformImage($event->asset, $transform);
```
results in the event getting triggered again, creating an infinite loop. Because that function above calls:
```
$transformedImages = $transformer->transform($image, $transforms);
```
which calls:
```
$sourceModel = new LocalSourceImageModel($image);
```
which calls:
```
$this->getPathsForVolumeAsset($image);
```
which calls:
```
$this->url = $image->getUrl();
```
which calls:
```
return Craft::$app->getAssets()->getAssetUrl($this, $transform, $generateNow);
```
which calls:
```
$this->trigger(self::EVENT_GET_ASSET_URL, $event);
```
and that is where it loops back to the event handler

### Additional info

- Imager version & edition: Imager X Pro v3.2.0
- Imager transformer: Craft
- Craft version: Craft Pro 3.5.8
- PHP version: 7.4.4
- Image driver & version: Imagick 3.4.4 (ImageMagick 7.0.9-7)
- Database driver & version:
- Plugins & versions (if relevant): Redactor  2.7.4

**Comment by aelvan** [comment]
Thank you for your detailed bug report. This has been fixed for the next release!

Just in case you didn't know, pairing Imager with Retcon makes it possible to make the images responsive, see https://github.com/mmikkel/Retcon-Craft/wiki/srcset. :)

**Comment by JoshCoady** [comment]
Thx for fixing so fast. I didnt know you could unset the transform like that. I was about to submit a PR that took a different tactic:

Replacing the following in `LocalSourceImageModel::getPathsForVolumeAsset`
```
$this->url = $image->getUrl();
```
With
```
use craft\helpers\Assets as AssetsHelper;
...
$this->url = AssetsHelper::generateUrl($image->getVolume(), $image);
```

Because I noticed this is how `craft\elements\Asset::getUrl` returns a URL without transforming:
```
        if ($this->getMimeType() === 'image/gif' && !Craft::$app->getConfig()->getGeneral()->transformGifs) {
            return AssetsHelper::generateUrl($volume, $this);
        }
```

**Comment by aelvan** [comment]
Nice catch, that's probably a better solution, I'll add that for the next release.
