### ISSUE TITLE
Check if named transform exists

### ISSUE THREAD

**Issue by jripmeester** [spacecatninja/craft-imager-x#51]
### I'm submitting a... 

- [ ] bug report
- [X] feature request
- [] general question

### Description
At our agency we're using a default component for our image elements. This contains optimized images and uses a named transform to get the correct sizes for the images. Most of the time the image has a different ratio on mobile so a different named transform is needed. For example largeHeader and largerHeaderMobile. It would be great if there would be a twig function with what we can check if the named transform for mobile exists. So we can fallback to the desktop version if it doesn't exist.

**Comment by aelvan** [comment]
Thanks for suggesting. I've added `hasNamedTransform` and `getNamedTransform` in v3.2.1 ([see docs](https://imager-x.spacecat.ninja/templating.html#craft-imager-hasnamedtransform-name)).
