### ISSUE TITLE
Exception thrown by craft.imager.transformImage()

### ISSUE THREAD

**Issue by khalwat** [spacecatninja/craft-imager-x#54]
Just wanted to give you the heads up on an issue I tracked down that isn't Imager X's fault, but nevertheless may affect people using it.

If you use `{{ craft.imager.transformImage() }}` in your templates, it ends up calling `checkMemoryForImage()`:

```php
            if (!Craft::$app->images->checkMemoryForImage($sourceModel->getFilePath())) {
                $msg = Craft::t('imager-x', 'Not enough memory available to perform this image operation.');
                Craft::error($msg, __METHOD__);
                throw new ImagerException($msg);
            }
```

 in `transformers/CraftTransformer.php`:

https://github.com/spacecatninja/craft-imager-x/blob/master/src/transformers/CraftTransformer.php#L198

The issue is that there's a bug in Craft's `services/Images::checkMemoryForImage()`:

https://github.com/craftcms/cms/issues/6898

A potential fix for now on your end would be to wrap `checkMemoryForImage()` in a try/catch or such

**Comment by aelvan** [comment]
Thanks for letting me know, I've added a try/catch for this, pending a decision from P&T.
