### ISSUE TITLE
imagerUrl for different sites

### ISSUE THREAD

**Issue by Jan10** [spacecatninja/craft-imager-x#55]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Description
I have a craft installation with two [sites/domains](https://craftcms.com/docs/3.x/sites.html) (for example: domain.de and domain.com).
I want to use a different Pull CDN domain for each domain.

How can I define an `imagerUrl` X for page X and an `imagerUrl` Y for page Y in the imager-x configuration?

**Comment by aelvan** [comment]
Currently there isn't a good solution for this use-case (this is the first time in five years that it's come up ;)). You'll have to override imagerUrl in each transform at the template level based on what site you're on. For instance:

```
{% set transforms = craft.imager.transformImage(image, [{ width: 800 }, { width: 1600 }], { ratio: 16/9 }, { imagerUrl: mySitesPullDomain }) %}
```

Where `mySitesPullDomain` has been set to the the correct pull CDN URL.

But I can definitely see that there's a use-case for this, and if I remember correctly there's a helper in Craft for parsing a config value that can have either a flat value, or one that's an array where the keys are each site handle. I'll tag this as an enhancement and get back to it shortly.

**Comment by aelvan** [comment]
As of v3.2.3, you can now do:

```
'imagerurl' => [
     'oneSite' => 'http://one.domain.com/'
     'anotherSite' => 'http://another.domain.com/'
],
```

Where `oneSite` and `anotherSite` _are the handles for your sites_.

**Comment by Jan10** [comment]
Works, thank you!
