### ISSUE TITLE
[FR] Expose information about source image in transformed image model

### ISSUE THREAD

**Issue by aelvan** [spacecatninja/craft-imager-x#58]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [ ] general question

### Description

Add the source model to the target model somehow. This will make it possible to know what image a transform was made from. This is useful for instance if Imager falled back to `fallbackImage`, or if `mockImage` is used.

**Comment by aelvan** [comment]
A `source` property was added in v3.2.4, which makes it possible to inspect the model of the source image that was used to create the transform. For instance `transform.source.extension` to get the original image's extension.

**Comment by davidhellmann** [comment]
Thank you!
