### ISSUE TITLE
Any possiblity of a generate after page load setting?

### ISSUE THREAD

**Issue by Moucky** [spacecatninja/craft-imager-x#6]
Hi again, 
Just wondered if it's possible to have a setting to generate the transforms after the page has loaded? Similar to how Crafts "generateTransformsBeforePageLoad" setting defaults as false so transforms are created after the page is displayed.

Thanks for all your hard work by the way, Imager is great!

**Comment by aelvan** [comment]
No, there isn't. I had a pretty long post about why I haven't implemented anything like this, [in the old repo](https://github.com/aelvan/Imager-Craft/issues/282#issuecomment-549518050). Hopefully now that the auto generation is fixed, you can use that to alleviate the worst of it.

**Comment by Moucky** [comment]
Cool, thanks man. I'll give it a read. Yeah, auto generation should be even better. Appreciate the help!
