### ISSUE TITLE
[FR] Image dimensions/ratio next to label

### ISSUE THREAD

**Issue by bymayo** [spacecatninja/craft-imager-x#60]
We get a lot of clients asking `How big should I export this image as` etc. It would be good if the transforms that are set in `imager-x-transforms.php` could somehow output next to the label of the Assets field as an instruction or note. This way we don't have to manually add these in, or if running 3.5 add a UI element with a note.

**Comment by aelvan** [comment]
Not sure I follow, how would Imager know that a given transform will be used for a given asset field?

**Comment by bymayo** [comment]
@aelvan I was just wondering if it's possible due to us being able to set the transforms in `imager-x-transforms.php` and assigning them to particular fields inside `imager-x-generate.php`

The main reason for this is due to a lot of clients asking for image sizes / ratios. But you can add these in no problem, but remembering to update the field instructions if the size or ratio changes is a bit of a never ending mess. 

Might be impossible to do! Just thought it would make a nice feature.

**Comment by aelvan** [comment]
Yeah, I don't think the transform and generate config files are suitable for that. Sometime, you'll maybe have a clear cut case where an element type and a certain field have a specific transform that you can use to deduce that information. But at least for my part I often use a combination of transforms by volume, field and elements, and also maybe do several transforms per field. Parsing that into a simple recommendation for the end user seems... complicated. 

Also, I try to avoid doing hacks like this that mess with the Craft UI, it's bound to break a lot and often. :)

But, there's nothing stopping anyone else who wants to give it a go from loading the config files and making a custom plugin:

```
$transformsConfig = Craft::$app->config->getConfigFromFile('imager-x-transforms');
$generateConfig = Craft::$app->config->getConfigFromFile('imager-x-generate');

// Go for it! :)
```

**Comment by bymayo** [comment]
`for the end user seems... complicated.`

I did wonder if that was the case 😂 And agree with the Craft UI point also.

It was just an idea to make image size descriptions dynamic for clients creating images. I might give it a go though and see what comes of it!
