### ISSUE TITLE
Automatic generation of configured element transforms

### ISSUE THREAD

**Issue by ccchapman** [spacecatninja/craft-imager-x#61]
### I'm submitting a... 

- [ ] bug report
- [x] feature request
- [x] general question

### Description
 
The Imager X [generate console command](https://imager-x.spacecat.ninja/usage/generate.html#console-commands-for-generating-transforms) allows you to automatically generate transforms for any given volume or field. This console command does not appear to support the configurable element specific transforms. My configuration has specific rules for the blog section, which will generate one transform for two different fields on the entries. Is it possible to use the CLI to trigger automatic transforms with this configuration? There is not exactly a unique identifier for the element transform configuration, so perhaps this is not so straightforward.

Let me know if this is a situation where custom code is required. If that is the case, it could be useful to have a tip on [the documentation](https://imager-x.spacecat.ninja/usage/generate.html#automatic-generation-of-transforms).

```php
<?php

return [
    'elements' => [
        [
            'elementType' =>  \craft\elements\Entry::class,
            'criteria' => [
                'section' => 'blog',
            ],
            'fields' => [
                'image',
                'referenceImage',
            ],
            'transforms' => [
                'post',
            ],
        ],
    ],
];
```

**Comment by aelvan** [comment]
Actually, you can use the built-in functionality in Craft to resave entries to achieve this. Something like:

`./craft resave/entries --section=myBlogSection`

You can use ` ./craft resave/entries --help` to see more options.
