### ISSUE TITLE
Saturated Images on Transform

### ISSUE THREAD

**Issue by bymayo** [spacecatninja/craft-imager-x#63]
### I'm submitting a... 
- [x] bug report
- [ ] feature request
- [ ] general question

### Description
We've recently noticed that images look a bit saturated once transformed. Originally, we narrowed this down to when uploading to Craft as the images in Assets looked saturated also. To fix it we had to force Craft to use Imagick over GD plus a few other parameters:

```
      'preserveImageColorProfiles' => true,
      'preserveCmykColorspace' => true,
      'optimizeImageFilesize' => false,
      'imageDriver' => 'imagick',
```

This fixed the issue when uploading. But now the same happens when transforming.

I've tried adding the below to `imager-x.php`:

`'preserveColorProfiles' => true,`

But the results still look saturated. Is it possible it's using GD over Imagick for the transforms? I tried to look in the config settings but couldn't see anything in there to force Imager to use Imagick.

### Additional info

- Imager version & edition: 3.0.9 Lite
- Imager transformer: Craft
- Craft version: Craft Pro 3.4.27
- PHP version: 7.2.34
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.10-68)
- Database driver & version: MySQL 5.7.31
- Plugins & versions (if relevant): n/a

**Comment by aelvan** [comment]
No, Imager uses the imageDriver setting from Craft, so that's probably not the issue. It's more likely that the preserve-voodoo is not working, it's not very straight forward. Could you send me one of the files you have issues with, and I'll try to figure out what's happening.

**Comment by bymayo** [comment]
@aelvan Where can I ping this to, or shall I send it over Discord?

**Comment by aelvan** [comment]
Send it to hi@spacecat.ninja :)

**Comment by bymayo** [comment]
@aelvan On a second look, it seems the images look okay now! So looks like it might have been a weird caching bug! DOH.

**Comment by aelvan** [comment]
That's great! I was not looking forward to diving into that rabbit hole again! ;)

**Comment by bymayo** [comment]
I bet! Anything to do with Imagick isn't fun at all!
