### ISSUE TITLE
All elements display the same image

### ISSUE THREAD

**Issue by celexus** [spacecatninja/craft-imager-x#66]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [ x] general question

### Description
 
I'm using a textfield to store the path to my product image on the individual product element - an example image path looks like this: 

<code>https://preprod.co.za//medias/?context=bWFzdGVyfHByb2R1Y3QtaW1hZ2VzfDUwMzQwfGltYWdlL2pwZWd8cHJvZHVjdC1pbWFnZXMvaDI5L2g3Yi85MzgyOTgwMzIxMzEwLmpwZ3w5Mjg0YjEyN2FlMGNhN2M0YzIwM2U3OWQ3ZDljZDhiYzRkY2E1OGI4Yzc2NGUxNDk4MDk1NTI5MTkyNzkwMGI5</code>

In my template I loop through my product elements & retrieve the path

<code>{% set image = product.productImage %}</code>

Then run the below transform on it

<code>{% set transformedImage = craft.imager.transformImage(image,{ width:320, height:320, format: 'jpg', jpegQuality: 100, removeMetadata: true, interlace: true }) %}</code>

The problem is that all the products display the exact same image. 

I can see the transform being created - but there is only one even though each and every product has a different image page in the productImage field

When I output <code>{{image}}</code> inside the loop I can see that the path is different for each product

When I output <code>{{transformedImage.url}}</code> directly after the transform the path is the same for each product

Below is the code: 
<code>{% for product in products %}</code>
<code>{% set image = product.productImage %}</code>
<code>{{ image }}</code><p>at this point a different path is output for each product</p>
<code>{% set transformedImage = craft.imager.transformImage(image,{ width:320, height:320, format: 'jpg', jpegQuality: 100, removeMetadata: true, interlace: true }) %}</code>
<code>{{ transformedImage.url }}</code><p>at this point the same transform path is output for each product</p>
<code>{% endfor %}</code>

I know that the server I'm having the issue on is running CloudFlare - could this have something to do with it ? 

### Additional info

- Imager version & edition: LITE v3.1.2
- Craft version: 3.4.30
- PHP version: 7.4.3

**Comment by aelvan** [comment]
You probably just need to enable `useRemoteUrlQueryString` in your config file, [see the docs](https://imager-x.spacecat.ninja/configuration.html#useremoteurlquerystring-bool).

By default, this is set to `false` to improve caching of external URLs that contain timestamps and such, but when the query string actually identifies the image, you need to set it to `true`.

Try that and let me know if it helps.

**Comment by celexus** [comment]
Thank you - that was it. Feeling pretty stupid now

**Comment by aelvan** [comment]
No reason to feel stupid, the list of config settings is pretty chaotic!

**Comment by celexus** [comment]
Most of my image transforms are working fine now, but occasionally I get the following error: 

![Capture](https://user-images.githubusercontent.com/6831255/98566314-495b1e80-22b7-11eb-9eed-abbccee470d9.PNG)

Any idea what might be causing this ?
