### ISSUE TITLE
[Question/FR] Clear Imager Cache as User Permission

### ISSUE THREAD

**Issue by davidhellmann** [spacecatninja/craft-imager-x#68]
We run today in the problem that our client cleared all caches inklusive Imager Caches.
That led to the problem that our server goes down cause too many image transformes was triggered. 

My question: Is it possible to make this checkboxes depending to user rights?
![image](https://user-images.githubusercontent.com/764292/98227393-8f328280-1f57-11eb-8b65-6bee5e9776aa.png)

Or maybe this settings can move into Imager Settings?

Or is that not possible from Craft side?
Any other Recommendation here?

**Comment by aelvan** [comment]
It's not possible out of the box in Craft to restrict that, but I guess I could add separate settings for it in Imager. Would you want that to be per user group, or would an "only for admin" kinda setting be enough?

**Comment by davidhellmann** [comment]
User roles would be the best but I think admin user is more as enough to prevent that. :)

**Comment by aelvan** [comment]
As of v3.2.6, there is now a `hideClearCachesForUserGroups` config setting which can be used to hide the Imager clear caches paths for certain used groups.

``` 
'hideClearCachesForUserGroups' => ['oneGrouphandle', 'anotherGrouphandle']
```
