### ISSUE TITLE
Watermark: Array to string error

### ISSUE THREAD

**Issue by clarknelson** [spacecatninja/craft-imager-x#70]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Copy paste example watermark code into Craft website.

```
{% set logo = craft.assets({ id: 11 }).one() %}
{% set watermarkedImage = craft.imager.transformImage(image, { 
	width: 600, 
	watermark: { image: logo, width: 80, height: 80, position: { right: 30, bottom: 30 }, opacity: 0.75, blendMode: 'multiply' }
}) %}
```

In my website they are valid assets. 

### Description
 

{% set logo = craft.assets({ id: 11 }).one() %}
{% set watermarkedImage = craft.imager.transformImage(image, { 
	width: 600, 
	watermark: { image: logo, width: 80, height: 80, position: { right: 30, bottom: 30 }, opacity: 0.75, blendMode: 'multiply' }
}) %}

### Displayed errors, stack trace, relevant logs  

![image](https://user-images.githubusercontent.com/4106671/98591665-28ce9c80-2296-11eb-8741-214711d86e4d.png)

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version & edition: 3.2
- Imager transformer: default
- Craft version: 3.5.15.1
- PHP version: 7.4
- Image driver & version:
- Database driver & version:
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Hi,

The watermark syntax in Imager isn't supported directly when using the Imgix transformer. You have to use the Imgix specific watermark params (see https://docs.imgix.com/apis/rendering/watermark), and put them inside the `imgixParams` transform parameter. 

The error you're seeing comes from the Imgix library, it seems they don't handle deeply nested objects gracefully. I'll tag this as a bug, and make sure to unset `watermark` in the next release. That'll remove the error at least, so that you could leave the code in if switching between transformers, _but obviously the watermark still wouldn't automatically appear when using Imgi_.

**Comment by clarknelson** [comment]
Thanks for your help, I tried that approach also and got a strange 422 error. 

https://jessicalagrange.imgix.net/assets/general/JLagrange_retouched003_1.jpg?auto=compress%2Cformat&fit=clip&mark=https%3A%2F%2Fjessicalagrange.com%2Fimages%2FJLI-Watermark.svg&position=35.64%2024.31&q=80&w=600&s=802adaada78c535ad8af10e5643667d8

and my template code:

```
{% set img = entry.featuredImage.one() %}
{% set watermarkedImage = craft.imager.transformImage(img, { 
	width: 600,
	imgixParams: { mark: 'https://jessicalagrange.com/images/JLI-Watermark.svg' }
}) %}

<img src="{{ watermarkedImage.url }}"/>
```

I think I know what the issue is, the mark should not be URL escaped. See this article: https://blog.imgix.com/2019/08/13/announcing-support-for-webp-and-svg

and this example url: https://assets.imgix.net/unsplash/mountains.jpg?w=1678&mark=http://assets.imgix.net/imgix_logo_white.svg&markfit=crop&markscale=20&markalign=top,right&markpad=30&markalpha=85&dpr=2&ixlib=imgixjs-3.4.1

I tried using `| raw' but it didn't make a difference.

**Comment by aelvan** [comment]
I tried with the image you used in your example, and got the same result, a 422 error. But using another image worked for me, so the encoding is correct. I'm guessing it chokes on that svg for some reason. Can you test with a bitmap image and see of that works.

**Comment by clarknelson** [comment]
`imgixParms` with a png seems to work, thanks for looking into this
