### ISSUE TITLE
How to handle GIFs with automatic generation of transforms

### ISSUE THREAD

**Issue by xavianaxw** [spacecatninja/craft-imager-x#71]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Set up Asset Volume
2. Configure ImagerX. I currently have a very normal setup with automatic generation of transforms.

### Description
I'm running into memory limit when handling GIFs which was highlighted in the FAQ page as well as https://imager-x.spacecat.ninja/usage/animated-gifs.html. I've decided to not transform the GIF so I was wondering how I should go about it to disable transforming GIFs automatically with `imager-x-generate.php` being set up.

I noticed there is `'safeFileFormats' => ['jpg', 'jpeg', 'png'], // remove gif from transform` under Configurations. Do I just do this and all the GIFs will get ignored and then I add `craft.imager.isAnimated` on the frontend?

### Additional info

- Imager version & edition: 3.2.4
- Imager transformer:
- Craft version: 3.5.15 PRO
- PHP version: 7.4.12
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.8.9-9)
- Database driver & version: MySQL 5.7.32
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Hi,

Yes, what you describe is probably the best approach! The `safeFileFormats` setting is only used for auto generation and cp transforms, so you'd still be able to transform non-animated gifs at the template level. That would happen runtime, but unless most of your images are gifs, that's probably a good tradeoff.

**Comment by aelvan** [comment]
Closing this, let me know if you have any more questions regarding this.
