### ISSUE TITLE
Focal point causing Imgix transforms with Secure URLs to return 403 error

### ISSUE THREAD

**Issue by johndwells** [spacecatninja/craft-imager-x#73]
### I'm submitting a... 
- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Set focal point on asset
2. Set up Imgix with Secure URLs (using "Web Folder" setup)
3. Transform image, e.g. `{% set img = craft.imager.transformImage(asset, 'namedTransform') %}
4. Output image tag, e.g. `<img src="{{ img.url }}">`
5. Image is broken, header says 403

I've noticed that the URL is encoded, and that appears to make a difference. So when I view source, the image URL looks like:

https://domain.imgix.net/photo.jpg?auto=compress%2Cformat&amp;fit=clip&amp;position=64.23%2085.19&amp;w=2400&amp;s=266033be0afab55ad64d4e8bb3520585

Images without a focal point set render fine. I could be wrong, but the Imgix docs describe a different way of setting the focal point:

https://docs.imgix.com/apis/rendering/focalpoint-crop

But, I haven't studied this closely.

### Additional info

- Imager version & edition: Pro v3.2.4
- Imager transformer: Imgix (Web Folder, Secure URLs)
- Craft version: 3.5.15.1
- PHP version: 7.4

**Comment by aelvan** [comment]
Hi,

i'm not able to reproduce, but you're correct, position is not suppose to be passed to the imgix url. I've fixed this for v3.2.5. But I'm not sure if that's the issue you're seeing, but could you try to update and let me know whether or not it fixes the issue.

**Comment by johndwells** [comment]
@aelvan I'm curious why the focal point wouldn't be passed to Imgix? Imgix does support the concept. And it's certainly going to create a different crop. Or is it up to _us_ to pass the focal point parameters, as part of the `imgixParams`? Which doesn't seem right either...

**Comment by aelvan** [comment]
Sorry, I was a bit unclear there! Focal points will be passed to Imgix, in the correct format, _if the transform involves cropping_. You're example above is a transform with only width specified, which means there is no cropping. What happened prior to the 3.2.5 update was that `position`, Imager's internal representation of the focal point, was not unset properly, which resulted in it making its way into the transform URL. After 3.2.5, position is always removed, and it is converted to the correct params if the transform results in cropping.

But as I said, I don't think this really was the cause of your error, but update just to be sure.

**Comment by johndwells** [comment]
@aelvan ah ok! Thanks for the explanation. I will run some tests - closing now, will re-open or submit a new ticket if necessary.
