### ISSUE TITLE
Target assets within craft-neo blocks (automatic transforms)

### ISSUE THREAD

**Issue by Antimated** [spacecatninja/craft-imager-x#76]
### I'm submitting a... 

- [x] bug report
- [x] feature request
- [ ] general question

(not sure if it's a bug or if it's something that needs to be implemented)

### Description
 
I'm trying to automatically generate images inside a [craft-neo](https://github.com/spicywebau/craft-neo) field.
I made a neo field with the handle "contentBuilder". This field has a block with the handle "textImage" and has an image field that has the handle "image".
The "contentBuilder" block will be present on multiple sections but for now I'll only target the "pages" section.

**imager-x-transforms.php**
```
<?php

return [
    'textImage' => [
        'displayName' => 'Text / image',
        'transforms' => [
            ['width' => 360],
            ['width' => 600],
            ['width' => 1200]
        ],
        'defaults' => [
            'format' => 'jpeg'
        ]
    ]
];
```

**imager-x-generate.php**

_Attempt one_
```
<?php

return [
    'elements' => [
        [
            'elementType' =>  \craft\elements\Entry::class,
            'criteria' => [
                'section' => ['pages'],
            ],
            'fields' => ['contentBlocks:textImage.image'],
            'transforms' => ['textImage']
        ],
    ],    
];
```

_Attempt two_
```
<?php

return [
    'elements' => [
        [
            'elementType' =>  \craft\elements\Entry::class,
            'criteria' => [
                'section' => ['pages'],
            ],
            'fields' => ['contentBlocks:*.image'],
            'transforms' => ['textImage']
        ],
    ],    
];
```

Both of these attempts do nothing at all. Am I doing something wrong or are automatic transforms in neo blocks not supported yet?

### Additional info

- Imager version & edition: v3.2.6 (pro)
- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.4.9
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.6-2)
- Database driver & version: MySQL 5.7.30
- Plugins & versions (if relevant): Neo 2.8.14

**Comment by aelvan** [comment]
Yes, there is no explicit support for Neo currently. 

What you could try though, is targeting the Neo Block element directly, see [my comment here](https://github.com/spacecatninja/craft-imager-x/issues/75#issuecomment-731835193) regarding targeting custom elements. Maybe something like this would work:

```
[
        'elementType' =>  \benf\neo\elements\Block::class,
        'criteria' => [
            'fieldId' => 28
        ],
        'fields' => ['image'],
        'transforms' => ['textImage']
]
```

This would target all blocks in a field with that ID, and it's `image` fields. The difficult part is crafting that criteria to match you needs, and it depends on what properties the Neo block supports.

I'll leave this open and give some thought to whether or not I want to build any extra support for Neo into Imager.
