### ISSUE TITLE
Target assets within super table field

### ISSUE THREAD

**Issue by xavianaxw** [spacecatninja/craft-imager-x#77]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x] general question

### Steps to reproduce

1. Install ImagerX
2. Add configuration file as included below.

```
// imager-x.php
// standard setup here with AWS configured
```

```
// imager-x-transforms.php
// standard setup here
```

```
// imager-x-generate.php
...
    [
      'elementType' =>  \craft\elements\GlobalSet::class,
      'criteria' => [
        'handle' => ['acknowledgement'],
      ],
      'fields' => ['acknowledgement:image'],
      'transforms' => ['imageTransform']
    ],
...
```

### Description
I'm trying to run auto-generate for my transforms on my `acknowledgement` SuperTable field. Here's how the structure looks like.

Handle: `mediaBlock`
Type: SuperTable by verbb
Fields:
* `description` | Plain Text
* `image` | Asset (multiple)

I did some reading and it states I have to refer to my field as such: `<MatrixFieldHandle>:<MatrixFieldType>.<FieldHandle>` which in my case translates to `acknowledgement:*.image` as it states in the documentation that SuperTable does not have a field type so we have to use `*`

Reference to doc: https://imager-x.spacecat.ninja/usage/generate.html#setting-it-up

### Displayed errors, stack trace, relevant logs  

No error message. Would be great if you can show me how to debug this so it'll be useful for the future.

Also, there is no successful message like such when I save the change.

```
2020-11-25 23:32:45 [-][1][-][info][yii\db\Command::execute] INSERT INTO `queue` (`job`, `description`, `timePushed`, `ttr`, `delay`, `priority`, `channel`) VALUES ('O:39:\"spacecatninja\\imagerx\\jobs\\TransformJob\":5:{s:7:\"assetId\";i:1406;s:10:\"transforms\";a:2:{i:0;s:9:\"heroImage\";i:1;s:17:\"heroHomepageImage\";}s:11:\"description\";s:52:\"Generating transforms for asset \"john.jpg\" (ID 1406)\";s:30:\"\0craft\\queue\\BaseJob\0_progress\";i:0;s:35:\"\0craft\\queue\\BaseJob\0_progressLabel\";N;}', 'Generating transforms for asset \"john.jpg\" (ID 1406)', 1606375965, 300, 0, 1024, 'queue')
```

### Additional info

- Imager version & edition: ImagerX v3.2.4
- Imager transformer: 
- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.4.12
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.10-23)
- Database driver & version: MySQL 5.7.32
- Plugins & versions (if relevant):

**Comment by aelvan** [comment]
Hi,

I tested this, and it seems to work, probably it's just a configuration error.

As you noted below your example, the syntax to target a supertable field, is `<supertablefield>:*.<fieldname>`. In your example, you have `'fields' => ['acknowledgement:image'],`. If this is you actual code, it should be `'fields' => ['acknowledgement:*.image'],`. Does that help?

The queue entry from the log is for an asset with id `1406` and name `john.jpg`, is that the asset you expected to be transformed? The transforms that was added to the queue was `heroImage` and `heroHomepageImage`, whereas your example has `imageTransform`. Not sure if this either is your actual code, or a modified example, but if it is, and the asset is the correct one, it seems like there might be another auto generate config that targets the `image` field. Please note that if you for instance target `image` in the fields-part of the auto generate config, it will match for all elements, including supertable blocks.

**Comment by xavianaxw** [comment]
So it succeeded with `acknowledgement:*.image` ?

The log message was just an example of something else working just to show that my imager configuration was working for other cases.

**Comment by xavianaxw** [comment]
I've changed it to the following

```
    [
      'elementType' => \craft\elements\GlobalSet::class,
      'criteria' => [
        'handle' => ['acknowledgement'],
      ],
      'fields' => ['acknowledgement:*.flag'],
      'transforms' => ['flags'],
    ],
```

but it still doesn't work.

**Comment by aelvan** [comment]
Is `acknowledgement` both the handle of your global, and your supertable field? You mention `mediaBlock` in your first post, if that's your supertable field handle, `acknowledgement` is you global, and `flag` is the assets field inside the supertable block, the code should look like this:

```
[
      'elementType' => \craft\elements\GlobalSet::class,
      'criteria' => [
        'handle' => ['acknowledgement'],
      ],
      'fields' => ['mediaBlock:*.flag'],
      'transforms' => ['flags'],
    ],
```

**Comment by xavianaxw** [comment]
Apologies. I did put `mediaBlock` in my initial post but I thought I'd used a simpler example and forgot to update it.

The current field I'm trying to target lives in a GlobalSet with a handle of `acknowledgement`. The field that I'm trying to run imager with is a SuperTable field with the handle `acknowledgement` as well with an Asset field with the handle `flag`

I hope that clears things up. I've attached a screenshot of my field setup if you require.

![Screen Shot 2020-11-30 at 11 13 16 am](https://user-images.githubusercontent.com/8082158/100557405-12e45280-32fd-11eb-9e28-96c5e5a752fa.png)

**Comment by aelvan** [comment]
Ok! Then I'm kinda out of ideas, it looks like what you had in your previous post should work, as long as the global is named `acknowledgement` and the transform is `flags`.

How do you verify that the transform is not running? You've checked in your `imagerSystemPath` that the transforms isn't there? 

Considering that the field is named `flag`; what type of images are you adding? SVG's for instance aren't transformed by default, in case that's what you've added.

**Comment by xavianaxw** [comment]
I check in AWS if the file ends up there or not. I'm just uploading jpg/png at this point.

**Comment by xavianaxw** [comment]
I have a question regarding how to test if imager is actually running? Because if I generate transforms manually using the Utilities Generate transforms panel, it doesn't do anything. Does this mean there is an issue with my `imager-x-generate.php` configuration?

Since the utility did state that 
> Use the transforms configured in imager-x-generate.php for each volume. Disable to pick transforms manually.

Here's my configuration to see if I did anything wrong

```
<?php

return [
  'elements' => [
    [
      'elementType' =>  \craft\elements\Entry::class,
      'criteria' => [
        'section' => ['styleguide', 'homepage', 'joinUs'],
      ],
      'fields' => ['heroImage'],
      'transforms' => ['heroImage', 'heroHomepageImage']
    ],
    // [
    //   // benefitsList.image
    //   'elementType' =>  \verbb\supertable\elements\SuperTableBlockElement::class,
    //   'criteria' => [
    //     'fieldId' => 19
    //   ],
    //   'fields' => ['image'],
    //   'transforms' => ['benefitCardImage'],
    // ],
    // [
    //   'elementType' => \craft\elements\Entry::class,
    //   'criteria' => [
    //     'section' => ['styleguide', 'homepage'],
    //   ],
    //   'fields' => ['benefitsList:*.image'],
    //   'transforms' => ['benefitCardImage'],
    // ],
    [
      'elementType' =>  \craft\elements\Entry::class,
      'criteria' => [
        'section' => ['styleguide', 'homepage'],
      ],
      'fields' => ['testimonialAuthorImage'],
      'transforms' => ['testimonialImage']
    ],
    // [
    //   // productCards.image
    //   'elementType' =>  \verbb\supertable\elements\SuperTableBlockElement::class,
    //   'criteria' => [
    //     'fieldId' => 34
    //   ],
    //   'fields' => ['image'],
    //   'transforms' => ['productCardImage'],
    // ],
    // [
    //   'elementType' =>  \verbb\supertable\elements\SuperTableBlockElement::class,
    //   'criteria' => [
    //     'fieldId' => 96
    //   ],
    //   'fields' => ['image'],
    //   'transforms' => ['squareCardImage']
    // ],
    // [
    //   'elementType' =>  \craft\elements\Entry::class,
    //   'criteria' => [
    //     'section' => ['styleguide'],
    //   ],
    //   'fields' => ['mediaBlocks:image'],
    //   'transforms' => ['mediaBlockImage']
    // ],
    [
      'elementType' =>  \craft\elements\Entry::class,
      'criteria' => [
        'section' => ['styleguide', 'joinUs'],
      ],
      'fields' => ['renewalImage'],
      'transforms' => ['renewalImage']
    ],
    [
      'elementType' =>  \craft\elements\Entry::class,
      'criteria' => [
        'section' => ['events'],
      ],
      'fields' => ['eventsImage'],
      'transforms' => ['eventCardImage']
    ],
    [
      'elementType' =>  \craft\elements\Entry::class,
      'criteria' => [
        'section' => ['styleguide'],
      ],
      'fields' => ['videoThumbnail'],
      'transforms' => ['videoImage']
    ],
    [
      'elementType' =>  \craft\elements\Entry::class,
      'criteria' => [
        'section' => ['styleguide'],
      ],
      'fields' => ['resourcesImage'],
      'transforms' => ['resourcesImage']
    ],
    [
      'elementType' => \craft\elements\GlobalSet::class,
      'criteria' => [
        'handle' => ['acknowledgement'],
      ],
      'fields' => ['acknowledgement:*.flag'],
      'transforms' => ['flags'],
    ],
    [
      'elementType' => \craft\elements\GlobalSet::class,
      'criteria' => [
        'handle' => ['callToAction'],
      ],
      'fields' => ['ctaFeaturedImage'],
      'transforms' => ['ctaFeaturedImage'],
    ],
    [
      'elementType' => \craft\elements\GlobalSet::class,
      'criteria' => [
        'handle' => ['callToAction'],
      ],
      'fields' => ['ctaSupportingImage'],
      'transforms' => ['ctaSupportingImage'],
    ],
  ],
];
```

**Comment by aelvan** [comment]
> I check in AWS if the file ends up there or not. I'm just uploading jpg/png at this point.

Make sure to always check in your `imagerSystemPath` first. If the transforms are there, it means there's something wrong with the upload to AWS.

> I have a question regarding how to test if imager is actually running?

To test your transforms and integration with external storages, make a twig template and do a plain transform there.

> Because if I generate transforms manually using the Utilities Generate transforms panel, it doesn't do anything.

The checkbox that says `Use the transforms configured in imager-x-generate.php for each volume.` means that for each selected volume, Imager will use _the auto generate config for that volume_. You don't have any configuration tied to **volumes**, you only have configuration tied to **elements**. See the `volumes` part [here](https://imager-x.spacecat.ninja/configuration.html#configuring-automatic-generation-of-transforms).

If you uncheck that checkbox, you'll be able to select named transforms directly.

**Comment by xavianaxw** [comment]
My upload to AWS seems to work because the other transforms (non supertable related) are actually working.

---

> If you uncheck that checkbox, you'll be able to select named transforms directly.

When I do this, does it just perform a transform for every single image in my volume?

---

Also another question, when I want to test my `imager-x-generate` do I need to remove the asset from the entry and re-select them? or can I just click Save and it will trigger the auto generate? Or perhaps there's more I need to do for the scripts to pick it up to perform the auto generation?

**Comment by aelvan** [comment]
> When I do this, does it just perform a transform for every single image in my volume?

Yes, that will transform every image in the volume. 

> Also another question, when I want to test my imager-x-generate do I need to remove the asset from the entry and re-select them? or can I just click Save and it will trigger the auto generate? Or perhaps there's more I need to do for the scripts to pick it up to perform the auto generation?

It should be sufficient to save. On every save, Imager will check to see if there are assets in the field that the elements definition targets, and create queue jobs for transforming those. If the transforms already exists, the job will just exit without doing anything, and if they dont, it will proceed to create them.

BUT, I should have noticed this earlier and saved us some time... It says you're running Imager X 3.2.4 in your original post. Super table support was added in 3.2.6. Try upgrading.

**Comment by xavianaxw** [comment]
I'll have a look at it sometime this week. Working on other stuff currently.

**Comment by xavianaxw** [comment]
Hey @aelvan it seems to work now after upgrading to `3.2.6` ! Thanks a lot 👍 

---

I have one more scenario that I'm trying to work out. Here's how the field is setup.

FieldName: `mediaBlocks`
Type: SuperTable
---
Fields:
- toggle | Lightswitch
- asset | Matrix
- richtext | Redactor
- buttons | Matrix

Under `asset`, I have two matrix blocks called `image` and `video` that has the Asset field called `thumbnail`. Here's how my `imager-x-generate.php` looks like for this field.

```
[
  'elementType' =>  \craft\elements\Entry::class,
  'criteria' => [
    'section' => ['styleguide'],
  ],
  'fields' => ['mediaBlocks:*.image'],
  'transforms' => ['mediaBlockImage']
],
```

I've also tried the following but to no success.

```
[
  'elementType' =>  \craft\elements\Entry::class,
  'criteria' => [
    'section' => ['styleguide'],
  ],
  'fields' => ['mediaBlocks:*.asset:image.thumbnail'],
  'transforms' => ['mediaBlockImage']
],
```

**Comment by aelvan** [comment]
Nested matrix/supertable fields is not supported in the fields syntax.

In this case, you'd have to target the matrix or supertable elements instead of the entries. [See my comment here](https://github.com/spacecatninja/craft-imager-x/issues/75#issuecomment-731835193).

**Comment by aelvan** [comment]
No response, closing. Please open a new issue if the problem persists.
