### ISSUE TITLE
configuration question

### ISSUE THREAD

**Issue by pioneerdesign** [spacecatninja/craft-imager-x#78]
I'm using imgix with the base url in their configuration pointing at our site root (https://domain.com/). Imger is working but it isn't using the correct path to the asset.  Right now it outputs all images directly off the root ignoring the path.  So if the images was found in /images/team/bio.jpg  it's just out putting it as /bio.jpg

I have the following setup in the configuration: 
    public $transformer = 'imgix';
    public $imagerSystemPath = '@webroot/imager/';
    public $imagerUrl = '/imager/';
 
I'm sure it's very simple I've missed. I thought of pointing imgix to the main uploads folder but it could also have subdirectories within it.

**Comment by aelvan** [comment]
Hi,

In general, the easiest way to use Imgix is pointing your Imgix source at the same folder as your craft volume that hosts your images. But, you can do it the way you've done, and use the `addPath` setting in the Imgix config:

```
'imgixConfig' => [
    'default' => [
        'domain' => 'imager-multi.imgix.net',
        'useHttps' => true,
        'signKey' => 'XxXxXxXx',
        'sourceIsWebProxy' => false,
        'addPath' => [
            'images' => 'images',            
            'documents' => 'documents',            
            'otherstuff' => 'other/stuff',            
        ],
        'getExternalImageDimensions' => true,
        'defaultParams' => ['auto'=>'compress,format', 'q'=>80],
    ]
]
```

So, if you for instance have a volume with handle `team`, that's pointed at `/images/team`, you'd configure it like this:

```
        'addPath' => [
            'team' => 'images/team',            
            // add any other volumes and paths here
        ],
```

Then the resulting url will be `<imgix-url><addPath><assetPath>`, ie `https://my-site.imgix.net/images/team/bio.jpg`.

Hope that helps!
