### ISSUE TITLE
GraphQL support watermark?

### ISSUE THREAD

**Issue by bzkjyf** [spacecatninja/craft-imager-x#79]
hi:
GraphQL support watermark?

**Comment by aelvan** [comment]
Yes, if you create a [named transform](https://imager-x.spacecat.ninja/usage/named-transforms.html) and use that in the `imagerTransform` or `imagerSrcset` directives, or in the `imagerTransform` query, you can use all the functionality in Imager in GraphQL.

**Comment by bzkjyf** [comment]
hi:
how to setup the named transform about watermark？

**Comment by aelvan** [comment]
You could do it something like this:

```
    'watermarkedImage' => [
        'transforms' => [
            ['width' => 600],
            ['width' => 900],
            ['width' => 1200],
        ],
        'defaults' => [
            'ratio' => 16/9,
            'watermark' => [
                'image' => Craft::$app->getAssets()->getAssetById(840),
                'width' => 100,
                'height' => 100,
                'position' => [ 'right' => 10, 'bottom' => 10 ], 
                'opacity' => 0.75, 
                'blendMode' => 'screen'
            ]
        ]
    ],
```

`'image'` can be an Asset model like here, or a url or path to an image inside your webroot. If you want to use opacity like in the example above, the image needs to be a png.

In your templates:

```
{% set transforms = craft.imager.transformImage(image, 'watermarkedImage') %}
<img srcset="{{ transforms | srcset }}">
```
