### ISSUE TITLE
Images not uploading to AWS after transform.

### ISSUE THREAD

**Issue by darionmh** [spacecatninja/craft-imager-x#81]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. We have configured Imager-X to store images on an S3 bucket
2. We have set up multiple transforms in our config to manage image transforms with srcset

### Description
 

We've used Imager 2.0 in the past. We are upgrading to Imager-X and running into issues. I've gotten several transforms configured and have verified they work as they are being stored in the imagerSystemPath location. However, the files are not being uploaded to our configured aws bucket. I cannot find any logs showing that the request failed, so it seems like its just not trying to upload. 

### Additional info

```
return array(
    'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/craft/assets/images/imager/',
    'imagerUrl' => 'https://xxxx.s3.amazonaws.com/',
    'cacheEnabled' => true,
    'cacheRemoteFiles' => true,
    'cacheDuration' => 1209600, // 14 days
    'cacheDurationRemoteFiles' => 1209600, // 14 days
    'jpegQuality' => 80,
    'pngCompressionLevel' => 2,
    'webpQuality' => 80,
    'webpImagickOptions' => array(), // additional options you want to pass to Imagick via '$instance->setOption('webp:option', 'value')'.
    'useCwebp' => false,
    'cwebpPath' => '/usr/bin/cwebp',
    'cwebpOptions' => '', // additional options you want to pass to cwebp. Quality is set automatically.
    'interlace' => false, // false, true ('line'), 'none', 'line', 'plane', 'partition'
    'allowUpscale' => true,
    'resizeFilter' => 'lanczos',
    'smartResizeEnabled' => false,
    'removeMetadata' => false,
    'bgColor' => '',
    'position' => '50% 50%',
    'letterbox' => array('color' => '#000', 'opacity' => 0),
    'hashFilename' => 'postfix', // true, false, or 'postfix' (meaning only the generated part of the filename is hashed)
    'hashPath' => false,
    'hashRemoteUrl' => 'host', // true, false, or 'host' (meaning only the host part of the url is hashed)
    'instanceReuseEnabled' => false,
    'jpegoptimEnabled' => false,
    'jpegoptimPath' => '/usr/bin/jpegoptim',
    'jpegoptimOptionString' => '-s',
    'jpegtranEnabled' => false,
    'jpegtranPath' => '/usr/bin/jpegtran',
    'jpegtranOptionString' => '-optimize -copy none',
    'mozjpegEnabled' => false,
    'mozjpegPath' => '/usr/bin/mozjpeg',
    'mozjpegOptionString' => '-optimize -copy none',
    'optipngEnabled' => false,
    'optipngPath' => '/usr/bin/optipng',
    'optipngOptionString' => '-o5',
    'tinyPngEnabled' => false,
    'tinyPngApiKey' => '',
    'optimizeType' => 'job',
    'logOptimizations' => false,
    'storages' => ['aws'],
    'storageConfig' => [
        'aws' => [
            'accessKey' => 'xxxx',
            'secretAccessKey' => 'xxxx,
            'bucket' => 'xxxx',
            'region' => 'us-east-2',
            'folder' => 'images',
            'public' => true,
            'requestHeaders' => array(),
            'storageType' => 'standard', // 'standard' or 'rrs' (reduced redundancy storage)
            'cloudfrontInvalidateEnabled' => false,
            'cloudfrontDistributionId' => '',
        ],
    ],
    'curlOptions' => array(),
    'runTasksImmediatelyOnAjaxRequests' => true,
    'clearKey' => '', // Key that should be passed to the clear controller action. Empty string means clearing is disabled.
);
```

- Imager version & edition: Pro v3.2.6
- Imager transformer: default
- Craft version: Craft Pro 3.5.9
- PHP version: 7.2.34
- Image driver & version: GD 7.2.34
- Database driver & version: MySQL 5.7.32
- Plugins & versions (if relevant):

**Comment by bymayo** [comment]
Also seeing this issue where transforms are generated locally, and uploading to AWS works perfectly through the CMS, but the generated transform doesn't upload to AWS.

```
         'storages' => ['aws'],
         'storageConfig' => [
            'aws'  => [
               'accessKey' => getenv('AMAZON_S3_KEY_ID'),
               'secretAccessKey' => getenv('AMAZON_S3_ACCESS_KEY'),
               'region' => getenv('AMAZON_S3_REGION'),
               'bucket' => getenv('AMAZON_S3_BUCKET'),
               'folder' => getenv('TRANSFORMS_FOLDER'),
               'requestHeaders' => array(
                  'Cache-Control' => 'max-age=31536000'
               ),
               'storageType' => 'standard',
               'public' => true,
               'cloudfrontInvalidateEnabled' => true,
               'cloudfrontDistributionId' => getenv('CLOUDFRONT_DISTRIBUTION_ID')
         ]
```
Imager version & edition: v3.2.6 Pro
Imager transformer: craft
Craft version: Craft Pro 3.5.16
PHP version: 7.1.33
Image driver & version: Imagick 3.4.3 (ImageMagick 6.9.10-68)
Database driver & version: MySQL 5.5.68

**Comment by aelvan** [comment]
Hi,

Have tested quickly now with the PHP/Imager/Craft versions you're using, but upload still works in my test suit. Can both of you answer the following questions:

Does this happen consistently for all transforms, or only intermittently?
What region are your buckets in (and are you sure you have the right one)? 
Is this on a live server, or in a dev environment? Which server OS / dev environment are you using?
Check your `composer.lock` file, what version of `aws/aws-sdk-php` is installed?

If you can reproduce, make sure to enable the debug toolbar, and run a test. If the setup of the AWS client fails, a log entry that starts with "Invalid configuration of S3 Client: ..." is logged. If something fails during upload, a log entry that starts with "An error occured while uploading to Amazon S3: ..." should be logged. 

And, make sure you delete the relevant images in your `imagerSystemPath` between each test, see https://imager-x.spacecat.ninja/troubleshooting.html#debug-toolbar-and-logs. Or maybe easier, make a really reduced test case with a single transform, and change the transform slightly (ie increase width by 1 or something) between every test.

**Comment by bymayo** [comment]
@aelvan My region is `eu-west-2` and this is testing on a dev environment. I did delete the transforms folder to let Imager regenerate the files locally, and it does, it just never seems to appear on CloudFront.

My settings are being pulled from my `.env` which i'm also using in my Asset settings and I can upload/preview the files perfectly fine through the CMS.

On a second look at this, it seems that it was putting it in the wrong folder and my `imagerUrl` looking for the wrong URL:

Before:
```
imagerUrl => 'https://xxxx.cloudfront.net/uploads/transforms/',
'storageConfig' => [
    'aws'  => [
        'folder' => 'transforms'
    ]
]
```

After
```
imagerUrl => 'https://xxxx.cloudfront.net/uploads/transforms/',
'storageConfig' => [
    'aws'  => [
        'folder' => 'uploads/transforms',
    ]
]
```

**Comment by aelvan** [comment]
@bymayo Ok, so it's working now for you? 

What is `uploads` in your url? You could probably also have done:

```
imagerUrl => 'https://xxxx.cloudfront.net/transforms/',
'storageConfig' => [
    'aws'  => [
        'folder' => 'transforms'
    ]
]
```

**Comment by bymayo** [comment]
@aelvan Yeah all work! Uploads is just another folder. I've moved the assets over from an existing `uploads` folder.

So the path is `uploads/images` and I usually keep the transforms in the same folder e.g. `uploads/transforms`.

I can always move this, but currently it would mean move the transforms or regenerating them but this will take far too long.

**Comment by darionmh** [comment]
I had the wrong region.. fixed that and things are uploading now. I do have a question about generating the assets. How do I do a bulk generation of transforms? The utility doesn't seem to be working for me. They only generate when I save an entry.

**Comment by aelvan** [comment]
@darionmh Great! There are various ways to generate the transforms. 

The utility by default, ie, if "Use configured transforms" is checked, will only generate transforms that are configured per volume, ie under the `volumes` part of your `imager-x-generate.php`. If you uncheck "Use configured transforms" you can select which transforms to generate, independent of what's configured in `imager-x-generate.php`. If that doesn't work, there must be a bug somewhere. Start your debugging and submit a new issue. ;)

You can also [use console commands to batch create transforms](https://imager-x.spacecat.ninja/usage/generate.html#console-commands-for-generating-transforms), and you can do this based on volume (and folder if needed) and fields (ie under the `fields` part of your `imager-x-generate.php`).

Finally, it sounds like you've maybe configured your generate config by targeting `elements` in your `imager-x-generate.php`? To trigger these transforms you'd use Craft's built-in resave functionality, ie `craft resave/entries`. 

Hope that helps!
