### ISSUE TITLE
Calling imager from PHP returns a url but no image exists

### ISSUE THREAD

**Issue by celexus** [spacecatninja/craft-imager-x#84]
### I'm submitting a... 

- [ ] bug report
- [ ] feature request
- [x ] general question

### Steps to reproduce

1.  Call the Imager transform image method from PHP
`private function transformImage($image){`
        `if($image != "" ) {`
            `if ($this->imagerx && $this->imagerx instanceof \spacecatninja\imagerx\ImagerX) {`
                `$transformedImage = $this->imagerx->imager->transformImage($image,`
                    `[`
                        `'width' => 640,`
                        `'height' => 640`
                    `],`
                    `[`
                        `'format' => 'jpg'`
                    `],`
                    `[`
                        `'jpegQuality' => 80`
                    `],`
                    `[`
                        `'removeMetadata' => true`
                    `],`
                    `[`
                        `'interlace' => true`
                    `]);`
                `if (property_exists(LocalSourceImageModel::class, 'url')) {`
                    `return  $transformedImage->url;`
                `}`
            `}`
        `}`
    `}`

### Description
 
It doesn't throw any errors & returns an image url, but when I try to view the image via the browser using the url returned, the image does not exist. 
I've tried setting the permissions to 777 on the imager folder & have checked whether the image exists in the imager folder, which but it doesn't. 

### Displayed errors, stack trace, relevant logs  

`2020-12-30 14:29:58 spacecatninja\imagerx\models\LocalTransformedImageModel Object`
`(`
`    [source] => spacecatninja\imagerx\models\LocalSourceImageModel Object`
`        (`
`            [type] => remoteurl`
`            [path] => /var/www/thebodyshop.co.za/craft3/storage/runtime/imager/clicks_co_za`
`            [transformPath] => /clicks_co_za`
`            [url] => https://clicks.co.za//medias/?context=bWFzdGVyfHByb2R1Y3QtaW1hZ2VzfDc1ODQ4fGltYWdlL2pwZWd8cHJvZHVjdC1pbWFnZXMvaDlmL2g2Mi85MzU2OTE1MjEyMzE4LmpwZ3w4Y2Q3OTE0NTI1NzJmYTdhYzhkYjAxZGY5MTRmMDNiZDFlZjU5ZDg4NGVmZjViNDczNTk5NWY4YWU5NjBjMGQ1`
`            [filename] => medias_a740a3e6241567e9bfbe518f94870572`
`            [basename] => medias_a740a3e6241567e9bfbe518f94870572`
`            [extension] => `
`            [asset:spacecatninja\imagerx\models\LocalSourceImageModel:private] => `
`        )`

`    [path] => /var/www/thebodyshop.co.za/craft3/web/imager/clicks_co_za/medias_a740a3e6241567e9bfbe518f94870572_0cf4070675dde88e45dfd92a7d0f1ef7.jpg`
 `   [filename] => medias_a740a3e6241567e9bfbe518f94870572_0cf4070675dde88e45dfd92a7d0f1ef7.jpg`
`    [url] => /imager/clicks_co_za/medias_a740a3e6241567e9bfbe518f94870572_0cf4070675dde88e45dfd92a7d0f1ef7.jpg`
`    [extension] => jpg`
`    [mimeType] => image/jpeg`
`    [width] => 640`
`    [height] => 640`
`    [size] => 78121`
`    [isNew] => `
`)`
```

### Additional info

- Imager version & edition: Imager X v3.2.5
- Craft version: Craft Pro 3.5.13.2
- PHP version: 7.4.3
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.10-23)
- Database driver & version: MySQL 8.0.22

**Comment by aelvan** [comment]
Hi, sorry for the late reply, recuperating from the holidays.

Did a quick test, and I'm able to transform the image in question, so it's some kind of environment/config issue.

So, you said that there's no transformed images in `/var/www/thebodyshop.co.za/craft3/web/imager/clicks_co_za/` after running the code? What about in `/var/www/thebodyshop.co.za/craft3/storage/runtime/imager/clicks_co_za`?

Make sure you're running in devMode and don't have `suppressExceptions` set to `true`, that would silence most errors. Did you check your logs for errors?

Do you have any external storages configured in imager-x.php?

How is this php code being executed? Is it through a template variable, a queue job, etc?

Btw, since your external url uses query strings to identify the image, you should set `useRemoteUrlQueryString` to `true`, [see docs](https://imager-x.spacecat.ninja/configuration.html#useremoteurlquerystring-bool). I don't think that'll make any difference about this error, but try enabling that just to be sure.

**Comment by celexus** [comment]
Hi, thank you so much for the reply. 

I use imager in my templates & it works beautifully. 

This php code is from a console controller that I wrote which generates an xml export of all products. 
I am currently manually executing it from the command line:
`php /var/www/thebodyshop.co.za/craft3/craft clicks-module/export/export-all-products`
In the long term it will be executed via a cron job. 

There are transformed images in `/var/www/thebodyshop.co.za/craft3/web/imager/clicks_co_za/` and in `/var/www/thebodyshop.co.za/craft3/storage/runtime/imager/clicks_co_za` but they are the transformed images generated from the templates. 
None of the paths that are output in the export file that I'm generating exist anywhere on the server. 
Whenever I try to browse any of the urls I get a 404. 

The worst part is that I'm not getting any errors whatsoever. 

I do not have external storages configured in imager-x.php.

I do have `useRemoteUrlQueryString `set to `true`

**Comment by aelvan** [comment]
And you've checked the `console.log` file for errors (that's where errors from console commands will end up)?

What environment is your server (OS/webserver)?

**Comment by celexus** [comment]
Yes, I've checked `console.log`

Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-53-generic x86_64))

**Comment by aelvan** [comment]
Ok, let me try to set up a console command test. 

Could you paste your complete imager-x.php file here for reference. Remove/obskure anything sensitive.

**Comment by celexus** [comment]
```
<?php
/**
 * General Configuration
 *
 * All of your system's general configuration settings go in here. You can see a
 * list of the available settings in vendor/craftcms/cms/src/config/GeneralConfig.php.
 *
 * @see \craft\config\GeneralConfig
 */

use craft\helpers\App;

return [
    // Global settings
    '*' => [
        'useRemoteUrlQueryString' => true
        ]
];
```

**Comment by aelvan** [comment]
Created a console command to test this, and it seems to work as it should for me. I didn't pick up on it before copying the code from your original post, but you're passing in the parameters in the wrong way. All the transform parameters should go into the second argument of transformImage (as long as you're only creating a single transform), like so:

```
$transformedImage = $this->imagerx->imager->transformImage($image,
    [
        'width' => 640,
        'height' => 640,
        'format' => 'jpg',
        'jpegQuality' => 80,
        'removeMetadata' => true,
        'interlace' => true
    ]);
```

But, that's probably not the cause of the error either, as there would still be a transform made with your original code, it would just ignore some of the parameters passed.

K, so reaching for straws here, but.. How do you set `$this->imagerx`? And where does `$image` come from? Could it be that it's some kind of object, not a string? Try typecasting it explicitely with `(string)$image` maybe?

**Comment by celexus** [comment]
That did it ! The explicit cast to string! Can't believe it - thank you for your help

**Comment by aelvan** [comment]
Ah, great! Then I guess if was probably some kind of model before, maybe a DOMElement if it came from a XML or something. Great that we got it figured out. :)
