### ISSUE TITLE
GraphQL won't transform source images that are WebP

### ISSUE THREAD

**Issue by alexroper** [spacecatninja/craft-imager-x#85]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Example code used in a Twig template:

```
<pre>
{% set image = craft.assets.id(145).one() %}

Original image: {{ image.filename }} 

Craft transform: {{ image.getUrl({width: 300}) }}

{% set resized = craft.imager.transformImage(image, { width: 300}) %}

Imager transform: {{ resized.url }}

{% set result = gql('
{
  asset (id: 145) {
    url (width: 300)
    imager: url @imagerTransform (width: 300)
  }
}') %}

{{ dump(result) }}
</pre>
```
2. Example output:

```
Original image: film-philosophy-03.webp 

Craft transform: {site_url}/images/films/_300xAUTO_crop_center-center_none/film-philosophy-03.webp?mtime=20201214133917&focal=none&tmtime=20210113155737

Imager transform: /imager/images/films/145/film-philosophy-03_9d774b89831857b4dfc965837c0ae6fd.webp


array(1) {
  ["data"]=>
  array(1) {
    ["asset"]=>
    array(2) {
      ["url"]=>
      string(159) "{site_url}/images/films/_300xAUTO_crop_center-center_none/film-philosophy-03.webp?mtime=20201214133917&focal=none&tmtime=20210113155737"
      ["imager"]=>
      NULL
    }
  }
}
```

### Description

Imager doesn't seem to be able to creates transforms from source WebP images. GraphQL query returns `null` every time.

Transforms made from Jpegs work fine. Transforms made with Craft's transform method on the same image work correctly as well.

### Additional info

- Imager version & edition: Pro v3.2.6
- Imager transformer: craft
- Craft version: Craft Pro 3.5.17.1
- PHP version: 7.3.21
- Image driver & version: Imagick 3.4.4 (ImageMagick 6.9.6-2)
- Database driver & version: MySQL 5.7.30

**Comment by aelvan** [comment]
Try enabling `webp` in the [`safeFileFormats` config setting](https://imager-x.spacecat.ninja/configuration.html#safefileformats-array), ie:

```
'safeFileFormats' => ['jpg', 'jpeg', 'gif', 'png', 'webp']
```

Those file formats are the ones that will be transformed in scenarios where you can't easily use conditionals to check what type of files to transform (like, CP transforms, auto generate and GQL (although not in the docs, I see now)). Since support for opening and transforming webp files is not very widespread, that webp is not enabled by default.

**Comment by alexroper** [comment]
Ah ha! That works. Thank you.

I'm fairly new to GraphQL so it was driving me bonkers as to why it kept returning "null."
