### ISSUE TITLE
Image not showing when using Sprig to reload entries - Safari only

### ISSUE THREAD

**Issue by philipboomy** [spacecatninja/craft-imager-x#87]
### I'm submitting a... 
- [ x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce
1. Use the Imager src set feature
2. Filtering entries using Sprig https://putyourlightson.com/plugins/sprig
3. See image is not showing but it exist in the DOM - Only on Safari

### Description

It is an odd one and an edge case but I would still love to see if I could fix this.

When doing this
```
{% set transformedImages = craft.imager.transformImage(image, imageSizes) %}
<picture>
 <source  sizes="100vw" srcset="{{ craft.imager.srcset(transformedImages) }}">
 <img src="{{ image.url }}" sizes="100vw">
</picture>
```

then the image is showing but when using Sprig to filter a query then the image is not showing but if you inspect the dom its there.

It only happens when using imager like above. If I manually build the src set with normal Craft image transform then it works. If I use Imager with only a img tag it works.

### Displayed errors, stack trace, relevant logs  

Before filtering using Sprig
https://share.getcloudapp.com/ApuRrg84
https://share.getcloudapp.com/L1uNgvzy

After filtering
https://share.getcloudapp.com/Jru1Wewe
https://share.getcloudapp.com/llu9yXyw

### Additional info

- Imager version & edition:
Craft 3.5.19.1
Imager X v3.3.0
PHP version | 7.4.14
Image driver & version | Imagick 3.4.4 (ImageMagick 7.0.10-55)

**Comment by aelvan** [comment]
Hi, 

That's an odd one, having a hard time seeing how using Imager would matter. As long as the HTML is served to the browser, and the images are valid, Imager shouldn't really be part of the equation at that point. But, let's try to get to the root of it.

Have you checked the network tab in the inspector; does the browser try to load the images at all? Any 404's?
Have you tried using full URL's for your transformed files (by changing the `imagerUrl` in your config to a full URL)? 

Could you provide me with a minimal twig template with Sprig that reproduces this? I've never used Sprig. :)

**Comment by philipboomy** [comment]
Yeah I agree and should have gone with my gut instinct that it wasn't related to Imager. I manually created srcset was not created correctly so it was not using the source element inside my picture element. It was using the img tag. So that is why it worked with Sprig. Bottom line Imager is working correctly. False alarm. Sorry about the and thanks responding so quickly.

**Comment by aelvan** [comment]
Great, hope you figure out the underlying issue.
