### ISSUE TITLE
'Unknown directive \"imagerTransform\".' error

### ISSUE THREAD

**Issue by Saboteur777** [spacecatninja/craft-imager-x#89]
### I'm submitting a... 

- [x] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. Navigate to GraphQL > GraphiQL.
2. Try the example query - it errors out for me, see the error message below.

### Displayed errors, stack trace, relevant logs  

```
{
  "errors": [
    {
      "message": "Unknown directive \"imagerTransform\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 7,
          "column": 22
        }
      ]
    }
  ]
}
```

### Additional info

- Imager version & edition: v3.3.0
- Craft version: Craft Pro 3.6.5.1
- PHP version: 7.4.11
- Image driver & version: Imagick 3.4.4 (ImageMagick 7.0.10-25)
- Database driver & version: MySQL 5.5.5

**Comment by aelvan** [comment]
Hi, 

I've tested this with the versions specified, but can not reproduce. All the directives and the query works as expected.

Just to be clear, is it the query or the directive you're testing (dumb of me to name them the same :-/)? 
Did you upgrade Imager to the pro edition (GraphQL is a pro-only feature)?
Do Imager work when used directly in your templates?
Could you post the graphql code that you have in GraphiQL?

**Comment by Saboteur777** [comment]
Well... :man_facepalming: I installed it from the CLI and did not upgrade it to the Pro edition. Upgrading it solved the issue, thanks!

**Comment by aelvan** [comment]
Great! :)
