### ISSUE TITLE
Environment Variables in Config File?

### ISSUE THREAD

**Issue by brianrivet-tilt** [spacecatninja/craft-imager-x#92]
Hi,

I'm running Craft 3.6.10, ImagerX v. 3.3.0. I'm trying to use environment variables in the config to connect up ImgIX. I wanted to use env variables for the domain, api key, and sign token. I have the environment variables set up, but when I try to use them in the config I get this error:

> Exception – spacecatninja\imagerx\exceptions\ImagerException
> UrlBuilder must be passed a string domain
> ↵
> Caused by: InvalidArgumentException
> UrlBuilder must be passed a string domain
> in /Users/Brian/WebDev/sites/website/vendor/imgix/imgix-php/src/Imgix/UrlBuilder.php at line 36

Here's how I have it in my config:

```
return [
	'transformer' => 'imgix',
	'jpegQuality' => 70,
	'webpQuality' => 70,
	'imgixApiKey' => craft\helpers\App::env('IMGIX_API_KEY'),
	'imgixConfig' => [
		'default' => [
			'domain' => craft\helpers\App::env('IMGIX_DOMAIN'),
			'useHttps' => true,
			'signKey' => craft\helpers\App::env('IMGIX_TOKEN'),
			'sourceIsWebProxy' => false,
			'useCloudSourcePath' => true,
			'getExternalImageDimensions' => true,
			'defaultParams' => ['auto'=>'compress,format', 'q'=>70],
		],		
	]
```

I'm sure that I'm referencing them incorrectly, but I'm not sure how to do it correctly. Can you assist me?

**Comment by aelvan** [comment]
Hi Brian,

Looks like Mats helped you out on discord this morning? You figured it out?

**Comment by brianrivet-tilt** [comment]
Yes, we sorted it out. Thanks for getting back to me!
