### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by christianruhstaller** [spacecatninja/craft-imager-x#94]
Currently it's not possible to install this plugin while running PHP 8 because of "imageoptim/imageoptim".

The imageoptim package has currently following constraints on the PHP version "^5.4 || ^7.0" and it does not look like it's actively maintained anymore.

Any plans to mitigate this issue?

**Comment by aelvan** [comment]
Thanks for reporting. Yes, I'll probably have to separate out that optimizer into a separate plugin so that Imager can move forward. Will try to get that done soonish.

**Comment by aelvan** [comment]
This has been fixed in v3.4.0 which is just out. The ImageOptim optimizer has been split out into [a separate plugin](https://github.com/spacecatninja/craft-imager-x-imageoptim-optimizer).
